### ISSUE TITLE
Services::WebhooksController#create with HTTP_X-Pagure-Signature-256 http header behaves like it verifies the signature when token is invalid renders an error with an invalid token

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#10231]
```
    Failure/Error: expect(response).to be_forbidden
      expected `#<ActionDispatch::TestResponse:0x0000559b3fa8bf58 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::...ders:0x0000559b3fa6cb08 @req=#<ActionController::TestRequest:0x0000559b3fa94248 ...>>, @variant=[]>>.forbidden?` to return true, got false
    Shared Example Group: "it verifies the signature" called from ./spec/controllers/services/webhooks_controller_spec.rb:94
    ./spec/controllers/services/webhooks_controller_spec.rb:39:in `block (5 levels) in <top (required)>'
```

Link to [CircleCI](https://app.circleci.com/pipelines/github/openSUSE/open-build-service/1615/workflows/9035bf25-cfd3-47dc-9ce9-1fb616d7802b/jobs/50830)

**Comment by dmarcoux** [comment]
Similar error:

```
Failure/Error: expect(response).to be_forbidden
  expected `#<ActionDispatch::TestResponse:0x000055b8f62f21a0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::...ders:0x000055b8f40ad8b0 @req=#<ActionController::TestRequest:0x000055b8f62f2308 ...>>, @variant=[]>>.forbidden?` to return true, got false
Shared Example Group: "it verifies the signature" called from ./spec/controllers/services/webhooks_controller_spec.rb:82
./spec/controllers/services/webhooks_controller_spec.rb:39:in `block (5 levels) in <top (required)>'
```

**Comment by hennevogel** [comment]
You find flickering specs on circle now.

https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests?branch=master&reporting-window=last-30-days
