### ISSUE TITLE
test_accept_request_does_not_revoke_request_for_single_package - ProjectRemoveTest

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#10237]
```
<status code="404">

  <summary>project 'home:Iggy:branches:Apache' does not exist</summary>

  <details>404 project 'home:Iggy:branches:Apache' does not exist</details>

</status>


app/lib/backend/connection.rb:123:in `handle_response'
app/lib/backend/connection.rb:113:in `put_or_post'
app/lib/backend/connection.rb:35:in `put'
app/lib/backend/connection_helper.rb:62:in `http_put'
app/lib/backend/api/sources/project.rb:41:in `write_meta'
app/lib/backend/remember_location.rb:15:in `call'
app/lib/backend/remember_location.rb:15:in `block in singleton_method_added'
app/models/project.rb:795:in `write_to_backend'
app/models/project.rb:810:in `block in store'
app/models/project.rb:808:in `store'
app/models/branch_package.rb:285:in `create_branch_project'
app/models/branch_package.rb:83:in `branch'
test/unit/project_remove_test.rb:112:in `branch_package'
test/unit/project_remove_test.rb:48:in `test_accept_request_does_not_revoke_request_for_single_package'
test/test_helper.rb:116:in `block in __run'
test/test_helper.rb:116:in `map'
test/test_helper.rb:116:in `__run'
```

Link to [CircleCI](https://app.circleci.com/pipelines/github/openSUSE/open-build-service/1559/workflows/bbcccf63-55ac-4436-9b20-653e052c21fb/jobs/50539)

**Comment by hennevogel** [comment]
You find flickering specs on circle now.

https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests?branch=master&reporting-window=last-30-days
