### ISSUE TITLE
SourceControllerTest - a lot of flickering tests

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#10235]
test_branch_repository_with_extra_policy:
```
Expected response to be a <2XX: success>, but was a <404: Not Found>

Response body: <status code="not_found">

  <summary>&lt;status code="404"&gt;

  &lt;summary&gt;project 'home:adrian:branches:home:adrian:TEMP' does not exist&lt;/summary&gt;

  &lt;details&gt;404 project 'home:adrian:branches:home:adrian:TEMP' does not exist&lt;/details&gt;

&lt;/status&gt;

</summary>

</status>


test/functional/source_controller_test.rb:2458:in `test_branch_repository_with_extra_policy'
test/test_helper.rb:116:in `block in __run'
test/test_helper.rb:116:in `map'
test/test_helper.rb:116:in `__run'
```

Link to [CircleCI](https://app.circleci.com/pipelines/github/openSUSE/open-build-service/1459/workflows/0ff4dbe7-0567-41dd-8ccb-979f2893bb6d/jobs/49991)

**Comment by dmarcoux** [comment]
And much more as we can see on CircleCI: [1](https://app.circleci.com/pipelines/github/openSUSE/open-build-service/1620/workflows/5fb0eb65-7a6a-4060-9636-425cd9aff710/jobs/50866), [2](https://app.circleci.com/pipelines/github/openSUSE/open-build-service/1618/workflows/96feda94-429d-4b09-8b0f-ba05644831fd/jobs/50852)

:warning: WALL OF TEXT ALARM! YOU WERE WARNED :smile: :warning:

```
    test_delete_and_undelete_permissions - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <500: Internal Server Error>
    test/functional/source_controller_test.rb:3571:in `test_delete_and_undelete_permissions'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run' 
```        
```
    test_diff_package - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="not_found">

      <summary>&lt;status code="404"&gt;

      &lt;summary&gt;project 'kde4' does not exist&lt;/summary&gt;

      &lt;details&gt;404 project 'kde4' does not exist&lt;/details&gt;

    &lt;/status&gt;

    </summary>

    </status>


    test/functional/source_controller_test.rb:2066:in `test_diff_package'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'  
```        
```
    test_diff_package_hidden_project - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="not_found">

      <summary>&lt;status code="404"&gt;

      &lt;summary&gt;project 'kde4' does not exist&lt;/summary&gt;

      &lt;details&gt;404 project 'kde4' does not exist&lt;/details&gt;

    &lt;/status&gt;

    </summary>

    </status>


    test/functional/source_controller_test.rb:2092:in `test_diff_package_hidden_project'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'     
```        
```
    test_diff_package_sourceaccess_protected_project - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="not_found">

      <summary>&lt;status code="404"&gt;

      &lt;summary&gt;project 'kde4' does not exist&lt;/summary&gt;

      &lt;details&gt;404 project 'kde4' does not exist&lt;/details&gt;

    &lt;/status&gt;

    </summary>

    </status>


    test/functional/source_controller_test.rb:2122:in `test_diff_package_sourceaccess_protected_project'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'     
```        
```
    test_get_package_filelist - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="404">

      <summary>project 'kde4' does not exist</summary>

      <details>404 project 'kde4' does not exist</details>

    </status>


    test/functional/source_controller_test.rb:215:in `test_get_package_filelist'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'    
```        
```
    test_get_package_meta - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="404">

      <summary>project 'kde4' does not exist</summary>

      <details>404 project 'kde4' does not exist</details>

    </status>


    test/functional/source_controller_test.rb:265:in `test_get_package_meta'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'    
```        
```
    test_get_package_meta_file - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="404">

      <summary>_meta: no such file</summary>

      <details>404 _meta: no such file</details>

    </status>


    test/functional/source_controller_test.rb:1783:in `test_get_package_meta_file'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'      
```        
```
    test_get_package_meta_history - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="404">

      <summary>project 'kde4' does not exist</summary>

      <details>404 project 'kde4' does not exist</details>

    </status>


    test/functional/source_controller_test.rb:1715:in `test_get_package_meta_history'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'  
```        
```
    test_get_project_meta_history - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="404">

      <summary>project 'kde4' does not exist</summary>

      <details>404 project 'kde4' does not exist</details>

    </status>


    test/functional/source_controller_test.rb:1736:in `test_get_project_meta_history'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'     
```        
```
    test_prjconf - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="not_found">

      <summary>Content undefined method `force_encoding' for #&lt;Net::ReadAdapter&gt;</summary>

    </status>


    test/functional/source_controller_test.rb:2219:in `test_prjconf'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'
```        
```
    test_public_keys - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected /kde4: no pubkey available/ to match "<status code=\\"404\\">\

      <summary>project 'kde4' does not exist</summary>\

      <details>404 project 'kde4' does not exist</details>\

    </status>\

    ".
    test/functional/source_controller_test.rb:2244:in `test_public_keys'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'       
```        
```
    test_put_package_meta - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="not_found">

      <summary>&lt;status code="404"&gt;

      &lt;summary&gt;project 'kde4' does not exist&lt;/summary&gt;

      &lt;details&gt;404 project 'kde4' does not exist&lt;/details&gt;

    &lt;/status&gt;

    </summary>

    </status>


    test/functional/source_controller_test.rb:972:in `do_change_package_meta_test'
    test/functional/source_controller_test.rb:997:in `test_put_package_meta'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'
```        
```
    test_read_file - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="404">

      <summary>package 'kdelibs' does not exist</summary>

      <details>404 package 'kdelibs' does not exist</details>

    </status>


    test/functional/source_controller_test.rb:1462:in `test_read_file'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'
```        
```
    test_remove_and_undelete_operations - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="not_found">

      <summary>&lt;status code="404"&gt;

      &lt;summary&gt;package 'kdelibs' does not exist&lt;/summary&gt;

      &lt;details&gt;404 package 'kdelibs' does not exist&lt;/details&gt;

    &lt;/status&gt;

    </summary>

    </status>


    test/functional/source_controller_test.rb:1884:in `test_remove_and_undelete_operations'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'    
```        
```
    test_use_illegal_encoded_parameters - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="not_found">

      <summary>&lt;status code="404"&gt;

      &lt;summary&gt;package 'kdelibs' does not exist&lt;/summary&gt;

      &lt;details&gt;404 package 'kdelibs' does not exist&lt;/details&gt;

    &lt;/status&gt;

    </summary>

    </status>


    test/functional/source_controller_test.rb:172:in `test_use_illegal_encoded_parameters'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'
```        
```
    test_use_project_link_as_non_maintainer - SourceControllerTest
    test/functional/source_controller_test.rb

    Expected response to be a <2XX: success>, but was a <404: Not Found>

    Response body: <status code="404">

      <summary>package 'kdelibs' does not exist</summary>

      <details>404 package 'kdelibs' does not exist</details>

    </status>


    test/functional/source_controller_test.rb:3483:in `test_use_project_link_as_non_maintainer'
    test/test_helper.rb:116:in `block in __run'
    test/test_helper.rb:116:in `map'
    test/test_helper.rb:116:in `__run'
```

**Comment by hennevogel** [comment]
You find flickering specs on circle now.

https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests?branch=master&reporting-window=last-30-days
