### ISSUE TITLE
test_submit_request - ProductTests

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#10234]
```
Expected response to be a <2XX: success>, but was a <404: Not Found>

Response body: <status code="not_found">

  <summary>&lt;status code="404"&gt;

  &lt;summary&gt;project 'home:tom:temporary' does not exist&lt;/summary&gt;

  &lt;details&gt;404 project 'home:tom:temporary' does not exist&lt;/details&gt;

&lt;/status&gt;

</summary>

</status>


test/functional/product_test.rb:348:in `test_submit_request'
test/test_helper.rb:116:in `block in __run'
test/test_helper.rb:116:in `map'
test/test_helper.rb:116:in `__run'
```

Link to [CircleCI](https://app.circleci.com/pipelines/github/openSUSE/open-build-service/1459/workflows/69e7e2f2-fc67-429f-bcd5-0520f1260d65/jobs/49953)

**Comment by hennevogel** [comment]
You find flickering specs on circle now.

https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests?branch=master&reporting-window=last-30-days
