### ISSUE TITLE
Login to obs using username with dot not possible

### ISSUE THREAD

**Issue by c-hoeger** [openSUSE/open-build-service#1064]
whenever I create a user containing a dot, e.g. carsten.hoeger, I cannot login with that user.

linux:~ # osc api /person
<directory count="4">
 <entry name="Admin"/>
 <entry name="_nobody_"/>
 <entry name="choeger"/>
 <entry name="carsten.hoeger"/>
</directory>

login using choeger works, login using carsten.hoeger doesn’t.

Is that really the case or am I hitting a bug here?

==> /srv/www/obs/api/log/production.log <==
[6abee853-7581-4f09-8415-0b481354ca0f] [1457:17274.48] Started GET "/" for 172.16.210.1 at 2015-08-26 13:27:26 +0000
[6abee853-7581-4f09-8415-0b481354ca0f] [1457:17274.49] Processing by Webui::MainController#index as HTML
[6abee853-7581-4f09-8415-0b481354ca0f] [1457:17274.49] Anonymous request to /
[6abee853-7581-4f09-8415-0b481354ca0f] [1457:17274.50]   Rendered webui/main/_systemstatus.html.erb (2.2ms)
[6abee853-7581-4f09-8415-0b481354ca0f] [1457:17274.50]   Rendered shared/_sign_up.html.erb (1.0ms)
[6abee853-7581-4f09-8415-0b481354ca0f] [1457:17274.50]   Rendered webui/main/_sponsors.html.erb (0.0ms)
[6abee853-7581-4f09-8415-0b481354ca0f] [1457:17274.50]   Rendered webui/main/_news.html.erb (0.0ms)
[6abee853-7581-4f09-8415-0b481354ca0f] [1457:17274.51]   Rendered webui/main/index.html.erb within layouts/webui/webui (7.8ms)
[6abee853-7581-4f09-8415-0b481354ca0f] [1457:17274.51]   Rendered layouts/webui/_watch_and_search.html.erb (0.4ms)
[6abee853-7581-4f09-8415-0b481354ca0f] [1457:17274.51]   Rendered layouts/webui/_header.html.erb (0.8ms)
[6abee853-7581-4f09-8415-0b481354ca0f] [1457:17274.51]   Rendered layouts/webui/_personal_navigation.html.erb (1.2ms)
[6abee853-7581-4f09-8415-0b481354ca0f] [1457:17274.51]   Rendered layouts/webui/_flash.html.erb (0.0ms)
[6abee853-7581-4f09-8415-0b481354ca0f] [1457:17274.51] Completed 200 OK in 23ms (Views: 12.9ms | ActiveRecord: 2.0ms | Backend: 0.0ms | XML: 0.0ms)

==> /srv/www/obs/api/log/apache_access.log <==
172.16.210.1 - - [26/Aug/2015:13:27:26 +0000] "GET / HTTP/1.1" 200 5136

==> /srv/www/obs/api/log/delayed_job.log <==
I, [2015-08-26T13:27:30.273416 #1509]  INFO -- : 2015-08-26T13:27:30+0000: [Worker(delayed_job.1020 host:linux pid:1509)] Job Event::NotifyBackends#send_not_in_queue (id=626) RUNNING
I, [2015-08-26T13:27:30.276198 #1509]  INFO -- : 2015-08-26T13:27:30+0000: [Worker(delayed_job.1020 host:linux pid:1509)] Job Event::NotifyBackends#send_not_in_queue (id=626) COMPLETED after 0.0025
I, [2015-08-26T13:27:30.277572 #1509]  INFO -- : 2015-08-26T13:27:30+0000: [Worker(delayed_job.1020 host:linux pid:1509)] 1 jobs processed at 82.5002 j/s, 0 failed

==> /srv/www/obs/api/log/production.log <==
[d9417421-1036-4233-9318-b5ca97fa78cf] [1457:17284.39] Started POST "/user/do_login" for 172.16.210.1 at 2015-08-26 13:27:36 +0000
[d9417421-1036-4233-9318-b5ca97fa78cf] [1457:17284.39] Processing by Webui::UserController#do_login as HTML
[d9417421-1036-4233-9318-b5ca97fa78cf] [1457:17284.39]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"gvWNQtEO0Jk8UCwFnbgxMxqM01iJ2VLnwBg3IH2CwyI=", "return_to_path"=>"/", "username"=>"carsten.hoeger", "password"=>"[FILTERED]", "commit"=>"Log In"}
[d9417421-1036-4233-9318-b5ca97fa78cf] [1457:17284.39] Anonymous request to /
[65815885-dbab-4885-8025-9c5891d81849] [1465:15445.79] Started POST "/person/carsten.hoeger/login" for ::1 at 2015-08-26 13:27:36 +0000
[65815885-dbab-4885-8025-9c5891d81849] [1465:15445.79]
ActionController::RoutingError (No route matches [POST] "/person/carsten.hoeger/login"):
 actionpack (4.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
 actionpack (4.1.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
 railties (4.1.6) lib/rails/rack/logger.rb:38:in `call_app'
 railties (4.1.6) lib/rails/rack/logger.rb:20:in `block in call'
 activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
 activesupport (4.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
 activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `tagged'
 railties (4.1.6) lib/rails/rack/logger.rb:20:in `call'
 actionpack (4.1.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
 rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
 rack (1.5.2) lib/rack/runtime.rb:17:in `call'
 activesupport (4.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
 rack (1.5.2) lib/rack/lock.rb:17:in `call'
 rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
 hoptoad_notifier (2.4.11) lib/hoptoad_notifier/user_informer.rb:12:in `call'
 railties (4.1.6) lib/rails/engine.rb:514:in `call'
 railties (4.1.6) lib/rails/application.rb:144:in `call'
 railties (4.1.6) lib/rails/railtie.rb:194:in `public_send'
 railties (4.1.6) lib/rails/railtie.rb:194:in `method_missing'
 passenger (5.0.7) lib/phusion_passenger/rack/thread_handler_extension.rb:89:in `process_request'
 passenger (5.0.7) lib/phusion_passenger/request_handler/thread_handler.rb:155:in `accept_and_process_next_request'
 passenger (5.0.7) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
 passenger (5.0.7) lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
 passenger (5.0.7) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'

==> /srv/www/obs/api/log/apache_access.log <==
::1 - - [26/Aug/2015:13:27:36 +0000] "POST /person/carsten.hoeger/login HTTP/1.1" 404 104

==> /srv/www/obs/api/log/production.log <==
[d9417421-1036-4233-9318-b5ca97fa78cf] [1457:17284.40] Completed 500 Internal Server Error in 10ms
[d9417421-1036-4233-9318-b5ca97fa78cf] [1457:17284.40]
ActiveXML::Transport::NotFoundError (<?xml version="1.0" encoding="UTF-8"?>
<hash>
 <status>404</status>
 <error>Not Found</error>
</hash>
):
 lib/activexml/transport.rb:447:in `handle_response'
 lib/activexml/transport.rb:394:in `http_do'
 lib/activexml/transport.rb:231:in `direct_http'
 app/controllers/webui/user_controller.rb:42:in `do_login'
 actionpack (4.1.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
 actionpack (4.1.6) lib/abstract_controller/base.rb:189:in `process_action'
 actionpack (4.1.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
 actionpack (4.1.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
 activesupport (4.1.6) lib/active_support/callbacks.rb:113:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:113:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
 activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
 activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
 activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
 activesupport (4.1.6) lib/active_support/callbacks.rb:229:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:229:in `block in halting'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
 activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
 activesupport (4.1.6) lib/active_support/callbacks.rb:229:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:229:in `block in halting'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
 activesupport (4.1.6) lib/active_support/callbacks.rb:86:in `call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:86:in `run_callbacks'
 actionpack (4.1.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
 actionpack (4.1.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
 actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
 activesupport (4.1.6) lib/active_support/notifications.rb:159:in `block in instrument'
 activesupport (4.1.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
 activesupport (4.1.6) lib/active_support/notifications.rb:159:in `instrument'
 actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
 actionpack (4.1.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
 activerecord (4.1.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
 actionpack (4.1.6) lib/abstract_controller/base.rb:136:in `process'
 actionview (4.1.6) lib/action_view/rendering.rb:30:in `process'
 actionpack (4.1.6) lib/action_controller/metal.rb:196:in `dispatch'
 actionpack (4.1.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
 actionpack (4.1.6) lib/action_controller/metal.rb:232:in `block in action'
 actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:82:in `call'
 actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
 actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:50:in `call'
 actionpack (4.1.6) lib/action_dispatch/routing/mapper.rb:45:in `call'
 actionpack (4.1.6) lib/action_dispatch/journey/router.rb:73:in `block in call'
 actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `each'
 actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `call'
 actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:678:in `call'
 config/initializers/wrap_parameters.rb:41:in `call'
 hoptoad_notifier (2.4.11) lib/hoptoad_notifier/rack.rb:27:in `call'
 rack (1.5.2) lib/rack/deflater.rb:25:in `call'
 rack (1.5.2) lib/rack/etag.rb:23:in `call'
 rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
 rack (1.5.2) lib/rack/head.rb:11:in `call'
 actionpack (4.1.6) lib/action_dispatch/middleware/flash.rb:254:in `call'
 rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
 rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
 actionpack (4.1.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
 activerecord (4.1.6) lib/active_record/query_cache.rb:36:in `call'
 activerecord (4.1.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
 actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
 activesupport (4.1.6) lib/active_support/callbacks.rb:82:in `run_callbacks'
 actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
 actionpack (4.1.6) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
 actionpack (4.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
 actionpack (4.1.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
 railties (4.1.6) lib/rails/rack/logger.rb:38:in `call_app'
 railties (4.1.6) lib/rails/rack/logger.rb:20:in `block in call'
 activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
 activesupport (4.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
 activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `tagged'
 railties (4.1.6) lib/rails/rack/logger.rb:20:in `call'
 actionpack (4.1.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
 rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
 rack (1.5.2) lib/rack/runtime.rb:17:in `call'
 activesupport (4.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
 rack (1.5.2) lib/rack/lock.rb:17:in `call'
 rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
 hoptoad_notifier (2.4.11) lib/hoptoad_notifier/user_informer.rb:12:in `call'
 railties (4.1.6) lib/rails/engine.rb:514:in `call'
 railties (4.1.6) lib/rails/application.rb:144:in `call'
 railties (4.1.6) lib/rails/railtie.rb:194:in `public_send'
 railties (4.1.6) lib/rails/railtie.rb:194:in `method_missing'
 passenger (5.0.7) lib/phusion_passenger/rack/thread_handler_extension.rb:89:in `process_request'
 passenger (5.0.7) lib/phusion_passenger/request_handler/thread_handler.rb:155:in `accept_and_process_next_request'
 passenger (5.0.7) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
 passenger (5.0.7) lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
 passenger (5.0.7) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'

==> /srv/www/obs/api/log/apache_access.log <==
172.16.210.1 - - [26/Aug/2015:13:27:36 +0000] "POST /user/do_login HTTP/1.1" 500 4322

**Comment by hennevogel** [comment]
A lot of the user routes don't use the constraints which allow dots in usernames. We need a test for users with dot in the name.

**Comment by Ana06** [comment]
In `build.opensuse.org` it is not possible to create a user with `.` in the name, but it does work using the OBS login (the one available in development).

**Comment by Ana06** [comment]
I can write a test.

**Comment by c-hoeger** [comment]
> In `build.opensuse.org` it is not possible to create a user with `.` in the name, but it does work using the OBS login (the one available in development).

Yes, it worked with 2.8 and 2.9 already.
