### ISSUE TITLE
Internal error when expanding bad link

### ISSUE THREAD

**Issue by tuminoid** [openSUSE/open-build-service#1074]
If `_link` has gone bad for some reason, trying to expand sources to see the actual link and where it points to, internal error 500 occurs. This is using OBS 2.6.3.

```
[7eb85869-87da-4d7b-a837-77c698212e47] [10226:38151.43] Started GET "/package/show/<project>/<package>?expand=0" for 131.160.66.146 at 2015-09-01 05:36:39 +0000
[7eb85869-87da-4d7b-a837-77c698212e47] [10226:38151.44] Processing by Webui::PackageController#show as HTML
[7eb85869-87da-4d7b-a837-77c698212e47] [10226:38151.44]   Parameters: {"expand"=>"0", "project"=>"<project>", "package"=>"<package>"}
[7eb85869-87da-4d7b-a837-77c698212e47] [10226:38151.44] Authenticated request to "/package/show/<project>/<package>?expand=0" from <user>
[7eb85869-87da-4d7b-a837-77c698212e47] [10226:38151.57]   Rendered webui/package/_tabs.html.erb (3.4ms)
[7eb85869-87da-4d7b-a837-77c698212e47] [10226:38151.57]   Rendered shared/_open_requests.html.erb (0.1ms)
[7eb85869-87da-4d7b-a837-77c698212e47] [10226:38151.57]   Rendered webui/package/_extra_actions.html.erb (0.1ms)
[7eb85869-87da-4d7b-a837-77c698212e47] [10226:38151.62]   Rendered webui/package/_files_view.html.erb (34.3ms)
[7eb85869-87da-4d7b-a837-77c698212e47] [10226:38151.62]   Rendered webui/package/show.html.erb within layouts/webui/webui (55.4ms)
[7eb85869-87da-4d7b-a837-77c698212e47] [10226:38151.62] Completed 500 Internal Server Error in 180ms
[7eb85869-87da-4d7b-a837-77c698212e47] [10226:38151.63] 
ActionView::Template::Error (undefined method `rjust' for nil:NilClass):
    18:                  end %>
    19:               <%= link_to_if(file[:viewable], nbsp(file[:name]), link_opts) %>
    20:             </td>
    21:             <td><span class="hidden"><%= file[:size].rjust(10, '0') %></span><%= human_readable_fsize(file[:size]) %>
    22:             </td>
    23:             <td><span class="hidden"><%= file[:mtime] %></span><%= fuzzy_time_string(Time.at(file[:mtime].to_i).to_s) %>
    24:             </td>
  app/views/webui/package/_files_view.html.erb:21:in `block in _app_views_webui_package__files_view_html_erb__3436729054256626064_35069740'
  app/views/webui/package/_files_view.html.erb:12:in `each'
  app/views/webui/package/_files_view.html.erb:12:in `_app_views_webui_package__files_view_html_erb__3436729054256626064_35069740'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/template.rb:145:in `block in render'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:161:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/template.rb:339:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/template.rb:143:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/partial_renderer.rb:278:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/renderer.rb:47:in `render_partial'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/renderer.rb:21:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/helpers/rendering_helper.rb:32:in `render'
  vendor/bundle/ruby/2.1.0/gems/haml-4.0.5/lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
  app/views/webui/package/show.html.erb:136:in `_app_views_webui_package_show_html_erb___4596607426952200183_36490780'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/template.rb:145:in `block in render'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:161:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/template.rb:339:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/template.rb:143:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:53:in `render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:17:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/renderer.rb:42:in `render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/renderer/renderer.rb:23:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/rendering.rb:99:in `_render_template'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/streaming.rb:217:in `_render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/rendering.rb:82:in `render_to_body'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/abstract_controller/rendering.rb:25:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:16:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/lib64/ruby/2.1.0/benchmark.rb:294:in `realtime'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/core_ext/benchmark.rb:12:in `ms'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:40:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:189:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:136:in `process'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/rendering.rb:30:in `process'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal.rb:196:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal.rb:232:in `block in action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:82:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:50:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/routing/mapper.rb:45:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:73:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `each'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:678:in `call'
  config/initializers/wrap_parameters.rb:41:in `call'
  vendor/bundle/ruby/2.1.0/gems/hoptoad_notifier-2.4.11/lib/hoptoad_notifier/rack.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/deflater.rb:25:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/flash.rb:254:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:82:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/lock.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/2.1.0/gems/hoptoad_notifier-2.4.11/lib/hoptoad_notifier/user_informer.rb:12:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:514:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/application.rb:144:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.33/lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  /usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.33/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.33/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.33/lib/phusion_passenger/request_handler.rb:440:in `block (3 levels) in start_threads'
```

**Comment by tuminoid** [comment]
Trying to retrieve this `_link` via `osc api` results in a failure too:

```
$ osc api -X GET /source/<project>/<package>/_link
Server returned an error: HTTP Error 400: <project>/<package>/076d41b61b69a498c41773eb70897c76-_link  No such file or directory
<project>/<package>/076d41b61b69a498c41773eb70897c76-_link: No such file or directory
```

Manually breaking a `_link` via `osc api -X PUT -T <file>` is validated and parsed correctly, but apparently whole _link being missing is not handled right.

**Comment by adrianschroeter** [comment]
this means that your source repository is broken (or you changed BSConfig.pm $nosharedtrees in an invalid mode). Sorry, but this is no code bug here.

**Comment by tuminoid** [comment]
Source repository is likely broken as we did `obs_admin --remove-old-sources 14 3` run at some point. I'll file another bug/suggestion against `obs_admin`.

I'd argue that there is a bug in backend as well, when you raise internal error 500 for a case you could catch. Fixing the package is impossible, requiring you to delete the entire package, losing all history. I think that is a valid bug.

**Comment by coolo** [comment]
There is a bug in the backend when trying to fix broken packages, see demo:

<pre>
coolo@gertrude#demopac>osc ls home:coolo demopac
_link
Link "home:coolo/demopac" cannot be expanded:
 openSUSE:Factory/gcc48: openSUSE:Factory/gcc48/a543b9622f7bf1a340a8a6682d09ad17: not in repository. Either not existing or misconfigured server setting for '$nosharedtrees' setting in BSConfig.pm
Use "osc repairlink" to fix merge conflicts.

coolo@gertrude#demopac>osc rm _link
D    _link
coolo@gertrude#demopac>osc ci -m test
Deleting    _link
Server returned an error: HTTP Error 400: Bad Request
openSUSE:Factory/gcc48/a543b9622f7bf1a340a8a6682d09ad17: not in repository. Either not existing or misconfigured server setting for '$nosharedtrees' setting in BSConfig.pm
Transmitting file data coolo@gertrude#demopac>
</pre>

The 500 you only get when the source repo is really broken though - the  remove-old-sources seems to have a bug there.
