### ISSUE TITLE
Can't submit maintenance request

### ISSUE THREAD

**Issue by weberhofer** [openSUSE/open-build-service#10846]
# Issue Description
I can't submit a maintenance request, available at https://build.opensuse.org/project/show/home:weberho:branches:OBS_Maintained:coturn

Expected Result
============
Submit as Update results in "500: Internal Server Error".

How to Reproduce
===============
1. osc mbranch coturn
2. Updated packages
3. osc commit
4. Wait until packages have been built
5. Try to submit the package

I have also tried:
3. osc mr
4. Results in "Server returned an error: HTTP Error 400: Bad Request
Maintenance incident request contains release target project openSUSE:Backports:SLE-15-SP3 with invalid project kind "standard" (should be "maintenance_release") for package coturn.openSUSE_Backports_SLE-15-SP3"

**Comment by adrianschroeter** [comment]
On Mittwoch, 10. März 2021, 08:00:10 CET Johannes Weberhofer wrote:
> # Issue Description
> I can't submit a maintenance request, available at https://build.opensuse.org/project/show/home:weberho:branches:OBS_Maintained:coturn
> 
> Expected Result
> ============
> Submit as Update results in "500: Internal Server Error".

You do not really expect an 500, right?

But did you actually saw one at all?

> How to Reproduce
> ===============
> 1. osc mbranch coturn
> 2. Updated packages
> 3. osc commit
> 4. Wait until packages have been built
> 5. Try to submit the package
> 
> I have also tried:
> 3. osc mr
> 4. Results in "Server returned an error: HTTP Error 400: Bad Request
> Maintenance incident request contains release target project openSUSE:Backports:SLE-15-SP3 with invalid project kind "standard" (should be "maintenance_release") for package coturn.openSUSE_Backports_SLE-15-SP3"

yes, SP3 is not yet in maintenance mode.

You need to create submit requests to it instead of maintenance_incident request type. 

That part looks absolute okay from OBS side.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by weberhofer** [comment]
Thanks @adrianschroeter for the quick response. 
* You are right, I did not expect 500, but that is the result after 5), which I did via the web-interfacce
* "osc mbranch coturn" created a branch for SP3 - is this a bug?
* You write, I should create submit requests, do you mean for SP3? I can do that, but how can I send the requests to Leap and SP2?

**Comment by adrianschroeter** [comment]
# You are right, I did not expect 500, but that is the result after 5), which I did via the web-interfacce

okay

# "osc mbranch coturn" created a branch for SP3 - is this a bug?

No, the package lifes there, so the branch is okay. And SP3 is not frozen yet, so it is okay that it does not point to the :Update project for maintenance update

# You write, I should create submit requests, do you mean for SP3? I can do that, but how can I send the requests to Leap and SP2?

Yes, you need to send submit requests for SP3 and maintenance_incident requests for the projects in maintenance.
The usual workflow with osc is to send always submit requests and osc automatically retries with maintenance_incident requests in case a project is in maintenance.

Not sure how the webui is currently handling this.

**Comment by Smarre** [comment]
This may or may not be related, but I were trying to implement something similar to `osc release` and `osc releaserequest` without a maintenance project using the webui. 

As far as I see, only flow the webui supports is maintenance incidents. To get a http 500, creating a project with a releasetarget, but without proper maintenance project setup. This changes `Submit package` button to `Submit as update` button. Utilizing that button causes the error.

This backtrace is for 2.10, but this seems to happen on build.opensuse.org. Can’t get a backtrace from there :)

 ```
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] [15448:2209.70]   
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] [15448:2209.70] BsRequestActionMaintenanceIncident::NoMaintenanceReleaseTarget (Maintenance incident request contains no defined release target project for package testpackage):
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] [15448:2209.70]   
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] [15448:2209.70] app/models/bs_request_action_maintenance_incident.rb:36:in `get_releaseproject'
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] app/models/bs_request_action.rb:489:in `block in create_expand_package'
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] app/models/bs_request_action.rb:443:in `create_expand_package'
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] app/models/bs_request_action.rb:828:in `expand_targets'
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] app/models/bs_request_action_maintenance_incident.rb:202:in `expand_targets'
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] app/models/bs_request.rb:1057:in `block in expand_targets'
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] app/models/bs_request.rb:1056:in `expand_targets'
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] app/models/bs_request.rb:913:in `sanitize!'
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] app/controllers/webui/projects/maintenance_incidents_controller.rb:50:in `block in create_request'
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] app/controllers/webui/projects/maintenance_incidents_controller.rb:42:in `create_request'
[b1d97404-140b-4f81-a19f-5fc85b25f6e8] config/initializers/wrap_parameters.rb:38:in `call'
```

**Comment by weberhofer** [comment]
Currently my home:weberho:branches:OBS_Maintained:coturn project is completely destroyed. Is there any way to delete it and to start from beginning? Who can help me there?

**Comment by hennevogel** [comment]
@weberhofer what would you want us to do?

**Comment by weberhofer** [comment]
@hennevogel for my specific problem: I should release a maintainance version for coturn; but I can't do anything with that project anymore. It would be great, if I could start from new - so removing would be great.

**Comment by hennevogel** [comment]
@weberhofer and why can't you do this yourself?

**Comment by weberhofer** [comment]
I can't; I alway get erros like:
```
> osc rdelete --recursive home:weberho:branches:OBS_Maintained:coturn 
Server returned an error: HTTP Error 400: Bad Request
Bs request actions Type has already been taken, Type has already been taken, and Type has already been taken
