### ISSUE TITLE
Logging in or logging out without session results in error 403

### ISSUE THREAD

**Issue by tuminoid** [openSUSE/open-build-service#1137]
If you have no session (it has expired after 24h, or you delete cookie by any means), and do login or logout (without reloading the page you're at), you get 403 forbidden.

**Comment by bgeuken** [comment]
Here is the log of the failing request:

[9aafe24c-3c3c-4c40-a467-380d9ab79059] [2479:782.25] Started POST "/user/logout" for 10.0.2.2 at 2015-09-22 13:01:38 +0200
[9aafe24c-3c3c-4c40-a467-380d9ab79059] [2479:782.25] Cannot render console from 10.0.2.2! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
[9aafe24c-3c3c-4c40-a467-380d9ab79059] [2479:782.41] Processing by Webui::UserController#logout as HTML
[9aafe24c-3c3c-4c40-a467-380d9ab79059] [2479:782.41]   Parameters: {"authenticity_token"=>"fYEhCid050sFV+TAiDfhkMEuZ40yE8FC/S9QNMB1T8mrl1ODZRxbeEujSVCNoF/cIcM9maOZc9M4v8m+gPoDdw=="}
[9aafe24c-3c3c-4c40-a467-380d9ab79059] [2479:782.41] Can't verify CSRF token authenticity
[9aafe24c-3c3c-4c40-a467-380d9ab79059] [2479:782.41] Completed 403 Forbidden in 1ms (ActiveRecord: 0.0ms | Backend: 0.0ms | XML: 0.0ms)
[9aafe24c-3c3c-4c40-a467-380d9ab79059] [2479:782.42] 
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  app/controllers/webui/webui_controller.rb:25:in `handle_unverified_request'
  actionpack (4.2.2) lib/action_controller/metal/request_forgery_protection.rb:204:in `verify_authenticity_token'
  activesupport (4.2.2) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.2) lib/active_support/callbacks.rb:164:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:164:in `block in halting'
  activesupport (4.2.2) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.2) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'

=====

The 403 is caused by this line https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/webui_controller.rb#L25

@hennevogel Any concerns removing the handle_unverified_request method? The protect_from_forgery should be enough if I am missing something

**Comment by bgeuken** [comment]
Fixed with #1159
