### ISSUE TITLE
`uninitialized constant Suse::ValidationError` errors in PackageService::FileVerifier specs

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#11609]
RSpec tests for PackageService::FileVerifier fail from time to time, with `uninitialized constant Suse::ValidationError.

Expected Result
============
The spec tests don't fail.

How to Reproduce
===============
1. Run `bin/rspec --seed 18030 spec/services/package_service/file_verifier_spec.rb` in a development environment.
1. See error:
```
  1) PackageService::FileVerifier.call invalid service file 
     Failure/Error: it { expect { subject }.to raise_error(Suse::ValidationError) }
     
     NameError:
       uninitialized constant Suse::ValidationError
       Did you mean?  Suse::ValidationError
                      ValidationHelper
     # ./spec/services/package_service/file_verifier_spec.rb:50:in `block (4 levels) in <top (required)>'

  2) PackageService::FileVerifier.call invalid constraints 
     Failure/Error: it { expect { subject }.to raise_error(Suse::ValidationError) }
     
     NameError:
       uninitialized constant Suse::ValidationError
       Did you mean?  Suse::ValidationError
                      ValidationHelper
     # ./spec/services/package_service/file_verifier_spec.rb:41:in `block (4 levels) in <top (required)>'
```

**Comment by hennevogel** [comment]
You find flickering specs on circle now.

https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests?branch=master&reporting-window=last-30-days
