### ISSUE TITLE
ValueError: unsupported format character 'B' (0x42) at index 66

### ISSUE THREAD

**Issue by marxin** [openSUSE/open-build-service#12146]
Happens for:

```
$ osc co devel:libraries:c_c++/jemalloc && cd $_ && osc build
A    devel:libraries:c_c++
A    devel:libraries:c_c++/jemalloc
A    devel:libraries:c_c++/jemalloc/jemalloc-5.2.1.tar.bz2
A    devel:libraries:c_c++/jemalloc/jemalloc.changes
A    devel:libraries:c_c++/jemalloc/jemalloc.spec
At revision 5e55983cc02eac61eacb9d592a653771.
Building jemalloc.spec for openSUSE_Factory/x86_64
Run source service: /usr/lib/obs/service/format_spec_file --outdir /tmp/devel:libraries:c_c++/jemalloc/tmp3ng60wa4.format_spec_file.service
Run source service: /usr/lib/obs/service/source_validator --outdir /tmp/devel:libraries:c_c++/jemalloc/tmpwuhqczk5.source_validator.service
Getting buildconfig from server and store to /tmp/devel:libraries:c_c++/jemalloc/.osc/_buildconfig-openSUSE_Factory-x86_64
Getting buildinfo from server and store to /tmp/devel:libraries:c_c++/jemalloc/.osc/_buildinfo-openSUSE_Factory-x86_64.xml
Updating cache of required packages
Traceback (most recent call last):
  File "/usr/bin/osc", line 45, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 6730, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python3.8/site-packages/osc/build.py", line 1074, in main
    fetcher.run(bi)
  File "/usr/lib/python3.8/site-packages/osc/fetch.py", line 210, in run
    i.makeurls(self.cachedir, urllist)
  File "/usr/lib/python3.8/site-packages/osc/build.py", line 291, in makeurls
    self.urllist.append(url % self.mp)
ValueError: unsupported format character 'B' (0x42) at index 66
```

The problematic url is `https://download.opensuse.org/repositories/devel:/libraries:/c_c%2B%2B/openSUSE_Factory//%(arch)s/%(filename)s`.

@adrianschroeter

**Comment by marcus-h** [comment]
On 2022-02-01 00:40:03 -0800, Martin Liška wrote:
> ```
> $ osc co devel:libraries:c_c++/jemalloc && cd $_ && osc build

<SNIP>

>   File "/usr/lib/python3.8/site-packages/osc/build.py", line 1074, in main
>     fetcher.run(bi)
>   File "/usr/lib/python3.8/site-packages/osc/fetch.py", line 210, in run
>     i.makeurls(self.cachedir, urllist)
>   File "/usr/lib/python3.8/site-packages/osc/build.py", line 291, in makeurls
>     self.urllist.append(url % self.mp)
> ValueError: unsupported format character 'B' (0x42) at index 66
> ```
>
> The problematic url is `https://download.opensuse.org/repositories/devel:/libraries:/c_c%2B%2B/openSUSE_Factory//%(arch)s/%(filename)s`.
>
Already fixed in osc commit d549f27ec5a4e871ae7ba6f611cb49e9a17149e4
("Escape % character in binary download URLs").
