### ISSUE TITLE
OBS: unable to upload and download files with spaces

### ISSUE THREAD

**Issue by manfredsc** [openSUSE/open-build-service#12457]
earlier this was no problem, but now I'm not able to upload, delete and download
files with spaces.
The error messages are as follows:

#> osc commit -n
```
Deleting    Mobile Atlas Creator 2.2.0.zip
Sending    Mobile Atlas Creator 2.2.2.zip
Transmitting file data ...a package internal error occured
please file a bug and attach your current package working copy and the following traceback to it:
server does not accept filelist:
<directory><entry hash="sha256:e6b315e211149038f3402b1fc07a09b31bc8b704892686e8cdfbb3865fc02b5a" md5="1fa86e97219502ae75b4c3b16ff44189" name="Mobile Atlas Creator 2.2.2.zip" /><entry md5="d0b809ae71404e46e419d19866eee0fc" name="mobac.changes" /><entry md5="9503e195387d033f880acc595ec4c134" name="mobac.desktop" /><entry md5="b1dc3b3e5f08216e0b32d31d60809cee" name="mobac.png" /><entry md5="83d23da2f536e0b61298e03e6ef97bc8" name="mobac.spec" /></directory>
missing:
<directory error="missing" name="mobac">
  <entry hash="sha256:e6b315e211149038f3402b1fc07a09b31bc8b704892686e8cdfbb3865fc02b5a" md5="1fa86e97219502ae75b4c3b16ff44189" name="Mobile Atlas Creator 2.2.2.zip" />
</directory>
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 4872, in do_commit
    self._commit(subcmd, opts, args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 4980, in _commit
    prj.commit(packages, msg=msg, files=prj_files, skip_local_service_run=skip_local_service_run, verbose=opts.verbose, can_branch=can_branch, force=opts.force)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 1032, in commit
    p.commit(msg, verbose=verbose, skip_local_service_run=skip_local_service_run, can_branch=can_branch, force=force)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 1590, in commit
    % (ET.tostring(filelist, encoding=ET_ENCODING), ET.tostring(sfilelist, encoding=ET_ENCODING)))
osc.oscerr.PackageInternalError
```

This seems to be an issue on the server side. When I try to download the
file "Mobile Atlas Creator 2.2.0.zip" via GUI, I get:

```
<status code="404">
<summary>Mobile+Atlas+Creator+2.2.0.zip: no such file</summary>
<details>404 Mobile+Atlas+Creator+2.2.0.zip: no such file</details>
</status>
```

And when I upload "Mobile Atlas Creator 2.2.2.zip" by hand via GUI,
I get a file "Mobile+Atlas+Creator+2.2.2.zip".

I tried last on 2021-05-10, then uploading files with spaces to https://build.opensuse.org/
via osc command line tool definitely worked fine.

The URL to the affected package is
  https://build.opensuse.org/package/show/home:manfred999/mobac

**Comment by manfredsc** [comment]
I confirm that https://build.opensuse.org/ is accepting spaces again, I could update my repo package.
Thanks!
