### ISSUE TITLE
obs-api attempts to talk to influxdb even if disabled

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#12461]
To reproduce:

0. obs-api-2.10.13-lp153.86.1, single server
1. Stop bs_srcserver momentarily, leave everything else (bs_repserver, apache2, etc.) up
2. Issue some osc command (e.g. `osc r`)
3. Observe how /srv/www/obs/api/log/production.log is now richer by warnings about influxdb

```
13:16 srv-build-01:../api/log # tail -f production.log &
[1] 27353
13:16 srv-build-01:../api/log # rcobssrcserver stop
13:17 srv-build-01:../api/log #

(osc r invoked on separate terminal on client device)

I, [2022-04-21T13:17:03.265037 #26563]  INFO -- : [74c95896-4d0c-4138-a5e2-0aa65b038e08] [26563:24.92] method=GET path=/build/home:jengelh/_result format=xml controller=BuildController action=result status=401 duration=4.28 view=0.66 db=0.43 params={"package"=>"gromox", "multibuild"=>"1", "locallink"=>"1", "project"=>"home:jengelh"} host=88.198.85.194 time=89666.57 backend=0 user=
I, [2022-04-21T13:17:03.601835 #26563]  INFO -- : [ca888c4c-8fb2-4cc5-8cf7-20887260224a] [26563:25.26] method=GET path=/build/home:jengelh/_result format=xml controller=BuildController action=result status=500 error='Errno::ECONNREFUSED: Failed to open TCP connection to localhost:5352 (Connection refused - connect(2) for "localhost" port 5352)' duration=318.09 view=0.00 db=2.41 params={"package"=>"gromox", "multibuild"=>"1", "locallink"=>"1", "project"=>"home:jengelh"} host=88.198.85.194 time=89666.59 backend=0 user=jengelh
F, [2022-04-21T13:17:03.610275 #26563] FATAL -- : [ca888c4c-8fb2-4cc5-8cf7-20887260224a] [26563:25.27]   
F, [2022-04-21T13:17:03.611154 #26563] FATAL -- : [ca888c4c-8fb2-4cc5-8cf7-20887260224a] [26563:25.27] Errno::ECONNREFUSED (Failed to open TCP connection to localhost:5352 (Connection refused - connect(2) for "localhost" port 5352)):
F, [2022-04-21T13:17:03.611244 #26563] FATAL -- : [ca888c4c-8fb2-4cc5-8cf7-20887260224a] [26563:25.27]   
F, [2022-04-21T13:17:03.611341 #26563] FATAL -- : [ca888c4c-8fb2-4cc5-8cf7-20887260224a] [26563:25.27] app/controllers/application_controller.rb:133:in `volley_backend_path'
[ca888c4c-8fb2-4cc5-8cf7-20887260224a] app/controllers/application_controller.rb:175:in `pass_to_backend'
[ca888c4c-8fb2-4cc5-8cf7-20887260224a] app/controllers/build_controller.rb:153:in `result'
[ca888c4c-8fb2-4cc5-8cf7-20887260224a] config/initializers/wrap_parameters.rb:38:in `call'
W, [2022-04-21T13:17:03.612249 #26563]  WARN -- InfluxDB: [26563:0.00] Failed to contact host localhost: #<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:8086 (Connection refused - connect(2) for "localhost" port 8086)> - retrying in 0.01s.
W, [2022-04-21T13:17:03.623159 #26563]  WARN -- InfluxDB: [26563:0.01] Failed to contact host localhost: #<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:8086 (Connection refused - connect(2) for "localhost" port 8086)> - retrying in 0.02s.
W, [2022-04-21T13:17:03.643662 #26563]  WARN -- InfluxDB: [26563:0.03] Failed to contact host localhost: #<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:8086 (Connection refused - connect(2) for "localhost" port 8086)> - retrying in 0.04s.
W, [2022-04-21T13:17:03.685309 #26563]  WARN -- InfluxDB: [26563:0.07] Failed to contact host localhost: #<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:8086 (Connection refused - connect(2) for "localhost" port 8086)> - retrying in 0.08s.
W, [2022-04-21T13:17:03.766181 #26563]  WARN -- InfluxDB: [26563:0.15] Failed to contact host localhost: #<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:8086 (Connection refused - connect(2) for "localhost" port 8086)> - retrying in 0.16s.
W, [2022-04-21T13:17:03.927003 #26563]  WARN -- InfluxDB: [26563:0.31] Failed to contact host localhost: #<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:8086 (Connection refused - connect(2) for "localhost" port 8086)> - retrying in 0.32s.
W, [2022-04-21T13:17:04.247844 #26563]  WARN -- InfluxDB: [26563:0.64] Failed to contact host localhost: #<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:8086 (Connection refused - connect(2) for "localhost" port 8086)> - retrying in 0.64s.
W, [2022-04-21T13:17:04.888691 #26563]  WARN -- InfluxDB: [26563:1.28] Failed to contact host localhost: #<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:8086 (Connection refused - connect(2) for "localhost" port 8086)> - retrying in 1.28s.
I, [2022-04-21T13:17:06.005545 #3439]  INFO -- : [ActiveJob] [3439:58199.05] Enqueued SendEventEmailsJob (Job ID: 6a630a2f-9604-4ce8-b929-0c70d9dba8da) to DelayedJob(mailers)
W, [2022-04-21T13:17:06.169520 #26563]  WARN -- InfluxDB: [26563:2.56] Failed to contact host localhost: #<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:8086 (Connection refused - connect(2) for "localhost" port 8086)> - retrying in 2.56s.
W, [2022-04-21T13:17:08.730439 #26563]  WARN -- InfluxDB: [26563:5.12] Failed to contact host localhost: #<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:8086 (Connection refused - connect(2) for "localhost" port 8086)> - retrying in 5.12s.
I, [2022-04-21T13:17:10.847282 #3628]  INFO -- : [3628:58204.68] 2022-04-21T13:17:10+0000: [Worker(delayed_job.1020 host:srv-build-01 pid:3628)] Job SendEventEmailsJob [6a630a2f-9604-4ce8-b929-0c70d9dba8da] from DelayedJob(mailers) with arguments: [] (id=2401450) (queue=mailers) RUNNING
I, [2022-04-21T13:17:10.847824 #3628]  INFO -- : [ActiveJob] [SendEventEmailsJob] [6a630a2f-9604-4ce8-b929-0c70d9dba8da] [3628:58204.68] Performing SendEventEmailsJob (Job ID: 6a630a2f-9604-4ce8-b929-0c70d9dba8da) from DelayedJob(mailers)
I, [2022-04-21T13:17:10.848974 #3628]  INFO -- : [ActiveJob] [SendEventEmailsJob] [6a630a2f-9604-4ce8-b929-0c70d9dba8da] [3628:58204.68] Performed SendEventEmailsJob (Job ID: 6a630a2f-9604-4ce8-b929-0c70d9dba8da) from DelayedJob(mailers) in 0.91ms
I, [2022-04-21T13:17:10.850669 #3628]  INFO -- : [3628:58204.68] 2022-04-21T13:17:10+0000: [Worker(delayed_job.1020 host:srv-build-01 pid:3628)] Job SendEventEmailsJob [6a630a2f-9604-4ce8-b929-0c70d9dba8da] from DelayedJob(mailers) with arguments: [] (id=2401450) (queue=mailers) COMPLETED after 0.0032
I, [2022-04-21T13:17:10.852175 #3628]  INFO -- : [3628:58204.69] 2022-04-21T13:17:10+0000: [Worker(delayed_job.1020 host:srv-build-01 pid:3628)] 1 jobs processed at 111.6695 j/s, 0 failed

13:17 srv-build-01:../api/log # rcobssrcserver start
13:17 srv-build-01:../api/log # W, [2022-04-21T13:17:13.851367 #26563]  WARN -- InfluxDB: [26563:10.24] Failed to contact host localhost: #<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:8086 (Connection refused - connect(2) for "localhost" port 8086)> - retrying in 10.24s.
```

The section in `/srv/www/obs/api/config/options.yml` about influx was left untouched and currently reads like so:

```
  # For sending application performance metrics to a influx time series database
  # influxdb_database: rails
  # influxdb_username: rails
  # influxdb_password: 123456
  # influxdb_hosts:
  #  - domain.tld
  # influxdb_port: 8086
  # influxdb_ssl: true
  # influxdb_retry: 10
  # influxdb_time_precision: ms

  # Enable (true) / Disable (false) Ruby on Rails profiling top-bar in the web ui
  peek_enabled: false
```

**Comment by jengelh** [comment]
No rpmold/rpmnew files. I do not think that this is a regression that would be visible in the diff 2.10.12..2.10.13.

**Comment by hennevogel** [comment]
In `/srv/www/obs/api`, what's the output of 

`bundle exec rails runner -e production "puts Rails.env"` 

and 

`bundle exec rails runner -e production "puts CONFIG['influxdb_hosts']"`

**Comment by hennevogel** [comment]
and 

`bundle exec rails runner -e production "pp InfluxDB::Rails.configuration"`

**Comment by jengelh** [comment]
```
# bundle exec rails runner -e production "puts Rails.env"
Traceback (most recent call last):
        2: from /usr/bin/bundle:23:in `<main>'
        1: from /usr/lib64/ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
/usr/lib64/ruby/2.5.0/rubygems.rb:284:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /srv/www/obs/api/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
# bundle.ruby2.7 exec rails runner -e production "puts Rails.env"
production
# bundle.ruby2.7 exec rails runner -e production "puts CONFIG['influxdb_hosts']" | hexdump -C
00000000  0a                                                |.|
00000001
# bundle.ruby2.7 exec rails runner -e production "pp InfluxDB::Rails.configuration"
#<InfluxDB::Rails::Configuration:0x0000558b9e6326b0
 @aggregated_exception_classes=[],
 @application_name="OBSApi",
 @application_root=#<Pathname:/srv/www/obs/api>,
 @async=true,
 @backtrace_filters=
  [#<Proc:0x0000558b9cfc5c38 /usr/lib64/obs-api/ruby/2.7.0/gems/experimental-influxdb-rails-1.0.0.beta5/lib/influxdb/rails/configuration.rb:100 (lambda)>,
   #<Proc:0x0000558b9cfc5c10 /usr/lib64/obs-api/ruby/2.7.0/gems/experimental-influxdb-rails-1.0.0.beta5/lib/influxdb/rails/configuration.rb:101 (lambda)>,
   #<Proc:0x0000558b9cfc5be8 /usr/lib64/obs-api/ruby/2.7.0/gems/experimental-influxdb-rails-1.0.0.beta5/lib/influxdb/rails/configuration.rb:106 (lambda)>],
 @debug=false,
 @environment="production",
 @environment_variable_filters=
  [/password/i, /key/i, /secret/i, /ps1/i, /rvm_.*_clr/i, /color/i],
 @framework="Rails",
 @framework_version="5.2.6.2",
 @ignored_environments=["test", "cucumber", "selenium"],
 @ignored_exception_messages=[],
 @ignored_exceptions=
  ["ActiveRecord::RecordNotFound", "ActionController::RoutingError"],
 @ignored_reports=[],
 @ignored_user_agents=["GoogleBot"],
 @influxdb_database=nil,
 @influxdb_hosts=["localhost"],
 @influxdb_password="root",
 @influxdb_port=8086,
 @influxdb_username="root",
 @instrumentation_enabled=false,
 @logger=
  #<ActiveSupport::Logger:0x0000558b9e68ebe0
   @default_formatter=
    #<Logger::Formatter:0x0000558b9e68eb90 @datetime_format=nil>,
   @formatter=
    #<Logger::Formatter:0x0000558b9e6f6420
     @datetime_format=nil,
     @thread_key="activesupport_tagged_logging_tags:27580">,
   @level=1,
   @local_levels=
    #<Concurrent::Map:0x0000558b9e68e9b0 entries=0 default_proc=nil>,
   @logdev=
    #<Logger::LogDevice:0x0000558b9e68eb40
     @binmode=false,
     @dev=#<File:/srv/www/obs/api/log/production.log>,
     @filename="/srv/www/obs/api/log/production.log",
     @mon_data=#<Monitor:0x0000558b9e68eaf0>,
     @mon_data_owner_object_id=17380,
     @shift_age=0,
     @shift_period_suffix="%Y%m%d",
     @shift_size=1048576>,
   @progname=nil>,
 @max_delay=30,
 @open_timeout=5,
 @rails_app_name=nil,
 @read_timeout=300,
 @rescue_global_exceptions=false,
 @retry=nil,
 @series_name_for_controller_runtimes="rails.controller",
 @series_name_for_db_runtimes="rails.db",
 @series_name_for_exceptions="rails.exceptions",
 @series_name_for_instrumentation="instrumentation",
 @series_name_for_render_collection="rails.render_collection",
 @series_name_for_render_partial="rails.render_partial",
 @series_name_for_render_template="rails.render_template",
 @series_name_for_sql=nil,
 @series_name_for_view_runtimes="rails.view",
 @tags_middleware=
  #<Proc:0x0000558b9cfc63b8 /usr/lib64/obs-api/ruby/2.7.0/gems/experimental-influxdb-rails-1.0.0.beta5/lib/influxdb/rails/configuration.rb:78 (lambda)>,
 @time_precision="s",
 @use_ssl=false>
```
