### ISSUE TITLE
Feed crashes for build failed notification

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#14362]
```
I, [2023-05-22T00:37:39.239789 #11005]  INFO -- : [419ecaf0-b162-4d3b-95e8-b545f02eb109] [11005:380.81] method=HEAD path=/user/feed/[[REDACTED]] format=rss controller=Webui::FeedsController action=notifications status=500 duration=67.42 view=0.00 db=15.11 params={"token"=>"[FILTERED]"} host=35.170.75.19 time=2139373813.61 backend=0 user=_nobody_
F, [2023-05-22T00:37:39.260990 #11005] FATAL -- : [419ecaf0-b162-4d3b-95e8-b545f02eb109] [11005:380.83]   
[419ecaf0-b162-4d3b-95e8-b545f02eb109] ActionView::Template::Error (Missing template notifications/build_fail with {:locale=>[:en], :formats=>[:text], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :haml]}.
[419ecaf0-b162-4d3b-95e8-b545f02eb109]     11:       xml.item do
[419ecaf0-b162-4d3b-95e8-b545f02eb109]     12:         if notification.notifiable && notification.event_type != 'Event::ReviewWanted'
[419ecaf0-b162-4d3b-95e8-b545f02eb109]     13:           xml.title notification.title
[419ecaf0-b162-4d3b-95e8-b545f02eb109]     14:           xml.description render(
[419ecaf0-b162-4d3b-95e8-b545f02eb109]     15:             template: "notifications/#{notification.template_name}",
[419ecaf0-b162-4d3b-95e8-b545f02eb109]     16:             layout: false,
[419ecaf0-b162-4d3b-95e8-b545f02eb109]     17:             formats: :text,
[419ecaf0-b162-4d3b-95e8-b545f02eb109]   
[419ecaf0-b162-4d3b-95e8-b545f02eb109] app/views/webui/feeds/notifications.rss.builder:14
[419ecaf0-b162-4d3b-95e8-b545f02eb109] app/views/webui/feeds/notifications.rss.builder:11
[419ecaf0-b162-4d3b-95e8-b545f02eb109] app/views/webui/feeds/notifications.rss.builder:10
[419ecaf0-b162-4d3b-95e8-b545f02eb109] app/views/webui/feeds/notifications.rss.builder:2
[419ecaf0-b162-4d3b-95e8-b545f02eb109] app/views/webui/feeds/notifications.rss.builder:1
[419ecaf0-b162-4d3b-95e8-b545f02eb109] app/views/webui/feeds/notifications.rss.builder:1:in `new'
[419ecaf0-b162-4d3b-95e8-b545f02eb109] app/views/webui/feeds/notifications.rss.builder:1
[419ecaf0-b162-4d3b-95e8-b545f02eb109] config/initializers/prefer_xml_over_html.rb:15:in `call'
```

**Comment by hennevogel** [comment]
Doesn't reach errbit as we filter this exception

**Comment by hennevogel** [comment]
Seems to be a problem 

```
api:~/api # grep 5eeedd18-c084-44fd-9fbb-54d45116a8a0 log/production.log
I, [2023-05-22T16:41:17.064199 #23655]  INFO -- : [5eeedd18-c084-44fd-9fbb-54d45116a8a0] [23655:1444.36] method=GET path=/user/feed/[[REDACTED]] format=rss controller=Webui::FeedsController action=notifications status=500 duration=82.68 view=0.00 db=22.73 params={"token"=>"[FILTERED]"} host=98.35.20.124 time=2197191622.75 backend=0 user=_nobody_
F, [2023-05-22T16:41:17.079011 #23655] FATAL -- : [5eeedd18-c084-44fd-9fbb-54d45116a8a0] [23655:1444.38]   
[5eeedd18-c084-44fd-9fbb-54d45116a8a0] ActionView::Template::Error (Missing template notifications/relationship_create with {:locale=>[:en], :formats=>[:text], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :haml]}.
[5eeedd18-c084-44fd-9fbb-54d45116a8a0]     11:       xml.item do
[5eeedd18-c084-44fd-9fbb-54d45116a8a0]     12:         if notification.notifiable && notification.event_type != 'Event::ReviewWanted'
[5eeedd18-c084-44fd-9fbb-54d45116a8a0]     13:           xml.title notification.title
[5eeedd18-c084-44fd-9fbb-54d45116a8a0]     14:           xml.description render(
[5eeedd18-c084-44fd-9fbb-54d45116a8a0]     15:             template: "notifications/#{notification.template_name}",
[5eeedd18-c084-44fd-9fbb-54d45116a8a0]     16:             layout: false,
[5eeedd18-c084-44fd-9fbb-54d45116a8a0]     17:             formats: :text,
[5eeedd18-c084-44fd-9fbb-54d45116a8a0]   
[5eeedd18-c084-44fd-9fbb-54d45116a8a0] app/views/webui/feeds/notifications.rss.builder:14
[5eeedd18-c084-44fd-9fbb-54d45116a8a0] app/views/webui/feeds/notifications.rss.builder:11
[5eeedd18-c084-44fd-9fbb-54d45116a8a0] app/views/webui/feeds/notifications.rss.builder:10
[5eeedd18-c084-44fd-9fbb-54d45116a8a0] app/views/webui/feeds/notifications.rss.builder:2
[5eeedd18-c084-44fd-9fbb-54d45116a8a0] app/views/webui/feeds/notifications.rss.builder:1
[5eeedd18-c084-44fd-9fbb-54d45116a8a0] app/views/webui/feeds/notifications.rss.builder:1:in `new'
[5eeedd18-c084-44fd-9fbb-54d45116a8a0] app/views/webui/feeds/notifications.rss.builder:1
[5eeedd18-c084-44fd-9fbb-54d45116a8a0] config/initializers/prefer_xml_over_html.rb:15:in `call'
```
