### ISSUE TITLE
Spider tests failing on 15.5/Factory

### ISSUE THREAD

**Issue by M0ses** [openSUSE/open-build-service#14410]
As you can see in the current logs 

https://build.opensuse.org/package/live_build_log/OBS:Server:Unstable/obs-server/15.5/x86_64
https://build.opensuse.org/package/live_build_log/OBS:Server:Unstable/obs-server/openSUSE_Factory/x86_64

the spider tests are failing with the following errors:

```
[ 3659s] 
[ 3659s] Webui::SpiderTest
[ 3673s] Starting test backend...To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
[ 3712s] Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
[ 3712s]   test_spider_anonymously                                        ERROR (53.73s)
[ 3712s] Minitest::UnexpectedError:         RuntimeError: Backend died
[ 3712s]             app/lib/backend/test.rb:17:in `block in start'
[ 3712s]             app/lib/backend/test.rb:15:in `loop'
[ 3712s]             app/lib/backend/test.rb:15:in `start'
[ 3712s]             test/test_helper.rb:207:in `block in <class:IntegrationTest>'
[ 3712s]             test/test_helper.rb:99:in `block in __run'
[ 3712s]             test/test_helper.rb:99:in `map'
[ 3712s]             test/test_helper.rb:99:in `__run'
[ 3712s] 
[ 3728s] (65 of 66) Crawling http://www.example.com/
```

```
[ 3886s] (371 of 625) Crawling http://www.example.com/package/revisions/HiddenProject/target
[ 5886s] Found flash alert The request timed out. Please try again. on http://www.example.com/package/revisions/HiddenProject/target, crawling path
[ 5886s]  http://www.example.com/package/show/HiddenProject/target ('Revisions')
[ 5886s]    http://www.example.com/package/sitemap/main ('sitemap')
[ 5886s]   test_spider_as_admin                                           ERROR (2174.28s)
[ 5886s] Minitest::UnexpectedError:         RuntimeError: Found flash alert The request timed out. Please try again.
[ 5886s]             test/functional/webui/spider_test.rb:88:in `raiseit'
[ 5886s]             test/functional/webui/spider_test.rb:126:in `crawl'
[ 5886s]             test/functional/webui/spider_test.rb:175:in `test_spider_as_admin'
[ 5886s]             test/test_helper.rb:99:in `block in __run'
[ 5886s]             test/test_helper.rb:99:in `map'
[ 5886s]             test/test_helper.rb:99:in `__run'
[ 5886s] 
[ 5886s] 
[ 5886s] Finished in 2228.03570s
[ 5886s] 2 tests, 0 assertions, 0 failures, 2 errors, 0 skips
```

**Comment by hennevogel** [comment]
Judging from the job history this is more a problem of resources

https://build.opensuse.org/packages/obs-server/job_history/OBS:Server:Unstable/15.5/x86_64

**Comment by bmwiedemann** [comment]
It looks like jobs that fail run over 1h and good jobs can finish in 30m - so should we raise constraints in https://build.opensuse.org/package/view_file/OBS:Server:Unstable/obs-server/_constraints and to what?

**Comment by hennevogel** [comment]
That would be the option you have yes. Please note that you would make the set of workers, that can build the package, smaller which would can mean higher latency also for distributions where we do *not* run the test suite. Like for the packages we deploy to production...

**Comment by M0ses** [comment]
As I mentioned in the inital report - this is reproducible on 15.5 and Factory. We would like to upgrade the appliance to 15.5 and also production is or will be running on 15.5 - the rest is only for backward compability.

IMHO we should double the existing constraints - for example in kanku we increased the ram from 4 to 6 GB RAM some time ago because the appliance tests were failing constantly.

**Comment by hennevogel** [comment]
It's not reproducible as the last 2 build for 15.5 succeeded. See the job history I linked. And if we upgrade production to 15.5 then we won't run the test suite during the build anymore during the 15.5 build...

**Comment by M0ses** [comment]
Quoting @bmwiedemann

> Last succeeded job had 8 cores and 8 GB RAM and the other had 3 cores and 4 GB RAM.

AFAICS also sheep88 provides more powerful workers then e.g. cloud103.
So I also guess that it is an constraints problem, as you already stated:

> Judging from the job history this is more a problem of resources
