### ISSUE TITLE
bin/rails db:setup writeconfiguration data:schema:load fails on a database constraint

### ISSUE THREAD

**Issue by dmach** [openSUSE/open-build-service#14517]
# Issue Description

There's a regularly built container image for osc testing in GitHub Actions.
It started to failing on a database constraint.

It's a clean install
  - `opensuse/leap:15.4` container
  - `http://download.opensuse.org/repositories/OBS:/Server:/Unstable/15.4/OBS:Server:Unstable.repo` repo

This is what happens:
```
$ RAILS_ENV=production SAFETY_ASSURED=1 bin/rails db:setup writeconfiguration data:schema:load
Name "BSConfig::localarch" used only once: possible typo at /usr/lib/obs/server/bs_srcserver line 1905.
WARNING: Nokogiri was built against libxml version 2.9.12, but has dynamically loaded 2.9.14
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
Created database 'api_production'
Seeding architectures table...
Seeding roles table...
Seeding users table...
Seeding roles_users table...
Seeding static_permissions table...
Seeding static permissions for admin role in roles_static_permissions table...
Seeding static permissions for maintainer role in roles_static_permissions table...
Seeding static permissions for reader role in roles_static_permissions table...
Seeding static permissions for downloader role in roles_static_permissions table...
Seeding attrib_namespaces table...
Seeding attrib_types table...
Seeding issue trackers ...
rails aborted!
ActiveRecord::InvalidForeignKey: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails
/srv/www/obs/api/db/schema.rb:14:in `block in <top (required)>'
/srv/www/obs/api/db/schema.rb:13:in `<top (required)>'

Caused by:
Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails
/srv/www/obs/api/db/schema.rb:14:in `block in <top (required)>'
/srv/www/obs/api/db/schema.rb:13:in `<top (required)>'
Tasks: TOP => data:schema:load
(See full trace by running task with --trace)
```

**Comment by hennevogel** [comment]
Not sure what you are trying to achieve but `db:setup` already includes `data:schema:load`
