### ISSUE TITLE
data:schema:load  does not work anymore 

### ISSUE THREAD

**Issue by M0ses** [openSUSE/open-build-service#14518]
# Issue Description

initial population of database via `obsapisetup` fails

Expected Result
============

exiting `obsapisetup` w/o any errors

How to Reproduce
===============

1.  Create a new VM using the OSU Appliance
2. Boot
3. Check the logs

Further Information
===============

* Problem seems to got introduced on 06/12/2023 between 14:00 and 16:00 (TZ Berlin)
  * Last successful run in kanku: 12.6.2023, 14:20:26 
  * First failing run in kanku: 12.6.2023, 15:33:35 
* output of obsapisetup

```
Jun 19 09:50:30 obs-server-unstable systemd[1]: Starting OBS API Setup...
Jun 19 09:50:30 obs-server-unstable setup-appliance.sh[2159]: Starting setup-appliance.sh at Mon Jun 19 09:50:30 UTC 2023
Jun 19 09:50:30 obs-server-unstable setup-appliance.sh[2159]: Waiting for FQHOSTNAME (29)
Jun 19 09:50:31 obs-server-unstable setup-appliance.sh[2159]: Appliance hostname changed from NOTHING to obs-server-unstable !
Jun 19 09:50:31 obs-server-unstable setup-appliance.sh[2159]: Adapting present worker jobs
Jun 19 09:50:31 obs-server-unstable setup-appliance.sh[2159]: Adjust configuration for this hostname
Jun 19 09:50:43 obs-server-unstable setup-appliance.sh[2159]: Initialize MySQL databases (first time only)
Jun 19 09:50:43 obs-server-unstable setup-appliance.sh[2159]:  - reconfiguring datadir in /etc/my.cnf
Jun 19 09:50:43 obs-server-unstable setup-appliance.sh[2159]: /etc/my.cnf.d/obs-server.cnf
Jun 19 09:50:43 obs-server-unstable setup-appliance.sh[2159]:  - installing to new datadir
Jun 19 09:50:43 obs-server-unstable setup-appliance.sh[2245]: mysql.user table already exists!
Jun 19 09:50:43 obs-server-unstable setup-appliance.sh[2245]: Run mysql_upgrade, not mysql_install_db
Jun 19 09:50:43 obs-server-unstable setup-appliance.sh[2159]:  - changing ownership for new datadir
Jun 19 09:50:43 obs-server-unstable setup-appliance.sh[2159]:  - restarting mysql
Jun 19 09:50:44 obs-server-unstable setup-appliance.sh[2159]:  - setting new password for user root in mysql
Jun 19 09:50:44 obs-server-unstable setup-appliance.sh[2159]: Initialize OBS api database (first time only)
Jun 19 09:50:44 obs-server-unstable setup-appliance.sh[2159]: Setting ownership of '/srv/obs' obsrun
Jun 19 09:50:44 obs-server-unstable setup-appliance.sh[2159]: Setting up rails environment
Jun 19 09:50:44 obs-server-unstable setup-appliance.sh[2159]: - Doing 'rails db:setup'
Jun 19 09:52:41 obs-server-unstable setup-appliance.sh[2159]: - Doing 'rails writeconfiguration'
Jun 19 09:52:47 obs-server-unstable setup-appliance.sh[2159]: - Doing 'rails data:schema:load'
Jun 19 09:52:53 obs-server-unstable setup-appliance.sh[2953]: Command data:schema:load FAILED
Jun 19 09:52:53 obs-server-unstable systemd[1]: obsapisetup.service: Main process exited, code=exited, status=1/FAILURE
Jun 19 09:52:53 obs-server-unstable systemd[1]: obsapisetup.service: Failed with result 'exit-code'.
Jun 19 09:52:53 obs-server-unstable systemd[1]: Failed to start OBS API Setup.
```

* logfile /srv/www/obs/api/log/db_migrate.log

```
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
Created database 'api_production'
Seeding architectures table...
Seeding roles table...
Seeding users table...
Seeding roles_users table...
Seeding static_permissions table...
Seeding static permissions for admin role in roles_static_permissions table...
Seeding static permissions for maintainer role in roles_static_permissions table...
Seeding static permissions for reader role in roles_static_permissions table...
Seeding static permissions for downloader role in roles_static_permissions table...
Seeding attrib_namespaces table...
Seeding attrib_types table...
Seeding issue trackers ...
WARNING: Nokogiri was built against libxml version 2.9.12, but has dynamically loaded 2.9.14
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
WARNING: Nokogiri was built against libxml version 2.9.12, but has dynamically loaded 2.9.14
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
rails aborted!
ActiveRecord::InvalidForeignKey: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails
/srv/www/obs/api/db/schema.rb:14:in `block in <top (required)>'
/srv/www/obs/api/db/schema.rb:13:in `<top (required)>'

Caused by:
Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails
/srv/www/obs/api/db/schema.rb:14:in `block in <top (required)>'
/srv/www/obs/api/db/schema.rb:13:in `<top (required)>'
Tasks: TOP => data:schema:load
(See full trace by running task with --trace)
```

* running rails with `--trace`

```
"cd /srv/www/obs/api/;RAILS_ENV=production bin/rails --trace data:schema:load"
Warning: Permanently added '[10.136.17.1]:49012' (ED25519) to the list of known hosts.
WARNING: Nokogiri was built against libxml version 2.9.12, but has dynamically loaded 2.9.14
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
** Invoke data:schema:load (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute data:schema:load
rails aborted!
ActiveRecord::InvalidForeignKey: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails
/usr/lib64/obs-api/ruby/3.1.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `_query'
/usr/lib64/obs-api/ruby/3.1.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `block in query'
/usr/lib64/obs-api/ruby/3.1.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `handle_interrupt'
/usr/lib64/obs-api/ruby/3.1.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `query'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:632:in `block (2 levels) in raw_execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:631:in `block in raw_execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:630:in `raw_execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:96:in `raw_execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:47:in `execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:328:in `drop_table'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:320:in `create_table'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/mysql/schema_statements.rb:81:in `create_table'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:932:in `block in method_missing'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:900:in `block in say_with_time'
/usr/lib64/ruby/3.1.0/benchmark.rb:296:in `measure'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:900:in `say_with_time'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:921:in `method_missing'
/usr/lib64/obs-api/ruby/3.1.0/gems/strong_migrations-1.4.4/lib/strong_migrations/migration.rb:13:in `method_missing'
/srv/www/obs/api/db/schema.rb:14:in `block in <top (required)>'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/schema.rb:55:in `instance_eval'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/schema.rb:55:in `define'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/schema.rb:50:in `define'
/srv/www/obs/api/db/schema.rb:13:in `<top (required)>'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:377:in `load'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:377:in `load_schema'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:482:in `block in load_schema_current'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:557:in `block (2 levels) in each_current_configuration'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:554:in `each'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:554:in `block in each_current_configuration'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:553:in `each'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:553:in `each_current_configuration'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:481:in `load_schema_current'
/usr/lib64/obs-api/ruby/3.1.0/gems/data_migrate-10.0.2/tasks/databases.rake:316:in `block (3 levels) in <top (required)>'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/airbrake-9.4.3/lib/airbrake/rake.rb:17:in `execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/command.rb:51:in `invoke'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails
/usr/lib64/obs-api/ruby/3.1.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `_query'
/usr/lib64/obs-api/ruby/3.1.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `block in query'
/usr/lib64/obs-api/ruby/3.1.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `handle_interrupt'
/usr/lib64/obs-api/ruby/3.1.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `query'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:632:in `block (2 levels) in raw_execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:631:in `block in raw_execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
/usr/lib64/obs-api/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:630:in `raw_execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:96:in `raw_execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:47:in `execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:328:in `drop_table'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:320:in `create_table'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/mysql/schema_statements.rb:81:in `create_table'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:932:in `block in method_missing'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:900:in `block in say_with_time'
/usr/lib64/ruby/3.1.0/benchmark.rb:296:in `measure'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:900:in `say_with_time'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:921:in `method_missing'
/usr/lib64/obs-api/ruby/3.1.0/gems/strong_migrations-1.4.4/lib/strong_migrations/migration.rb:13:in `method_missing'
/srv/www/obs/api/db/schema.rb:14:in `block in <top (required)>'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/schema.rb:55:in `instance_eval'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/schema.rb:55:in `define'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/schema.rb:50:in `define'
/srv/www/obs/api/db/schema.rb:13:in `<top (required)>'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:377:in `load'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:377:in `load_schema'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:482:in `block in load_schema_current'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:557:in `block (2 levels) in each_current_configuration'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:554:in `each'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:554:in `block in each_current_configuration'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:553:in `each'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:553:in `each_current_configuration'
/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:481:in `load_schema_current'
/usr/lib64/obs-api/ruby/3.1.0/gems/data_migrate-10.0.2/tasks/databases.rake:316:in `block (3 levels) in <top (required)>'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/airbrake-9.4.3/lib/airbrake/rake.rb:17:in `execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/command.rb:51:in `invoke'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => data:schema:load

```

**Comment by hennevogel** [comment]
Are you by any chance doing the same as @dmach in #14517 did? :)

**Comment by M0ses** [comment]
"It wasn`t me".  ;-)
`obsapisetup` is doing it here: https://github.com/openSUSE/open-build-service/blob/master/dist/functions.setup-appliance.sh#L277

I will provide a patch to fix this.
Anyway, it would be nice to know _why_ `data:schema:load` was required in the past but is not needed any longer.
Did something change in rails or in open-build-service?

**Comment by hennevogel** [comment]
It was never needed. My guess is that it was more forgiving in the past if it found a schema already.

**Comment by M0ses** [comment]
For the record: It was introduced due to this issue:

https://github.com/openSUSE/open-build-service/issues/9779
