### ISSUE TITLE
[ci] Timeout issues in openQA.o.o during build result refresh on OBS Unstable appliance

### ISSUE THREAD

**Issue by shyukri** [openSUSE/open-build-service#1668]
https://openqa.opensuse.org/tests/135852 -> Logs & Assets -> rspec_webui_tests-srv_www_obs_api_logs.tar.gz

https://github.com/shyukri/open-build-service/blob/rspec_appliance_tests_fix/dist/t/spec/features/login_spec.rb#L77 , 
`Capybara.default_max_wait_time = 6`

I can't reproduce this on my local openQA instance using 2GB RAM as in o.o.o
@coolo , @hennevogel any ideas?

Part of production.log
```
[52df755a-3682-43c1-aa5c-2b9b502582bc] [8516:169.80] Started GET "/project/show/home:Admin/" for 10.0.2.15 at 2016-03-31 14:12:57 +0000
[52df755a-3682-43c1-aa5c-2b9b502582bc] [8516:169.85] Processing by Webui::ProjectController#show as HTML
[52df755a-3682-43c1-aa5c-2b9b502582bc] [8516:169.85]   Parameters: {"project"=>"home:Admin"}
[52df755a-3682-43c1-aa5c-2b9b502582bc] [8516:169.95] --> caught timeout, closing HTTP
[52df755a-3682-43c1-aa5c-2b9b502582bc] [8516:169.96] Completed 408 Request Timeout in 106ms (ActiveRecord: 64.7ms | Backend: 0.0ms | XML: 0.0ms)
[52df755a-3682-43c1-aa5c-2b9b502582bc] [8516:169.97] 
Timeout::Error (Timeout::Error):
  lib/activexml/transport.rb:365:in `rescue in http_do'
  lib/activexml/transport.rb:389:in `http_do'
  lib/activexml/transport.rb:229:in `direct_http'
  app/models/project.rb:176:in `number_of_build_problems'
  app/controllers/webui/project_controller.rb:908:in `load_project_info'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5.2) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5.2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5.2) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5.2) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:815:in `call'
  config/initializers/wrap_parameters.rb:38:in `call'
  hoptoad_notifier (2.4.11) lib/hoptoad_notifier/rack.rb:27:in `call'
  rack (1.6.4) lib/rack/deflater.rb:35:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.2) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  hoptoad_notifier (2.4.11) lib/hoptoad_notifier/user_informer.rb:12:in `call'
  railties (4.2.5.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.2) lib/rails/application.rb:165:in `call'
  railties (4.2.5.2) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.5.2) lib/rails/railtie.rb:194:in `method_missing'
  passenger (5.0.22) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  passenger (5.0.22) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  passenger (5.0.22) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  passenger (5.0.22) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  passenger (5.0.22) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'


[8637:179.98] --> caught timeout, closing HTTP
```

**Comment by hennevogel** [comment]
Backend died/never started?

**Comment by hennevogel** [comment]
And @shyukri?

**Comment by shyukri** [comment]
@hennevogel Tests prior to this one shows the services as started: https://openqa.opensuse.org/tests/135852/file/trigger_obs_appliance_tests-appliance_tests.txt

**Comment by shyukri** [comment]
Looks like fixed in https://github.com/openSUSE/open-build-service/compare/master...shyukri:rspec_appliance_tests_fix
