### ISSUE TITLE
Upgrading to OBS 2.7 beta breaks projects

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#1763]
After upgrading from either OBS 2.6 or OBS 2.6.51 builds to OBS 2.6.90 builds, attempts to access projects result in HTTP 500 errors. 

The following output came from `/srv/www/obs/api/log/production.log` when clicking on one of the projects:

```
52117b96-3595-4808-bc29-80ff1d9d6f93] [1295:345.71] Started GET "/project/show/home:ngompa" for 10.0.130.13 at 2016-04-29 18:09:46 +0000
[52117b96-3595-4808-bc29-80ff1d9d6f93] [1295:345.71] Processing by Webui::ProjectController#show as HTML
[52117b96-3595-4808-bc29-80ff1d9d6f93] [1295:345.71]   Parameters: {"project"=>"home:ngompa"}
[52117b96-3595-4808-bc29-80ff1d9d6f93] [1295:345.74] Completed 500 Internal Server Error in 21ms (ActiveRecord: 1.3ms | Backend: 0.0ms | XML: 0.0ms)
[52117b96-3595-4808-bc29-80ff1d9d6f93] [1295:345.74] 
NoMethodError (undefined method `kind' for #<Project:0x00000005fa9650>):
  activemodel (4.2.5.2) lib/active_model/attribute_methods.rb:433:in `method_missing'
  app/models/project.rb:452:in `is_maintenance?'
  app/controllers/webui/project_controller.rb:959:in `find_maintenance_infos'
  app/controllers/webui/project_controller.rb:915:in `load_project_info'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5.2) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5.2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5.2) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5.2) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:815:in `call'
  config/initializers/wrap_parameters.rb:38:in `call'
  hoptoad_notifier (2.4.11) lib/hoptoad_notifier/rack.rb:27:in `call'
  rack (1.6.4) lib/rack/deflater.rb:35:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.2) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  hoptoad_notifier (2.4.11) lib/hoptoad_notifier/user_informer.rb:12:in `call'
  railties (4.2.5.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.2) lib/rails/application.rb:165:in `call'
  railties (4.2.5.2) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.5.2) lib/rails/railtie.rb:194:in `method_missing'
  passenger (5.0.22) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  passenger (5.0.22) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  passenger (5.0.22) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  passenger (5.0.22) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  passenger (5.0.22) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

I'm unsure of what's causing the problem or how to fix it. This issue has cropped up on every appliance upgrade I've done so far.

**Comment by bgeuken** [comment]
Might be a migration missing

**Comment by bgeuken** [comment]
Did you follow https://github.com/openSUSE/open-build-service/blob/master/dist/README.UPDATERS ? Point 5 explains how to run the migration

**Comment by Conan-Kudo** [comment]
@bgeuken I followed that exactly, and I still have broken appliances.

**Comment by adrianschroeter** [comment]
@Conan-Kudo please tell which mirgrations are listed in your production database. Check the schema_migrations table.

20150716124906_add_type_to_project   

migration seems to be skipped.

**Comment by Conan-Kudo** [comment]
@adrianschroeter After blowing it away and starting over with the 2.7 RC, this seems to work now.
