### ISSUE TITLE
Make PublicController#project_file (aka main page) failsafe

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#1955]
Yesterday evening the main page and monitor page stopped being accessible, responding with a 408. The rest of OBS, including the API, were fine though.

Looking at the logs it turned out that PublicController#project_file was querying the worker status, which did not respond in time and caused the 408 Request Timeout.

It would be good if we catch the timeout exception and render the page properly. Maybe show a warning that we face some issues right now and OBS availability might be limited.
In addition we should send a mail to the admins of that OBS instance.

======

[4d818639-5280-4666-b85b-be1d49b5bcf4] [29410:912.46] Processing by PublicController#project_file as XML
[4d818639-5280-4666-b85b-be1d49b5bcf4] [29410:912.46]   Parameters: {"project"=>"openSUSE:Factory"}
[4d818639-5280-4666-b85b-be1d49b5bcf4] [29410:912.47] Completed 200 OK in 8ms (ActiveRecord: 2.8ms | Backend: 0.0ms | XML: 0.0ms)
[e7f5b1c1-cdcf-43e0-8d2a-ab949e99f8e4] [344:673.96] --> caught timeout, closing HTTP
[e7f5b1c1-cdcf-43e0-8d2a-ab949e99f8e4] [344:673.96] Completed 408 Request Timeout in 120135ms (ActiveRecord: 4.8ms | Backend: 0.0ms | XML: 0.0ms)
[e7f5b1c1-cdcf-43e0-8d2a-ab949e99f8e4] [344:673.97] 
Timeout::Error (Timeout::Error):
  lib/activexml/transport.rb:365:in `rescue in http_do'
  lib/activexml/transport.rb:389:in `http_do'
  lib/activexml/transport.rb:229:in `direct_http'
  app/models/worker_status.rb:4:in `hidden'
  app/controllers/webui/main_controller.rb:28:in `block in index'
  dalli (2.7.4) lib/active_support/cache/dalli_store.rb:105:in `block in fetch'
  dalli (2.7.4) lib/active_support/cache/dalli_store.rb:359:in `block in instrument'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:166:in `instrument'
  dalli (2.7.4) lib/active_support/cache/dalli_store.rb:359:in `instrument'
  dalli (2.7.4) lib/active_support/cache/dalli_store.rb:104:in `fetch'
  app/controllers/webui/main_controller.rb:27:in `index'

**Comment by hennevogel** [comment]
So we need a public/408.html that tells people what's up and what they can do (notify us)

**Comment by hennevogel** [comment]
There is a [public/408.html](https://github.com/openSUSE/open-build-service/blob/master/src/api/public/408.html) page. This was rendered @bgeuken?

**Comment by bgeuken** [comment]
It got rendered after several minutes of waiting. And it included a link to the monitor page for users to check the OBS state. Though the monitor page was timing out for the same reason.

The thing is OBS shouldn't block everything because of a subsystem not working and it shouldn't require users to notify us.

So I think that data should be fetched asynchronously. If that fails, an error message should appear. In addition we should also send a mail to the admins of that OBS instance.

That way people can still use OBS even if the services or hermes or ??? doesn't work.
