### ISSUE TITLE
osc results --csv results in python stack trace

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#2548]
I have a script that checks on various build situations in order to react on this. To get the output of osc machine parsable, I'm using the --csv parameter, which has worked for a long time to my likings.

since recently though, I have noticed this throwing a stack trace, like:
```
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 5053, in do_results
    print('\n'.join(format_results(results, opts.format)))
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 5495, in format_results
    return [format % r for r in results]
TypeError: format requires a mapping
```

**Comment by marcus-h** [comment]
Fixed in commit 4c39b6316260723669a5a10d0056e44fdbfd893e.
Thanks for report! (Btw., actually this should be filed in the osc
project (https://github.com/openSUSE/osc/issues) :))
