### ISSUE TITLE
updating from 2.7.4 to 2.8.1 fails during db:migrate

### ISSUE THREAD

**Issue by jsjhb** [openSUSE/open-build-service#2949]
Issue/Feature description
====================
Machine is an old installation updates in steps over the years from 2.1.
Until today it was a 2.6 on openSUSE 13.2, I made an update to obs 2.7, still on 13.2.
After that update to openSUSE Leap 42.1, still with 2.7.4.
Update to obs 2.8.1, following README.UPDATERS:

RAILS_ENV="production" rails.ruby2.4 db:migrate
----
/usr/lib64/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/usr/lib64/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/usr/lib64/ruby/gems/2.4.0/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Fixnum is deprecated
/usr/lib64/ruby/gems/2.4.0/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Bignum is deprecated
/usr/lib64/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
== 20170123115500 RemoveDuplicateIndexes: migrating ===========================
-- execute("ALTER TABLE `attrib_namespace_modifiable_bies` DROP INDEX `index_attrib_namespace_modifiable_bies_on_attrib_namespace_id`;")
   -> 0.0252s
-- execute("ALTER TABLE `attrib_types` DROP INDEX `attrib_namespace_id`;")
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Can't DROP 'attrib_namespace_id'; check that column/key exists: ALTER TABLE `attrib_types` DROP INDEX `attrib_namespace_id`;
/srv/www/obs/api/db/migrate/20170123115500_remove_duplicate_indexes.rb:32:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: Can't DROP 'attrib_namespace_id'; check that column/key exists: ALTER TABLE `attrib_types` DROP INDEX `attrib_namespace_id`;
/srv/www/obs/api/db/migrate/20170123115500_remove_duplicate_indexes.rb:32:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Mysql2::Error: Can't DROP 'attrib_namespace_id'; check that column/key exists
/srv/www/obs/api/db/migrate/20170123115500_remove_duplicate_indexes.rb:32:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
----
The index in 20170123115500 is not in the database, thus the migration fails.

Expected result
============
it's obvious ;-)

How to Reproduce
===============
dunno, but probably take a 2.7.4 on 42.1, and migrate to 2.8.1
If this is ok, then follow:
openSUSE 13.2 -> obs 2.6.x
migrate to 2.7.4
update to openSUSE Leap 42.1
migrate to 2.8.1

Further information
===============
* A link to an OBS instance showing the issue
https://buildhost.jacobs-university.de - if access needed, please contact me
probably pmbs.links2linux.de is affected too, my buildhost would have been the test case for PMBS
* Exact server version (in case a private instance is used)
2.7.4->2.8.1

**Comment by jsjhb** [comment]
The installation used in pmbs.links2linux.de showed similar - though not identical - problems:
relevant lines from the db:migrate script:
----
== 20170123115500 RemoveDuplicateIndexes: migrating ===========================
-- execute("ALTER TABLE `attrib_namespace_modifiable_bies` DROP INDEX `index_attrib_namespace_modifiable_bies_on_attrib_namespace_id`;")
   -> 0.0082s
-- execute("ALTER TABLE `attrib_types` DROP INDEX `attrib_namespace_id`;")
   -> 0.0087s
-- execute("ALTER TABLE `binary_releases` DROP INDEX `index_binary_releases_on_binary_name`;")
   -> 0.0087s
-- execute("ALTER TABLE `bs_request_actions` DROP INDEX `index_bs_request_actions_on_target_project_and_source_project`;")
   -> 0.0096s
-- execute("ALTER TABLE `cache_lines` DROP INDEX `index_cache_lines_on_project`;")
   -> 0.0295s
-- execute("ALTER TABLE `channels` DROP INDEX `package_id`;")
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Can't DROP 'package_id'; check that column/key exists: ALTER TABLE `channels` DROP INDEX `package_id`;
/srv/www/obs/api/db/migrate/20170123115500_remove_duplicate_indexes.rb:90:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: Can't DROP 'package_id'; check that column/key exists: ALTER TABLE `channels` DROP INDEX `package_id`;
/srv/www/obs/api/db/migrate/20170123115500_remove_duplicate_indexes.rb:90:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Mysql2::Error: Can't DROP 'package_id'; check that column/key exists
/srv/www/obs/api/db/migrate/20170123115500_remove_duplicate_indexes.rb:90:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
----

The database there seems to have some of the keys added, but also not all.

**Comment by adrianschroeter** [comment]
The attrib_namespace_id key should exist in 2.7 installations. Not sure why it doesn't for you, but you should be able to continue by removing (commenting out) this line number 90 in that migration.
Is this solving your issue?

**Comment by adrianschroeter** [comment]
and I am not aware that we released 2.8.1 already .... you speak about current 2.8 git branch, right?

**Comment by jsjhb** [comment]
Probably, I tried installing obs-server-2.8-1.5.noarch.rpm and all other packages from
http://download.opensuse.org/repositories/OBS:/Server:/2.8/openSUSE_42.2/noarch/

If the attrib_namespace_id should be in 2.7, then the update from 2.6 to 2.7 did not introduce them for me.
I will try to grab a db structure from my backups from 2.6, and the 2.7 on both of my machines and provide them later today.

**Comment by jsjhb** [comment]
I cannot retrieve the pure dump from PMBS' version 2.6, here is the structure from 2.7.4
http://hawk.jacobs-university.de/NzI3NmRiYmFmZWRlZjQ1ZGRkNGZlNjBk/obs_db_2.7_pmbs.sql

My buildhost had/has db structure
2.6: http://hawk.jacobs-university.de/NzI3NmRiYmFmZWRlZjQ1ZGRkNGZlNjBk/obs_db_2.6_buildhost.sql
2.7:http://hawk.jacobs-university.de/NzI3NmRiYmFmZWRlZjQ1ZGRkNGZlNjBk/obs_db_2.7_buildhost.sql

Hope that helps.
As said, both old installations, regularly updated from the respective http://download.opensuse.org/repositories/OBS:/Server: repos.

**Comment by computersalat** [comment]
running into this issue ...
```
obs:/srv/www/obs/api # RAILS_ENV="production" rails.ruby2.4 db:migrate
/usr/lib64/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/usr/lib64/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/usr/lib64/ruby/gems/2.4.0/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Fixnum is deprecated
/usr/lib64/ruby/gems/2.4.0/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Bignum is deprecated
/usr/lib64/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
== 20170123115500 RemoveDuplicateIndexes: migrating ===========================
-- execute("ALTER TABLE `attrib_namespace_modifiable_bies` DROP INDEX `index_attrib_namespace_modifiable_bies_on_attrib_namespace_id`;")
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Can't DROP 'index_attrib_namespace_modifiable_bies_on_attrib_namespace_id'; check that column/key exists: ALTER TABLE `attrib_namespace_modifiable_bies` DROP INDEX `index_attrib_namespace_modifiable_bies_on_attrib_namespace_id`;
/srv/www/obs/api/db/migrate/20170123115500_remove_duplicate_indexes.rb:18:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: Can't DROP 'index_attrib_namespace_modifiable_bies_on_attrib_namespace_id'; check that column/key exists: ALTER TABLE `attrib_namespace_modifiable_bies` DROP INDEX `index_attrib_namespace_modifiable_bies_on_attrib_namespace_id`;
/srv/www/obs/api/db/migrate/20170123115500_remove_duplicate_indexes.rb:18:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Mysql2::Error: Can't DROP 'index_attrib_namespace_modifiable_bies_on_attrib_namespace_id'; check that column/key exists
/srv/www/obs/api/db/migrate/20170123115500_remove_duplicate_indexes.rb:18:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
```
#1553 - Kann Index 'index_attrib_types_on_attrib_namespace_id_and_name'
nicht löschen: wird für eine Fremdschlüsselbeschränkung benötigt
```
how to fix ?

**Comment by hennevogel** [comment]
@computersalat see adrians first comment...
