### ISSUE TITLE
flickering spec: revokes request

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3002]
This spec is flickering:

```
1) Requests revoke revokes request
     Failure/Error: expect(page).to have_text('Request revoked!')
       expected to find text "Request revoked!" in "Watchlist Open Build Service > Request 1 kugelblitz | 
Home Project | Logout Overview Request 1 (new) a long text - a long text - a long text - a long text - a 
long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a 
long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a 
long text - a long [+] Add a review Created by kugelblitz now In state new Submit ball Submit package 
home:kugelblitz / ball to package home:titan / goal No source changes! Build Results Rpmlint Results 
The project this package belongs to currently has no build targets defined. My Decision Request 
History kugelblitz created request now a long text - a long text - a long text - a long [+] Comments for 
request 1 (0) kugelblitz: Your Profile Home Project Logout Locations Projects Search Status Monitor 
Help Open Build Service OBS Manuals openSUSEs OBS Portal Reporting a Bug Contact Mailing List 
Forums Chat (IRC) Twitter Open Build Service (OBS) is an openSUSE project."
     # ./spec/features/webui/requests_spec.rb:163:in `block (3 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
```

**Comment by bgeuken** [comment]
This test got replaced by a controller test in 20a60940c56bb2610270c79a2ff0f3c9b228d670

Closing
