### ISSUE TITLE
[api] error running new DB migration 20170509123922 AddReferencesToBsRequestAction

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#3109]
Issue/Feature description
====================

Running the new migration with:
$ RAILS_ENV=production bundle exec rails.ruby2.4 db:migrate
causes a mysql failure

Expected result
============

Migration should pass without error

How to Reproduce
===============

1. Install new git master
2. run above migration command

Further information
===============

Error line from the migration:

`
-- add_reference(:bs_request_actions, :target_package, {:index=>true})
   -> 0.3216s
-- add_reference(:bs_request_actions, :target_project, {:index=>true})
   -> 0.3392s
-- add_reference(:bs_request_actions, :source_package, {:index=>true})
   -> 0.4258s
-- add_reference(:bs_request_actions, :source_project, {:index=>true})
   -> 0.3647s
-- execute("      UPDATE bs_request_actions\n      INNER JOIN projects ON projects.name = bs_request_actions.target_project\n      SET bs_request_actions.target_project_id = projects.id\n      WHERE bs_request_actions.target_project IS NOT NULL\n")
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '=':       UPDATE bs_request_actions
      INNER JOIN projects ON projects.name = bs_request_actions.target_project
      SET bs_request_actions.target_project_id = projects.id
      WHERE bs_request_actions.target_project IS NOT NULL
/srv/www/obs/api/db/migrate/20170509123922_add_references_to_bs_request_action.rb:14:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '=':       UPDATE bs_request_actions
      INNER JOIN projects ON projects.name = bs_request_actions.target_project
      SET bs_request_actions.target_project_id = projects.id
      WHERE bs_request_actions.target_project IS NOT NULL
/srv/www/obs/api/db/migrate/20170509123922_add_references_to_bs_request_action.rb:14:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Mysql2::Error: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='
/srv/www/obs/api/db/migrate/20170509123922_add_references_to_bs_request_action.rb:14:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate

`

**Comment by ChrisBr** [comment]
@mmohring thanks for reporting!

Please try to add the following to the beginning of the migration:

```
    execute('ALTER TABLE bs_request_actions MODIFY target_project VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci;')
    execute('ALTER TABLE bs_request_actions MODIFY target_package VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci;')
    execute('ALTER TABLE bs_request_actions MODIFY source_project VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci;')
    execute('ALTER TABLE bs_request_actions MODIFY source_package VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci;')
```

**Comment by mmohring** [comment]
@ChrisBr thanks, that worked. 

I had to first also remove the references because the "up" was interrupted, with the 4 calls to "remove_reference(:bs_request_actions, ..." .

**Comment by ChrisBr** [comment]
@mmohring yep, I will add these to the migration! Thanks for reporting and trying it out!

**Comment by mdeniz** [comment]
Ping, this is still valid?

**Comment by ChrisBr** [comment]
Yes, still valid, see https://github.com/openSUSE/open-build-service/blob/master/src/api/db/migrate/20170509123922_add_references_to_bs_request_action.rb
