### ISSUE TITLE
2.4.2: webui URI::InvalidURIError 

### ISSUE THREAD

**Issue by KostyaSha** [openSUSE/open-build-service#332]
```
[INFO |#22123] Processing by PackageController#binary as HTML
[INFO |#22123]   Parameters: {"arch"=>"x86_64", "filename"=>"PROJECT-10.9-bareOS.x86_64-0.1.0-Build<<
SPEC_REL>.1.iso", "package"=>"project-image-pxe", "project"=>"PROJECT:trunk:PROJECT",
 "repository"=>"images"}
[INFO |#22123] Authenticated request to "/package/binary?arch=x86_64&filename=PROJECT-10.9-bareOS.x88
6_64-0.1.0-Build%3CSPEC_REL%3E.1.iso&package=project-image-pxe&project=PROJECT%3Atru
nk%3APROJECT&repository=images" from kshautsou
[INFO |#22123] Completed 500 Internal Server Error in 196ms

[FATAL|#22123] URI::InvalidURIError (bad URI(is not URI?): http://obs-server.domain.com:82//PP
ROJECT:/trunk:/PROJECT/images/iso/PROJECT-10.9-bareOS.x86_64-0.1.0-Build<SPEC_REL>.1
.iso):
  app/controllers/package_controller.rb:1073:in `file_available?'
  app/controllers/package_controller.rb:132:in `binary'
```

Yes, file is available.

**Comment by eduardoj** [comment]
As 2.4.2 is not supported anymore I will close this. Please, feel free to open it if this is still happening in a supported version.

Checked https://build.opensuse.org/package/binaries/OBS:Server:2.4/OBS-Appliance?repository=images and all the links are working. Please provide another example if it is still happening.
