### ISSUE TITLE
Backend in Vagrant setup sometimes aborts with exception

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3330]
Sometimes, the `script/start_test_backend` aborts with the exception:
```
/vagrant/src/api/app/models/user.rb:286:in `get_default_admin': undefined method `is_admin?' for nil:NilClass (NoMethodError)
Did you mean?  is_haml?
	from /vagrant/src/api/app/models/update_notification_events.rb:51:in `perform'
	from script/start_test_backend:407:in `block (2 levels) in <main>'
	from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
	from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
	from /usr/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
	from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
	from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/transactions.rb:210:in `transaction'
	from script/start_test_backend:406:in `block in <main>'
/vagrant/src/api/app/models/user.rb:286:in `get_default_admin': undefined method `is_admin?' for nil:NilClass (NoMethodError)
Did you mean?  is_haml?
	from /vagrant/src/api/app/models/update_notification_events.rb:51:in `perform'
	from script/start_test_backend:407:in `block (2 levels) in <main>'
	from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
	from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
	from /usr/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
	from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
	from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/transactions.rb:210:in `transaction'
	from script/start_test_backend:406:in `block in <main>'
```

**Comment by M0ses** [comment]
hmm, seems like it is a problem in src/api/script/start_test_backend and not in the backend itself?

**Comment by bgeuken** [comment]
We switched to docker by now
