### ISSUE TITLE
script/start_test_backend is broken

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#3421]
That's what I get if I run `vagrant exec script/start_test_backend`:

```
WARNING: Nokogiri was built against LibXML version 2.9.4, but has dynamically loaded 2.9.1
warning: parser/current is loading parser/ruby24, which recognizes
warning: 2.4.0-compliant syntax, but you are running 2.4.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
memcached already started (pid=1037).
Creating backend config at /config/BSConfig.pm
/usr/lib64/ruby/2.4.0/fileutils.rb:229:in `mkdir': Permission denied @ dir_s_mkdir - /config (Errno::EACCES)
        from /usr/lib64/ruby/2.4.0/fileutils.rb:229:in `fu_mkdir'
        from /usr/lib64/ruby/2.4.0/fileutils.rb:166:in `block in mkdir'
        from /usr/lib64/ruby/2.4.0/fileutils.rb:165:in `each'
        from /usr/lib64/ruby/2.4.0/fileutils.rb:165:in `mkdir'
        from script/start_test_backend:87:in `<main>'
```

This is not a local problem, as @DavidKang @mdeniz and @evanrolfe has the same problem. :sob: I can not write more tests! :sob: :sob: :sob:

**Comment by Ana06** [comment]
Broke here: https://github.com/openSUSE/open-build-service/commit/2ed5dedf39357ab1c0e3988b2419e6b884047d76

**Comment by hennevogel** [comment]
This broke with 2ed5dedf39357ab1c0e3988b2419e6b884047d76 

We are frequently starting the test backend also in development.
