### ISSUE TITLE
Requests project with list of requests going through a request list

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3531]
```
1) Requests project with list of requests going through a request list
     Failure/Error: expect(page).to have_link("Show request ##{request_1.id}")
       expected to find link "Show request #243" but there were no matches
     # ./spec/features/webui/requests_spec.rb:312:in `block (3 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
```

**Comment by Ana06** [comment]
@hennevogel do you know when this failed?

**Comment by Ana06** [comment]
Nevermind, I already know what the problem is :wink:

**Comment by ChrisBr** [comment]
Also a request test which seems to be similar and happened a lot of times recently to me:

```
  1) Requests project with list of requests going through a request list
     Failure/Error: expect(page).to have_link("Show request ##{request_1.id}")
       expected to find visible link "Show request #89" but there were no matches
     # ./spec/features/webui/requests_spec.rb:213:in `block (3 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
```

**Comment by coolo** [comment]
this feature - and the test to it - was removed in last sprint
