### ISSUE TITLE
TypeError: wrong argument type Integer (expected Proc)

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3532]
```
TypeError:         TypeError: wrong argument type Integer (expected Proc)
            test/functional/webui/spider_test.rb:98:in `crawl'
            test/functional/webui/spider_test.rb:162:in `test_spider_as_admin'
            test/test_helper.rb:127:in `block in __run'
            test/test_helper.rb:127:in `map'
            test/test_helper.rb:127:in `__run'
```

* Happened on https://travis-ci.org/openSUSE/open-build-service/jobs/245651607
* Could be related to this bug in ruby https://bugs.ruby-lang.org/issues/13107
* upgrading to ruby 2.4.1 could solve it?

**Comment by Ana06** [comment]
Do we still get this error? this issue is from Aug... :thinking:

**Comment by hennevogel** [comment]
have not seen it for a long time...
