### ISSUE TITLE
Capybara::ElementNotFound: Unable to find css "#link-to-user-home"

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3533]
```
Webui::MaintenanceWorkflowTest
  test_full_maintenance_workflow                                 ERROR (8.56s)
Capybara::ElementNotFound:         Capybara::ElementNotFound: Unable to find css "#link-to-user-home"
            test/test_helper.rb:220:in `login_user'
            test/test_helper.rb:228:in `login_tom'
            test/functional/webui/maintenance_workflow_test.rb:17:in `test_full_maintenance_workflow'
            test/test_helper.rb:127:in `block in __run'
            test/test_helper.rb:127:in `map'
            test/test_helper.rb:127:in `__run'
```

*Happened on  https://travis-ci.org/openSUSE/open-build-service/jobs/247407502

**Comment by bgeuken** [comment]
This test got removed recently as part of the test suite switch to rspec
