### ISSUE TITLE
expected to find text "accepted and forwarded" in "none".

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3534]
* Happened on  https://travis-ci.org/openSUSE/open-build-service/jobs/247407502

```
  test_branch_package_double_and_submit_back                      FAIL (6.39s)
Minitest::Assertion:         expected to find text "accepted and forwarded" in "none".
        test/functional/webui/package_branch_test.rb:102:in `test_branch_package_double_and_submit_back'
        test/test_helper.rb:127:in `block in __run'
        test/test_helper.rb:127:in `map'
        test/test_helper.rb:127:in `__run'
```

**Comment by bgeuken** [comment]
This test got removed recently as part of the test suite switch to rspec
