### ISSUE TITLE
Expected false to be truthy.

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3535]
* Happened on https://travis-ci.org/openSUSE/open-build-service/jobs/249663117

```
          test_list_all_groups                                            FAIL (1.58s)
Minitest::Assertion:         Expected false to be truthy.
        test/functional/webui/group_controller_test.rb:19:in `test_list_all_groups'
        test/test_helper.rb:127:in `block in __run'
        test/test_helper.rb:127:in `map'
        test/test_helper.rb:127:in `__run'
```

**Comment by bgeuken** [comment]
This test got removed recently as part of the test suite switch to rspec
