### ISSUE TITLE
Unable to find css "a" with text "bnc#700501"

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3536]
* Happened on https://travis-ci.org/openSUSE/open-build-service/jobs/250369496

```
  test_create_patchinfo_with_issues                              ERROR (11.07s)
Capybara::ElementNotFound:         Capybara::ElementNotFound: Unable to find css "a" with text "bnc#700501"
            test/functional/webui/patchinfo_controller_test.rb:183:in `test_create_patchinfo_with_issues'
            test/test_helper.rb:127:in `block in __run'
            test/test_helper.rb:127:in `map'
            test/test_helper.rb:127:in `__run'
```

**Comment by bgeuken** [comment]
This test got removed recently as part of the test suite switch to rspec
