### ISSUE TITLE
Expected: :info           Actual: nil

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3537]
* Happened on https://travis-ci.org/openSUSE/open-build-service/jobs/250387509

```
Webui::EditPackageUsersTest
  test_add_and_edit_package_people                                FAIL (10.48s)
Minitest::Assertion:         Expected: :info
          Actual: nil
        test/functional/webui/users_test.rb:156:in `delete_user'
        test/functional/webui/users_test.rb:50:in `test_add_and_edit_package_people'
        test/test_helper.rb:127:in `block in __run'
        test/test_helper.rb:127:in `map'
        test/test_helper.rb:127:in `__run'
```

**Comment by bgeuken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Expected: :info Actual: nil #3537](https://trello.com/c/DjSA6X5n/493-expected-info-actual-nil-3537)
