### ISSUE TITLE
test_attrib_with_single_value 

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3629]
* https://travis-ci.org/openSUSE/open-build-service/jobs/265564864

```
test_attrib_with_single_value                                   FAIL (8.64s)

Minitest::Assertion:         --- expected

        +++ actual

        @@ -1 +1 @@

        -"Attribute sucessfully deleted!"

        +"none"

        test/functional/webui/attributes_test.rb:111:in `delete'

        test/functional/webui/attributes_test.rb:145:in `test_attrib_with_single_value'

        test/test_helper.rb:126:in `block in __run'

        test/test_helper.rb:126:in `map'

        test/test_helper.rb:126:in `__run'
```

**Comment by bgeuken** [comment]
This test got removed recently as part of the test suite switch to rspec
