### ISSUE TITLE
Project#remove_all_groups deletes the relationship

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#3805]
https://travis-ci.org/openSUSE/open-build-service/jobs/274530612
```
  1) Project#remove_all_groups deletes the relationship
     Failure/Error: raise WritePermissionError, "No permission to modify project '#{name}' for user '#{User.current.login}'"
     
     Project::WritePermissionError:
       No permission to modify project 'project_696' for user '_nobody_'
     # ./app/models/project.rb:497:in `check_write_access!'
     # ./app/mixins/has_relationships.rb:92:in `remove_all_groups'
     # ./spec/models/project_spec.rb:518:in `block (3 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
```

**Comment by Ana06** [comment]
This is supposed to be fixed :running_man:
