### ISSUE TITLE
SSL crash on commenting in test instance

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#4030]
This happens sporadically when starting a new rabbitmq connection

```
I, [2017-10-17T15:21:05.258173 #3779]  INFO -- : [359f6ac9-07a2-480f-990c-0b0e0abb055e] [3779:90.47] Completed 500 Internal Server Error in 54ms (ActiveRecord: 13.9ms | Backend: 0.0ms | XML: 0.0ms)
F, [2017-10-17T15:21:05.260121 #3779] FATAL -- : [359f6ac9-07a2-480f-990c-0b0e0abb055e] [3779:90.47]   
F, [2017-10-17T15:21:05.260181 #3779] FATAL -- : [359f6ac9-07a2-480f-990c-0b0e0abb055e] [3779:90.47] OpenSSL::SSL::SSLError (SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server hello A):
F, [2017-10-17T15:21:05.260220 #3779] FATAL -- : [359f6ac9-07a2-480f-990c-0b0e0abb055e] [3779:90.47]   
F, [2017-10-17T15:21:05.260343 #3779] FATAL -- : [359f6ac9-07a2-480f-990c-0b0e0abb055e] [3779:90.47] lib/rabbitmq_bus.rb:13:in `start_connection'
[359f6ac9-07a2-480f-990c-0b0e0abb055e] lib/rabbitmq_bus.rb:4:in `publish'
[359f6ac9-07a2-480f-990c-0b0e0abb055e] app/models/event/base.rb:268:in `send_to_bus'
[359f6ac9-07a2-480f-990c-0b0e0abb055e] app/controllers/webui/comments_controller.rb:7:in `create'
[359f6ac9-07a2-480f-990c-0b0e0abb055e] config/initializers/wrap_parameters.rb:38:in `call'

**Comment by mdeniz** [comment]
It could be related? https://stackoverflow.com/questions/25814210/opensslsslsslerror-ssl-connect-syscall-returned-5-errno-0-state-sslv3-read

**Comment by evanrolfe** [comment]
@coolo do you know what version of SSL the rabbitmq server is running?

The rabbitmq [docs](http://rubybunny.info/articles/tls.html) says that it:

> will reject SSLv3 connections unless configured otherwise

**Comment by coolo** [comment]
```
openssl s_client -connect rabbit.opensuse.org:5671

CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 High Assurance Server CA
verify return:1
depth=0 C = US, L = Provo, ST = Utah, O = "Novell, Inc.", CN = *.opensuse.org
verify return:1
---
Certificate chain
 0 s:/C=US/L=Provo/ST=Utah/O=Novell, Inc./CN=*.opensuse.org
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
 1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGQzCCBSugAwIBAgIQBT4IOplFYhKMEzLM9xHZSDANBgkqhkiG9w0BAQsFADBw
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMS8wLQYDVQQDEyZEaWdpQ2VydCBTSEEyIEhpZ2ggQXNz
dXJhbmNlIFNlcnZlciBDQTAeFw0xNTAyMTcwMDAwMDBaFw0xODA0MjMxMjAwMDBa
MFwxCzAJBgNVBAYTAlVTMQ4wDAYDVQQHEwVQcm92bzENMAsGA1UECBMEVXRhaDEV
MBMGA1UEChMMTm92ZWxsLCBJbmMuMRcwFQYDVQQDDA4qLm9wZW5zdXNlLm9yZzCC
AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMCIOeWzSzeA7Yg+B7IWVj4c
08Eo76/cxKl1t53L3KHCMUbZJYWlOMFWnyRWFynzVohVHZH75oI8ISC91HNfn93T
Mk8WOqXq6f95XzdL5btXiYQnJupcsIL8HHP8Nv37ZggX27YM/EWOcxP4wMzZXnPm
kO+XHwLFBQKZuNult+el69E2sxYDKHNsyzNh/HLKsoZjGOyMmamrTBsujY4SdAJg
RtXHzFgm66sDFIUXNVR+V0j4+jqg4dMaUatN4UMn86/3GH0sDGyc8sI3qL8AJURN
Qf/GX839x1QcweTVsrsfQznBusB6frJusKi5TiH2mheU58SGkHeCLkuGhni8v4Kw
ek+4EvrWeJ3UzjjOzh2pOrYkD5UQXoOuo2cEa37PMPBVOz3uk8h6BexiNA7qEb7T
1PJR0B8q8hvWgZ3YY8lUVAelPNezQZ9FkbmDcCpKgrbAPb22vh05DLWm0FXPgCWC
mEYSo3rhNfBq9F+gSn10cs6CdKaBeJ3TdabO2Ou8KYf/HzxHQqQT35jETlEK8Vsx
iqRhSDP0ZzGIZiN/o8n8W+uPJrEwJOZNueOO8ZCkLROgxGHAeT+l4ePG0WTjv9PQ
td58TLgvruoQ4Nellak6ypKStPdIHgN8EhYL9Ou+f3KC0F9HBizPwQL6MH0TeOsx
la9S4D1vbpX04TFdyF1jAgMBAAGjggHrMIIB5zAfBgNVHSMEGDAWgBRRaP+QrwIH
dTzM2WVkYqISuFlyOzAdBgNVHQ4EFgQUjKPK+SsT+RT4PXtarNhTjyfKe8owJwYD
VR0RBCAwHoIOKi5vcGVuc3VzZS5vcmeCDG9wZW5zdXNlLm9yZzAOBgNVHQ8BAf8E
BAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMHUGA1UdHwRuMGww
NKAyoDCGLmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9zaGEyLWhhLXNlcnZlci1n
My5jcmwwNKAyoDCGLmh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9zaGEyLWhhLXNl
cnZlci1nMy5jcmwwQgYDVR0gBDswOTA3BglghkgBhv1sAQEwKjAoBggrBgEFBQcC                                                                                                                                                 
ARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzCBgwYIKwYBBQUHAQEEdzB1                                                                                                                                                 
MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wTQYIKwYBBQUH                                                                                                                                                 
MAKGQWh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFNIQTJIaWdo                                                                                                                                                 
QXNzdXJhbmNlU2VydmVyQ0EuY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQEL                                                                                                                                                 
BQADggEBAH01BMN0Jakr700M2bi3njgjlN1vvyTd8c2JJRJF7fYwis7QW2hxMqeU                                                                                                                                                 
Jkb9enkOQ6lWNMQmSSgnxDAv5O0nnmtji3nQTSm4cn5nXGkIFVQYQb1AcYNkBbUF                                                                                                                                                 
Gw8Ut0likKFUyCjE+13DDNmMn1Jda1qjaeu4OT32Pqs33+kaUQfFvTQWTFJIz0MH                                                                                                                                                 
ZU9dmw8HstT9iD562+CglElRKWBtSUjDO/2VMKc760LkHcqBDhTl7SMbUQ8B+PXs                                                                                                                                                 
TRBT8FVl6aFWI30N3vxlQMpZPuXPMqh0bLZeaKsFicgUgfu8lrT3E1pB3QLauj/W                                                                                                                                                 
TLL6GM+Qj7v0mnlGH3pwu4YIKLyVJ20=                                                                                                                                                                                 
-----END CERTIFICATE-----                                                                                                                                                                                        
subject=/C=US/L=Provo/ST=Utah/O=Novell, Inc./CN=*.opensuse.org                                                                                                                                                   
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA                                                                                                                        
---                                                                                                                                                                                                              
No client certificate CA names sent                                                                                                                                                                              
Peer signing digest: SHA512                                                                                                                                                                                      
Server Temp Key: ECDH, P-256, 256 bits                                                                                                                                                                           
---                                                                                                                                                                                                              
SSL handshake has read 3730 bytes and written 419 bytes                                                                                                                                                          
---                                                                                                                                                                                                              
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384                                                                                                                                                          
Server public key is 4096 bit                                                                                                                                                                                    
Secure Renegotiation IS supported                                                                                                                                                                                
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 2ED1164EE3B4779C7C00222DEDC3FBE84D59A310BB0CD5ADB5B179BE75CC1DE1
    Session-ID-ctx: 
    Master-Key: 81CD55C2537D47325C53724B9347A8AA327C0B5D426A4FAA4843A4FD0280C0A10D28ED6CBD9AC53C34C14371E4506AB5
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 600 (seconds)
    TLS session ticket:
    0000 - d8 08 85 d5 cb 5e 3f db-37 a1 1f cd f8 d0 01 7b   .....^?.7......{
    0010 - 3e 19 9b 42 01 af 72 57-04 49 46 a8 94 21 9f 48   >..B..rW.IF..!.H
    0020 - 70 c0 8c 98 cb 4b 8b 54-5c 58 e6 69 28 53 80 b9   p....K.T\X.i(S..
    0030 - 8b 2a 27 dd 17 64 62 3a-1d 4d 70 f3 4c 4d d2 c0   .*'..db:.Mp.LM..
    0040 - 4b 32 df b7 71 78 fe 78-4c 88 05 e9 bd c8 40 0a   K2..qx.xL.....@.
    0050 - 4d f8 ac 4f 25 71 bf f1-fb 08 30 bf db 0a 73 9a   M..O%q....0...s.
    0060 - 0d 2b 34 d3 f1 6c b0 73-db ac d4 ce d1 fe dd a8   .+4..l.s........
    0070 - 97 53 cd 0f f8 fc aa 9f-84 73 e9 a5 ff c7 83 5e   .S.......s.....^
    0080 - c7 56 0b e6 30 da 40 39-e2 5b 04 86 5d 1c e6 16   .V..0.@9.[..]...
    0090 - 0a 7f 00 27 80 45 7c 29-37 a5 76 5e 52 0e 91 24   ...'.E|)7.v^R..$

    Start Time: 1508253288
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---


closed
```

**Comment by coolo** [comment]
darix and me believe the HA proxy closed the connection when $connection.start was trying to find the session, so we were crashing. I changed the heartbeat_interval to 10 and the timeout of the HA proxy was increased to 30min - so we should be good.
