### ISSUE TITLE
Docker setup broken within last day

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#4462]
Issue/Feature description
====================

I have not done a bisect to determine what commit, but I see some pertaining to ruby versions and what not. [Broke on our CI](https://travis-ci.org/openSUSE/osc-plugin-factory/jobs/338735735) and I can confirm locally.

```
Step 9/11 : RUN gem install thor:0.19 foreman
 ---> Running in 89c7d4184e85
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/lib64/ruby/gems/2.1.0 directory.
        /usr/lib64/ruby/2.1.0/rubygems/installer.rb:629:in `verify_gem_home'
        /usr/lib64/ruby/2.1.0/rubygems/installer.rb:749:in `pre_install_checks'
        /usr/lib64/ruby/2.1.0/rubygems/installer.rb:213:in `install'
        /usr/lib64/ruby/2.1.0/rubygems/request_set.rb:142:in `block in install'
        /usr/lib64/ruby/2.1.0/rubygems/request_set.rb:126:in `each'
        /usr/lib64/ruby/2.1.0/rubygems/request_set.rb:126:in `install'
        /usr/lib64/ruby/2.1.0/rubygems/dependency_installer.rb:391:in `install'
        /usr/lib64/ruby/2.1.0/rubygems/commands/install_command.rb:219:in `install_gem'
        /usr/lib64/ruby/2.1.0/rubygems/commands/install_command.rb:263:in `block in install_gems'
        /usr/lib64/ruby/2.1.0/rubygems/commands/install_command.rb:259:in `each'
        /usr/lib64/ruby/2.1.0/rubygems/commands/install_command.rb:259:in `install_gems'
        /usr/lib64/ruby/2.1.0/rubygems/commands/install_command.rb:171:in `execute'
        /usr/lib64/ruby/2.1.0/rubygems/command.rb:305:in `invoke_with_build_args'
        /usr/lib64/ruby/2.1.0/rubygems/command_manager.rb:167:in `process_args'
        /usr/lib64/ruby/2.1.0/rubygems/command_manager.rb:137:in `run'
        /usr/lib64/ruby/2.1.0/rubygems/gem_runner.rb:54:in `run'
        /usr/bin/gem:21:in `<main>'
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c gem install thor:0.19 foreman' returned a non-zero code: 1
docker-compose stop
rake aborted!
Command failed with status (1): [docker-compose build frontend...]
/home/jberry/osc-plugin-factory/.open-build-service/Rakefile:13:in `block (2 levels) in <top (required)>'
Tasks: TOP => docker:build
(See full trace by running task with --trace)
```

Expected result
============

`rake docker:build` succeed

How to Reproduce
===============

Invoke `rake docker:build` on latest.

**Comment by jberry-suse** [comment]
Apparently our CI does catch things. :) Presumably since docker setup not being used by upstream CI.

**Comment by bgeuken** [comment]
https://github.com/openSUSE/open-build-service/commit/8fd450e841aebd09b5158878826506b0f479705f broke it. https://github.com/openSUSE/open-build-service/pull/4460 should fix it.

**Comment by bgeuken** [comment]
The permission error is fixed now. But there is another issue with mysql. Might be related to the recent ruby version bump.

**Comment by jberry-suse** [comment]
Seeing the following now.

```
Step 9/12 : RUN sudo gem.ruby2.5 install thor:0.19 foreman
 ---> Running in 48b11a41ccc5
sudo: gem.ruby2.5: command not found
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c sudo gem.ruby2.5 install thor:0.19 foreman' returned a non-zero code: 1
docker-compose stop
rake aborted!
Command failed with status (1): [docker-compose build frontend...]
/home/travis/build/openSUSE/osc-plugin-factory/.open-build-service/Rakefile:13:in `block (2 levels) in <top (required)>'
/home/travis/.rvm/gems/ruby-2.4.1@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
```

**Comment by jberry-suse** [comment]
Do you not see this locally?

**Comment by bgeuken** [comment]
That's because we didn't update the other containers in [docker hub](https://hub.docker.com/u/openbuildservice/dashboard/) yet.

As soon as #4467 is merge, we can rebuild and publish them.

Meanwhile you could build them locally via
```bash
rake docker:maintainer:rebuild
rake docker:build
```

Though you need to cherry-pick 5c234bddb51f5a3294b22bf7f8b6f7dcd1507c7b

**Comment by jberry-suse** [comment]
Will do, although that won't work for our CI. Assume it will be merged today. Thanks.

**Comment by bgeuken** [comment]
New containers are building right now.

Sorry again, but we had to update to ruby 2.5 and this affects a lot of places and in this case broke our docker builds.

**Comment by bgeuken** [comment]
@jberry-suse containers are updated and everything works again. Let us know if there is still something broken

**Comment by jberry-suse** [comment]
Seems to be working, thanks.
