### ISSUE TITLE
Requests project with list of requests going through a request list

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#4617]
From https://travis-ci.org/openSUSE/open-build-service/jobs/347286383#L1332

```
  1) Requests project with list of requests going through a request list
     Failure/Error: expect(page).to have_link("Show request ##{request_2.id}")
       expected to find visible link "Show request #4" but there were no matches
     # ./spec/features/webui/requests_spec.rb:217:in `block (3 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
```

**Comment by Ana06** [comment]
ouch! duplicated! https://github.com/openSUSE/open-build-service/issues/3531 :see_no_evil:
