### ISSUE TITLE
Project#branch_remote_repositories kiwi project 

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#4621]
From https://travis-ci.org/openSUSE/open-build-service/jobs/349219278#L1332

```
  1) Project#branch_remote_repositories kiwi project 
     Failure/Error: raise SaveError, "project name mismatch: #{project.name} != #{xmlhash['name']}"
     
     Project::SaveError:
       project name mismatch: openSUSE_41 != home:tom
     # ./app/models/project/update_from_xml_command.rb:31:in `run'
     # ./app/models/project.rb:595:in `update_from_xml!'
     # ./app/models/project.rb:1070:in `branch_remote_repositories'
     # ./spec/models/project_spec.rb:104:in `block (3 levels) in <top (required)>'
     # ./spec/models/project_spec.rb:211:in `block (4 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
```

**Comment by coolo** [comment]
we don't see this any longer
