### ISSUE TITLE
Projects repositories tab DoD repositories adding DoD repositories

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#4622]
From https://travis-ci.org/openSUSE/open-build-service/jobs/349219278#L1344

```
  2) Projects repositories tab DoD repositories adding DoD repositories
     Failure/Error:
       within '.repository-container' do
         expect(page).to have_text('My DoD repository')
         expect(page).to have_link('mDelete repository')
         expect(page).to have_text('Download on demand sources')
         expect(page).to have_link('Add')
         expect(page).to have_link('Edit')
         expect(page).to have_link('Delete')
         expect(page).to have_link('http://somerandomurl.es')
         expect(page).to have_text('rpmmd')
       end
     
     Capybara::ElementNotFound:
       Unable to find visible css ".repository-container"
     # ./spec/features/webui/projects_spec.rb:200:in `block (4 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
```

**Comment by coolo** [comment]
no longer flickering
