### ISSUE TITLE
SearchController cassettes are hiding (testsuite) bugs

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#5235]
I'll skip them in my branch, but I would like to have a reference

```
rm -r src/api/spec/cassettes/Webui_SearchController/

Failures:

  1) Webui::SearchController GET #owner assigns results for devel package
     Failure/Error: expect(assigns(:results)[0].users).to eq('maintainer'=>['DevelIggy'])
     
     NoMethodError:
       undefined method `users' for nil:NilClass
     # ./spec/controllers/webui/search_controller_spec.rb:34:in `block (3 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'

  2) Webui::SearchController GET #owner assigns results
     Failure/Error: expect(assigns(:results)[0].users).to eq('maintainer'=>['Iggy'])
     
     NoMethodError:
       undefined method `users' for nil:NilClass
     # ./spec/controllers/webui/search_controller_spec.rb:27:in `block (3 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'

Finished in 2.37 seconds (files took 4.13 seconds to load)
18 examples, 2 failures

Failed examples:

rspec ./spec/controllers/webui/search_controller_spec.rb:30 # Webui::SearchController GET #owner assigns results for devel package
rspec ./spec/controllers/webui/search_controller_spec.rb:25 # Webui::SearchController GET #owner assigns results

**Comment by ChrisBr** [comment]
https://github.com/openSUSE/open-build-service/pull/5270 and https://github.com/openSUSE/open-build-service/pull/4745 will fix this issue!

cc @hennevogel

**Comment by hennevogel** [comment]
#5270 fixes the issue of this test failing without on a 'real' backend.

#4745 is just explaining what `Owner` does...
