### ISSUE TITLE
Webui::UserController GET #icon loads small icon with param

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#5303]
```
  1) Webui::UserController GET #icon loads small icon with param
     Failure/Error: expect(response.body.size).to be < 1000
     
       expected: < 1000
            got:   1060
     # ./spec/controllers/webui/user_controller_spec.rb:352:in `block (3 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
```

**Comment by eduardoj** [comment]
Still flickering here:

https://build.opensuse.org/package/live_build_log/OBS:Server:Unstable/obs-server/openSUSE_42.3/x86_64


```
[ 4860s] Failures:
[ 4860s] 
[ 4860s]   1) Webui::UserController GET #icon loads small icon with param
[ 4860s]      Failure/Error: image = ChunkyPNG::Image.from_blob(response.body)
[ 4860s] 
[ 4860s]      ChunkyPNG::SignatureMismatch:
[ 4860s]        PNG signature not found, found "<html><b" instead of "\x89PNG\r\n\x1A\n"!
[ 4860s]      # ./spec/controllers/webui/user_controller_spec.rb:354:in `block (3 levels) in <top (required)>'
[ 4860s]      # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
[ 4860s] 
[ 4860s]   2) Webui::UserController GET #icon loads big icon without param
[ 4860s]      Failure/Error: image = ChunkyPNG::Image.from_blob(response.body)
[ 4860s] 
[ 4860s]      ChunkyPNG::SignatureMismatch:
[ 4860s]        PNG signature not found, found "<html><b" instead of "\x89PNG\r\n\x1A\n"!
[ 4860s]      # ./spec/controllers/webui/user_controller_spec.rb:347:in `block (3 levels) in <top (required)>'
[ 4860s]      # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
[ 4860s] 
[ 4860s] Finished in 41 minutes 34 seconds (files took 14.42 seconds to load)
[ 4860s] 2973 examples, 2 failures, 28 pending
```

**Comment by coolo** [comment]
that means the icon route returns html - test succeeded to find a bug. Don't fix the test but the code :)

**Comment by dmarcoux** [comment]
`ActiveXML.backend.load_external_url('some_url')` doesn't deal with redirections, so this explains why the `response.body` is some HTML (as we see in the failure shared above by @eduardoj)
