### ISSUE TITLE
Package build failures due to openqa tests

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#5404]
The package builds have no network access - and we really shouldn't query openqa as part of the tests

```
[22166s]   3) ObsFactory::StagingProject#openqa_jobs @openqa_jobs is nil openqa results are relevant 
[22166s]      Failure/Error: resp = Net::HTTP.start(uri.host, use_ssl: uri.scheme == "https") { |http| http.request(req) }
[22166s] 
[22166s]      SocketError:
[22166s]        Failed to open TCP connection to openqa.opensuse.org:80 (getaddrinfo: Temporary failure in name resolution)
[22166s]      # ./app/models/obs_factory/openqa_api.rb:50:in `block in _get'
[22166s]      # ./app/models/obs_factory/openqa_api.rb:50:in `_get'
[22166s]      # ./app/models/obs_factory/openqa_api.rb:35:in `get'
[22166s]      # ./app/models/obs_factory/openqa_job.rb:78:in `find_all_by'
[22166s]      # ./app/models/obs_factory/staging_project.rb:100:in `openqa_jobs'
[22166s]      # ./spec/models/obs_factory/staging_project_spec.rb:210:in `block (5 levels) in <top (required)>'
[22166s]      # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
[22166s]      # ------------------
[22166s]      # --- Caused by: ---
[22166s]      # SocketError:
[22166s]      #   getaddrinfo: Temporary failure in name resolution
[22166s]      #   ./app/models/obs_factory/openqa_api.rb:50:in `block in _get'

**Comment by Ana06** [comment]
@coolo could you please label the issue? :pray: :pray:
