### ISSUE TITLE
Cassettes hide yet another problem 

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#5439]
master:
```
Issue
  #fetch_issues
    fetches the issues

Finished in 1.88 seconds (files took 4.51 seconds to load)
```

Now enable global_write_through in spec/support/vcr.rb and run again:
```
Issue
  #fetch_issues
    fetches the issues (FAILED - 1)

Failures:

  1) Issue#fetch_issues fetches the issues
     Failure/Error: raise ActiveXML::Transport::Error, message.force_encoding('UTF-8')
     
     ActiveXML::Transport::Error:
       <status code="400">
         <summary>element 'description' contains attributes nil</summary>
       </status>
     # ./lib/backend/connection.rb:126:in `handle_response'
     # ./lib/backend/connection.rb:112:in `put_or_post'
     # ./lib/backend/connection.rb:35:in `put'
     # ./lib/backend/connection_helper.rb:60:in `http_put'
     # ./lib/backend/api/issue_trackers.rb:9:in `write_list'
     # ./app/jobs/issue_tracker_write_to_backend_job.rb:8:in `perform'
     # ./app/models/issue_tracker.rb:24:in `delayed_write_to_backend'
     # ./spec/models/issue_spec.rb:10:in `block (3 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'

Finished in 1.86 seconds (files took 4.67 seconds to load)

**Comment by coolo** [comment]
Boah, what a mess. The bug has been in there almost since forever, but only recently uncovered by #5434 and hidden again by cassettes.

The issue that app/model/issue_tracker has after_save hooks that are only added if 
global_write_through is true. And as this config is only set to true delayed, it's basically never true when running seed.rb (which was most likely the intention of this code). 

But #5434 removed the calling to seeds, we happen to set the config variable actually *before* the class is parsed and as such the after_save hooks are added - and it's uncovered that the issue_tracker factory never added the required description attribute (which is also not validated to exist, but refused by the backend).
