### ISSUE TITLE
test_release_project flickers

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#5542]
Saw this test flickering [on travis](https://api.travis-ci.org/v3/job/411622636/log.txt) 
```
test_release_project                                            FAIL (8.66s)
Minitest::Assertion:         Expected response to be a <2XX: success>, but was a <408: Request Timeout>
        Response body: <status code="timeout_error">
          <summary>execution expired</summary>
        </status>
        test/functional/release_management_test.rb:135:in `test_release_project'
        test/test_helper.rb:117:in `block in __run'
        test/test_helper.rb:117:in `map'
        test/test_helper.rb:117:in `__run'
```

**Comment by eduardoj** [comment]
We don't use Travis any more. Can we close this issue then?

**Comment by coolo** [comment]
I've seen similiar timeouts in rspec when not using cassettes - but only on travis. So possibly this is indeed travis specific.

**Comment by hennevogel** [comment]
Let's see...

**Comment by coolo** [comment]
this is happening on circleci - but is a different test (so possibly yours will come back too):

```
Expected response to be a <2XX: success>, but was a <408: Request Timeout>
Response body: <status code="timeout_error">
  <summary>execution expired</summary>
</status>

test/functional/request_controller_test.rb:387:in `test_submit_request_with_broken_source'
test/test_helper.rb:118:in `block in __run'
test/test_helper.rb:118:in `map'
test/test_helper.rb:118:in `__run'
