### ISSUE TITLE
test_manual_branch_with_extend_names

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#5688]
```
test_manual_branch_with_extend_names                            FAIL (1.99s)
        Expected response to be a <2XX: success>, but was a <400: Bad Request>
        Response body: <status code="attribute_save">
          <summary>/var/tmp/obsbackend20180820-596-wmtu72/data/projects/home:tom:branches:BaseDistro2.0:LinkedUpdateProject.pkg/_project.mrev: No such file or directory</summary>
        </status>
        test/functional/maintenance_test.rb:893:in `test_manual_branch_with_extend_names'
        test/test_helper.rb:118:in `block in __run'
        test/test_helper.rb:118:in `map'
        test/test_helper.rb:118:in `__run'
```

**Comment by hennevogel** [comment]
You find flickering specs on circle now.

https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests?branch=master&reporting-window=last-30-days
