### ISSUE TITLE
deprecated method each_full

### ISSUE THREAD

**Issue by KostyaSha** [openSUSE/open-build-service#587]
http://apidock.com/rails/ActiveRecord/Errors/each_full
```
[FATAL|#24255] NoMethodError (undefined method `each_full' for #<ActiveModel::Errors:0x00000004228388>):
 app/controllers/application_controller.rb:247:in `extract_user'
  config/initializers/wrap_parameters.rb:35:in `call'
```
./app/controllers/application_controller.rb:              newuser.errors.each_full do |msg|

**Comment by bgeuken** [comment]
This got fixed meanwhile
