### ISSUE TITLE
Flickering 'maintained projects' test

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6238]
Looks like the autocomplete isn't properly awaited

```
[ 2066s]   1) Projects maintained projects creating a maintened project
[ 2066s]      Failure/Error: expect(page).to have_text("Added #{project.name} to maintenance")
[ 2066s]        expected to find text "Added home:Jane to maintenance" in "31ms / 21 sql\n1ms / 6 memcache\nmorla3\nWatchlist\nOpen Build Service > Projects > maintenance_project > Maintained Projects\nuser_1148 | Tasks | Home Project | Logout\nAdd Project to Maintenance\nDo you want to maintain project maintenance_project?\nProject to maintain:\n1 result is available, use up and down arrow keys to navigate.\nCancel\nOverview\nIncidents\nMaintained Projects\nRequests\nUsers\nAdvanced\nMaintained Projects\nNo projects in maintenance\nAdd project to maintenance\nuser_1148:\nYour Profile\nHome Project\nLogout\nLocations\nProjects\nSearch\nStatus Monitor\nHelp\nOpen Build Service\nOBS Manuals\nopenSUSEs OBS Portal\nReporting a Bug\nContact\nMailing List\nForums\nChat (IRC)\nTwitter\nOpen Build Service (OBS) is an openSUSE project.\nhome:Jane"
[ 2066s]      # ./spec/features/webui/projects_spec.rb:432:in `block (3 levels) in <top (required)>'

**Comment by coolo** [comment]
Very similiar failure?
```
[ 2743s]   1) Requests review for package opens a review
[ 2743s]      Failure/Error: expect(page).to have_text("Review for #{submitter.home_project} / #{package.name}")
[ 2743s]        expected to find text "Review for home:kugelblitz / package_70" in "Watchlist\nOpen Build Service > Request 1\nkugelblitz | Tasks | Home Project | Logout\nAdd Reviewer\nAdd a reviewer to request 1\nType:\nUser\nGroup\nProject\nPackage\n\n\n\n\n\nProject:\n1 result is available, use up and down arrow keys to navigate.\nPackage:\n1 result is available, use up and down arrow keys to navigate.\nComment for reviewer:\nCancel\nOverview\nRequest 1 (new)\na long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long [+]\nAdd a review\nCreated by kugelblitz now\nIn state new\nComments for request 1 (0)\nMy Decision\nRequest History\nkugelblitz created request now\na long text - a long text - a long text - a long [+]\nkugelblitz:\nYour Profile\nHome Project\nLogout\nLocations\nProjects\nSearch\nStatus Monitor\nHelp\nOpen Build Service\nOBS Manuals\nopenSUSEs OBS Portal\nReporting a Bug\nContact\nMailing List\nForums\nChat (IRC)\nTwitter\nOpen Build Service (OBS) is an openSUSE project."
[ 2743s]      # ./spec/features/webui/requests_spec.rb:181:in `block (4 levels) in <top (required)>'

**Comment by vpereira** [comment]
does it still happen @coolo ?

**Comment by coolo** [comment]
You tell me. Hard to say what flickers, but the package builds are still pretty unstable:
https://build.opensuse.org/packages/obs-server:obs-api-testsuite-rspec/job_history/OBS:Server:Unstable/SLE_15/x86_64

**Comment by coolo** [comment]
Just had it in https://build.opensuse.org/package/live_build_log/OBS:Server:Unstable:TestGithub:PR-7082/obs-server:obs-api-testsuite-rspec/SLE_15/x86_64 (now restarted):

```
[ 2391s]   1) Requests review for user opens a review and accepts it
[ 2391s]      Failure/Error: expect(page).to have_text(/Open review for\s+#{reviewer.login}/)
[ 2391s]        expected to find text matching /Open review for\s+user_1433/ in "Watchlist\nOpen Build Service > Request 1\nkugelblitz | Tasks | Home Project | Logout\nAdd Reviewer\nAdd a reviewer to request 1\nType:\nUser\nGroup\nProject\nPackage\n\nUser:\n1 result is available, use up and down arrow keys to navigate.\n\n\n\n\n\n\nComment for reviewer:\nCancel\nOverview\nRequest 1 (new)\na long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long text - a long [+]\nAdd a review\nCreated by kugelblitz now\nIn state new\nDelete home:titan\nDelete project home:titan\nComments for request 1 (0)\nMy Decision\nRequest History\nkugelblitz created request now\na long text - a long text - a long text - a long [+]\nkugelblitz:\nYour Profile\nHome Project\nLogout\nLocations\nProjects\nSearch\nStatus Monitor\nHelp\nOpen Build Service\nOBS Manuals\nopenSUSEs OBS Portal\nReporting a Bug\nContact\nMailing List\nForums\nChat (IRC)\nTwitter\nOpen Build Service (OBS) is an openSUSE project."
[ 2391s]      # ./spec/features/webui/requests_spec.rb:125:in `block (4 levels) in <top (required)>'

**Comment by vpereira** [comment]
ok thank you for spotting it, Until now, I never stumbled on that.

**Comment by hennevogel** [comment]
This is flickering hard
