### ISSUE TITLE
Flickering test: test_mbranch_and_maintenance_entire_project_request

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#6372]
From https://github.com/openSUSE/open-build-service/pull/6366 which is only generating .rubocop_todo.yml:

```
  test_mbranch_and_maintenance_entire_project_request             FAIL (12.94s)
        Expected response to be a <2XX: success>, but was a <400: Bad Request>
        Response body: <status code="attribute_save">
          <summary>/var/tmp/obsbackend20181126-654-9elqo2/data/projects/home:tom:branches:OBS_Maintained:pack2.pkg/_project.mrev: No such file or directory</summary>
        </status>
        test/functional/maintenance_test.rb:800:in `test_mbranch_and_maintenance_entire_project_request'
        test/test_helper.rb:118:in `block in __run'
        test/test_helper.rb:118:in `map'
        test/test_helper.rb:118:in `__run'
```

**Comment by coolo** [comment]
this looks like #5688

**Comment by hennevogel** [comment]
You find flickering specs on circle now.

https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests?branch=master&reporting-window=last-30-days
