### ISSUE TITLE
obs-server package failures due to flickering test (InfluxDB)

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#6474]
I've seen this frequently during the last one or two weeks

```sh
[ 1894s]   1) InfluxDB::OBS::Middleware::BackendSubscriber#call writes to InfluxDB
[ 1894s]      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
[ 1894s]        Exactly one instance should have received the following message(s) but didn't: write_point
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-support-3.8.0/lib/rspec/support.rb:97:in `block in <module:Support>'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-support-3.8.0/lib/rspec/support.rb:106:in `notify_failure'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-mocks-3.8.0/lib/rspec/mocks/error_generator.rb:327:in `notify'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-mocks-3.8.0/lib/rspec/mocks/error_generator.rb:311:in `__raise'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-mocks-3.8.0/lib/rspec/mocks/any_instance/error_generator.rb:7:in `raise_second_instance_received_message_error'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-mocks-3.8.0/lib/rspec/mocks/any_instance/recorder.rb:95:in `verify'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-mocks-3.8.0/lib/rspec/mocks/space.rb:75:in `block in verify_all'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-mocks-3.8.0/lib/rspec/mocks/space.rb:75:in `each_value'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-mocks-3.8.0/lib/rspec/mocks/space.rb:75:in `verify_all'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-mocks-3.8.0/lib/rspec/mocks.rb:45:in `verify'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/mocking_adapters/rspec.rb:23:in `verify_mocks_for_rspec'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:514:in `verify_mocks'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:508:in `run_after_example'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:273:in `block in run'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `block in run'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:604:in `block in run_around_example_hooks_for'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:342:in `call'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-rails-3.8.1/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
[ 1894s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/r[ 1883.820151] serial8250: too much work for irq4
[ 1894s] spec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
```

**Comment by ChrisBr** [comment]
Are you sure? We merged this one yesterday https://github.com/openSUSE/open-build-service/pull/6441#event-2004568571

**Comment by ChrisBr** [comment]
Anyway, I will investigate

**Comment by ChrisBr** [comment]
The problem seems to be that it runs in the background, fixed in https://github.com/openSUSE/open-build-service/pull/6469

**Comment by bgeuken** [comment]
I saw it at least yesterday already. Might be that I confuse the previous test failures with other flickering tests.

**Comment by vpereira** [comment]
@bgeuken i think it was fixed, right?

**Comment by coolo** [comment]
I haven't seen it in about 300 builds
