### ISSUE TITLE
influxdb blocks development

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6556]
This is pretty much freshly built dev container trying to run things in Rails console.

Has to cancel the command to get the following backtrace:

```
^CTraceback (most recent call last):
        13: from /usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/client.rb:58:in `block in initialize'
        12: from /usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/client.rb:66:in `stop!'
        11: from /usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/writer/async.rb:142:in `stop!'
        10: from /usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/writer/async.rb:105:in `check_background_queue'
         9: from /usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/writer/async.rb:105:in `loop'
         8: from /usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/writer/async.rb:127:in `block in check_background_queue'
         7: from /usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/writer/async.rb:148:in `write'
         6: from /usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/writer/async.rb:148:in `each'
         5: from /usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/writer/async.rb:149:in `block in write'
         4: from /usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/query/core.rb:83:in `write'
         3: from /usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/client/http.rb:26:in `post'
         2: from /usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/client/http.rb:43:in `connect_with_retry'
         1: from /usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/config.rb:92:in `next_host'
/usr/lib64/ruby/gems/2.5.0/gems/influxdb-0.6.4/lib/influxdb/config.rb:92:in `pop': Interrupt

**Comment by hennevogel** [comment]
Fix it? This is right up your alley. See #6552. I dare you :wink:

**Comment by coolo** [comment]
done:
```
--- a/src/api/config/initializers/influxdb_rails.rb
+++ b/src/api/config/initializers/influxdb_rails.rb
@@ -1,3 +1,4 @@
+if false

**Comment by hennevogel** [comment]
works for me. maybe you want to rebase?

**Comment by coolo** [comment]
the only thing that was merged afterwards are the repository pages. Hardly related.

And this problem might also be the reason you saw circleci hanging yesterday

**Comment by ChrisBr** [comment]
cc @eduardoj

**Comment by ChrisBr** [comment]
> And this problem might also be the reason you saw circleci hanging yesterday

Nope as the PR is not yet merged which was causing the hanging of CircleCI. The commit got moved to #6552.
