### ISSUE TITLE
Kiwi::Repository validations for source_path not valid when has {

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#6773]
From SLE 15 build log:

```
[ 1336s]   1) Kiwi::Repository validations for source_path not valid when has `{`
[ 1336s]      Failure/Error:
[ 1336s]        property_of do
[ 1336s]          string = sized(range(1, 199)) { string(/[\w]/) }
[ 1336s]          index = range(0, (string.length - 2))
[ 1336s]          uri_character = sized(1) { string(/[{]/) }
[ 1336s]          string[index] = uri_character
[ 1336s]          protocol + '://' + string
[ 1336s]        end.check(3) do |string|
[ 1336s]          expect(subject).not_to allow_value(string).for(:source_path)
[ 1336s]        end
[ 1336s] 
[ 1336s]      TypeError:
[ 1336s]        0 successful tests, failed on:
[ 1336s] 
[ 1336s] 
[ 1336s]        no implicit conversion from nil to integer
[ 1336s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rantly-2.0.0/lib/rantly/property.rb:54:in `rescue in check'
[ 1336s]      # /usr/lib64/obs-api/ruby/2.5.0/gems/rantly-2.0.0/lib/rantly/property.rb:30:in `check'
[ 1336s]      # ./spec/models/kiwi/repository_spec.rb:97:in `block (5 levels) in <top (required)>'
[ 1336s]      # ------------------
[ 1336s]      # --- Caused by: ---
[ 1336s]      # TypeError:
[ 1336s]      #   no implicit conversion from nil to integer
[ 1336s]      #   ./spec/models/kiwi/repository_spec.rb:95:in `[]='
[ 1336s] 
[ 1336s] Finished in 19 minutes 28 seconds (files took 9.26 seconds to load)
[ 1336s] 3782 examples, 1 failure, 33 pending
[ 1336s] 
[ 1336s] Failed examples:
[ 1336s] 
[ 1336s] rspec ./spec/models/kiwi/repository_spec.rb[1:2:1:15] # Kiwi::Repository validations for source_path not valid when has `{`
[ 1336s] 
[ 1336s] Randomized with seed 28453
[ 1336s] 
```

It looks like a flickering test

**Comment by Ana06** [comment]
She also released the previous version of Rantly.... :unamused:

**Comment by Ana06** [comment]
```
  1) Configuration#delayed_write_to_backend writes to the backend
     Failure/Error: expect(configuration).to have_received(:write_to_backend)
     
       (#<Configuration id: nil, title: "dolorem", description: "Eos autem odit voluptates.", created_at: nil, updated_at: nil, name: "cumque", registration: "allow", anonymous: true, default_access_disabled: false, allow_user_to_create_home_project: true, disallow_group_creation: false, change_password: true, hide_private_options: false, gravatar: true, enforce_project_keys: false, download_on_demand: true, download_url: nil, ymp_url: nil, bugzilla_url: nil, http_proxy: nil, no_proxy: nil, theme: nil, obs_url: "https://unconfigured.openbuildservice.org", cleanup_after_days: nil, admin_email: "unconfigured@openbuildservice.org", cleanup_empty_projects: true, disable_publish_for_branches: true, default_tracker: "bnc", api_url: nil, unlisted_projects_filter: "^home:.+", unlisted_projects_filter_description: "home projects">).write_to_backend(*(any args))
           expected: 1 time with any arguments
           received: 0 times with any arguments
```

**Comment by Ana06** [comment]
@Ana06 Related:

> ```
>   1) Configuration#delayed_write_to_backend writes to the backend
>      Failure/Error: expect(configuration).to have_received(:write_to_backend)
>      
>        (#<Configuration id: nil, title: "dolorem", description: "Eos autem odit voluptates.", created_at: nil, updated_at: nil, name: "cumque", registration: "allow", anonymous: true, default_access_disabled: false, allow_user_to_create_home_project: true, disallow_group_creation: false, change_password: true, hide_private_options: false, gravatar: true, enforce_project_keys: false, download_on_demand: true, download_url: nil, ymp_url: nil, bugzilla_url: nil, http_proxy: nil, no_proxy: nil, theme: nil, obs_url: "https://unconfigured.openbuildservice.org", cleanup_after_days: nil, admin_email: "unconfigured@openbuildservice.org", cleanup_empty_projects: true, disable_publish_for_branches: true, default_tracker: "bnc", api_url: nil, unlisted_projects_filter: "^home:.+", unlisted_projects_filter_description: "home projects">).write_to_backend(*(any args))
>            expected: 1 time with any arguments
>            received: 0 times with any arguments
> # ./spec/models/configuration_spec.rb:33:in `block (3 levels) in <top (required)>'
> ```
> 

This is not related, no Rantly test... @dmarcoux
