### ISSUE TITLE
obs_factory: staging dashboard crashes

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7153]
It crashed 3 times for me this morning and I couldn't make something out of it as there was no errbit msg related to it. But looking at the logs, this is a NotFoundError and it's filtered.

This problem is new though. I assume it's triggered as we now have required checks in the adi projects and these adi projects disappear quite regularly. If this happens in the many seconds the staging dashboard loads, you get the explosion.

```
I, [2019-03-11T10:01:32.724104 #23425]  INFO -- : [36c037c4-17dd-4d98-9e36-8f4d9613c934] [23425:331622.33] method=GET path=/project/staging_projects/openSUSE:Factory format=html controller=Webui::ObsFactory:
:StagingProjectsController action=index status=500 error='Backend::NotFoundError: <status code="404">
  <summary>project 'openSUSE:Factory:Staging:adi:16' does not exist</summary>
  <details>404 project 'openSUSE:Factory:Staging:adi:16' does not exist</details>
</status>
' duration=4519.43 view=0.00 db=902.52 params={"project"=>"openSUSE:Factory"} host=172.16.42.1 time=2769674.29 backend=2495.38 user=coolo
F, [2019-03-11T10:01:32.744593 #23425] FATAL -- : [36c037c4-17dd-4d98-9e36-8f4d9613c934] [23425:331622.35]   
F, [2019-03-11T10:01:32.744734 #23425] FATAL -- : [36c037c4-17dd-4d98-9e36-8f4d9613c934] [23425:331622.35] Backend::NotFoundError (<status code="404">
  <summary>project 'openSUSE:Factory:Staging:adi:16' does not exist</summary>
  <details>404 project 'openSUSE:Factory:Staging:adi:16' does not exist</details>
</status>
):
F, [2019-03-11T10:01:32.744780 #23425] FATAL -- : [36c037c4-17dd-4d98-9e36-8f4d9613c934] [23425:331622.35]   
F, [2019-03-11T10:01:32.744847 #23425] FATAL -- : [36c037c4-17dd-4d98-9e36-8f4d9613c934] [23425:331622.35] lib/backend/connection.rb:122:in `handle_response'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] lib/backend/connection.rb:31:in `get'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] lib/backend/connection_helper.rb:50:in `http_get'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] lib/backend/api/build_results/status.rb:51:in `failed_results'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] lib/backend/remember_location.rb:15:in `call'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] lib/backend/remember_location.rb:15:in `block in singleton_method_added'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] app/models/obs_factory/staging_project.rb:269:in `set_buildinfo'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] app/models/obs_factory/staging_project.rb:115:in `building_repositories'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] app/models/obs_factory/staging_project.rb:209:in `build_state'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] app/models/obs_factory/staging_project.rb:251:in `overall_state'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] app/presenters/obs_factory/staging_project_presenter.rb:149:in `sort_key'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] app/presenters/obs_factory/staging_project_presenter.rb:6:in `block in sort'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] app/presenters/obs_factory/staging_project_presenter.rb:6:in `each'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] app/presenters/obs_factory/staging_project_presenter.rb:6:in `sort_by'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] app/presenters/obs_factory/staging_project_presenter.rb:6:in `sort_by!'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] app/presenters/obs_factory/staging_project_presenter.rb:6:in `sort'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] app/controllers/webui/obs_factory/staging_projects_controller.rb:11:in `block (2 levels) in index'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] app/controllers/webui/obs_factory/staging_projects_controller.rb:9:in `index'
[36c037c4-17dd-4d98-9e36-8f4d9613c934] config/initializers/wrap_parameters.rb:38:in `call'

**Comment by coolo** [comment]
I guess this was fixed - it's not happening anymore
