### ISSUE TITLE
`rake docker:build` fails after recent changes

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#7303]
# Issue Description

```
rake docker:build
```

Does not complete successfully, but used to.

```
pose run --no-deps --rm frontend bundle exec rake dev:bootstrap RAILS_ENV=development
Setting up the database configuration...
Creating config/config/database.yml from config/config/database.yml.example
Setting up the application configuration...
Creating config/config/options.yml from config/config/options.yml.example
Setting up the cloud uploader
Creating config/../../dist/aws_credentials from config/../../dist/aws_credentials.example
Creating config/../../dist/ec2utils.conf from config/../../dist/ec2utils.conf.example
Creating the database...
Created database 'api_development'
Created database 'api_test'
Seeding architectures table...
rake aborted!
SocketError: Failed to open TCP connection to backend:5352 (getaddrinfo: Name or service not known)
/obs/src/api/lib/backend/connection.rb:96:in `put_or_post'
/obs/src/api/lib/backend/connection.rb:35:in `put'
/obs/src/api/lib/backend/connection_helper.rb:62:in `http_put'
/obs/src/api/lib/backend/api/server.rb:23:in `write_configuration'
/obs/src/api/lib/backend/remember_location.rb:15:in `call'
/obs/src/api/lib/backend/remember_location.rb:15:in `block in singleton_method_added'
/obs/src/api/app/models/configuration.rb:134:in `write_to_backend'
/obs/src/api/app/jobs/configuration_write_to_backend_job.rb:5:in `perform'
/obs/src/api/app/models/configuration.rb:127:in `delayed_write_to_backend'
/obs/src/api/db/seeds.rb:21:in `<top (required)>'
/obs/src/api/lib/tasks/databases.rake:121:in `block (2 levels) in <top (required)>'
/obs/src/api/lib/tasks/dev.rake:38:in `rescue in block (2 levels) in <top (required)>'
/obs/src/api/lib/tasks/dev.rake:34:in `block (2 levels) in <top (required)>'
Caused by:
ActiveRecord::NoDatabaseError: Unknown database 'api_development'
/obs/src/api/lib/tasks/dev.rake:35:in `block (2 levels) in <top (required)>'
Caused by:
Mysql2::Error: Unknown database 'api_development'
/obs/src/api/lib/tasks/dev.rake:35:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
docker-compose stop
Stopping openbuildservice_db_1 ... 
Command failed with status (1): [docker-compose run --no-deps --rm frontend...]
/home/travis/build/openSUSE/openSUSE-release-tools/.open-build-service/Rakefile:34:in `block (2 levels) in <top (required)>'
/home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => docker:build
(See full trace by running task with --trace)
The command "./dist/ci/docker-compose-obs" failed and exited with 1 during .
```

Expected Result
============

Success.

How to Reproduce
===============
1. execute `rake docker:build`

Further Information
===============

Broke our CI which includes full log output: openSUSE/openSUSE-release-tools#1943.

**Comment by jberry-suse** [comment]
I performed a `git bisect` after verifying that a2277380ada24382282783a1c6a09d789e14fc86 passed script and `HEAD` fails.

```
$ git bisect start HEAD a2277380ada24382282783a1c6a09d789e14fc86 --
Bisecting: 11 revisions left to test after this (roughly 4 steps)
[602eb085aa399caa5e83e27b029fcca6cc26f0d8] Merge pull request #7290 from coolo/remove_cron
$ git bisect run ./docker-test.sh
```

Where `docker-test.sh` is the following (could be optimized, but ensuring clean starting point):

```bash
#!/bin/bash

docker system prune --force
images=($(docker images --filter=reference='openbuildservice/*' --quiet))
if [ ${#images[@]} -gt 0 ] ; then
  docker rmi ${images[@]}
fi
rake docker:build
```

With the following result:

```
f2395bb7619b2ec64cb07b6e977711dceb020479 is the first bad commit
commit f2395bb7619b2ec64cb07b6e977711dceb020479
Author: depfu[bot] <depfu[bot]@users.noreply.github.com>
Date:   Fri Mar 29 05:07:07 2019 +0000

    Update all of rails to version 5.2.3

:040000 040000 16ef6b9974942e1d07d3e6f4c63ccf4f827e887f a72e57e20fa5b711287cbb034c68dd662ad5b638 M      src
bisect run success
```

This also fits within timeframe of < 24 hours since it passed in our CI.

**Comment by jberry-suse** [comment]
Would be beneficial if a test were added for this in OBS CI since various things have caused this to break repeatedly over last year.

**Comment by coolo** [comment]
Looking at rails changelog, I would say this is caused by "Seed database with inline ActiveJob job adapter #34953", i.e. db:seed will now actually write into the backend and no longer trigger an active job.

**Comment by coolo** [comment]
The fix could be as plain as:
```
--- a/Rakefile
+++ b/Rakefile
@@ -30,8 +30,7 @@ EOF"
       # Build the minitest container on top of that
       sh 'docker-compose -f docker-compose.yml -f docker-compose.minitest.yml build minitest'
       # Bootstrap the app
-      sh 'docker-compose up -d db'
-      sh 'docker-compose run --no-deps --rm frontend bundle exec rake dev:bootstrap RAILS_ENV=development'
+      sh 'docker-compose run --rm frontend bundle exec rake dev:bootstrap RAILS_ENV=development'
     ensure
       sh 'docker-compose stop'
     end
```

**Comment by coolo** [comment]
And I briefly looked into CIing that task. But that doesn't fly - circleci does offer only remote docker builds, which makes mounting the bash files impossible.

**Comment by hennevogel** [comment]
@coolo uh, that sounds nasty and possible source of many failures for people with more elaborate backends. 

@jberry-suse we are not going to test against your misuse of our dev-environment in your CI, sorry. Lets talk how else you can do this and why rake docker:build exists.

**Comment by jberry-suse** [comment]
> misuse of our dev-environment in your CI

You are testing that your dev environment rake task works, nothing more. Also absolutely no misuse.

**Comment by hennevogel** [comment]
Running tests against a development build instance of OBS is awesome. I also understand your need to do this. But using the **developer** environment for this is not so optimal. Like I said, let's talk about how you can "run tests against a development build instance of OBS."

**Comment by jberry-suse** [comment]
> "run tests against a development build instance of OBS."

That's what we are doing.
