### ISSUE TITLE
Crash in staging project selection

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7349]
unstaging a request without body is not validated and causes a crash:

```
I, [2019-04-05T18:11:12.207140 #13395]  INFO -- : [e76c17ce-3c18-44a7-b72b-d7960720c3de] [13395:12350.80] method=DELETE path=/staging/openSUSE:Factory/staging_projects/openSUSE:Factory:Staging:C/staged_requests format=xml 
controller=Staging::StagedRequestsController action=destroy status=500 error='NoMethodError: undefined method `elements' for {}:Hash' duration=115.02 view=0.00 db=29.28 params={"staging_workflow_project"=>"openSUSE:Factory
", "staging_project_name"=>"openSUSE:Factory:Staging:C"} host=149.44.161.60 time=435536.26 backend=0 user=coolo
F, [2019-04-05T18:11:12.214487 #13395] FATAL -- : [e76c17ce-3c18-44a7-b72b-d7960720c3de] [13395:12350.80]   
F, [2019-04-05T18:11:12.214569 #13395] FATAL -- : [e76c17ce-3c18-44a7-b72b-d7960720c3de] [13395:12350.80] NoMethodError (undefined method `elements' for {}:Hash):
F, [2019-04-05T18:11:12.214603 #13395] FATAL -- : [e76c17ce-3c18-44a7-b72b-d7960720c3de] [13395:12350.80]   
F, [2019-04-05T18:11:12.214681 #13395] FATAL -- : [e76c17ce-3c18-44a7-b72b-d7960720c3de] [13395:12350.80] app/controllers/staging/staged_requests_controller.rb:57:in `request_numbers'
[e76c17ce-3c18-44a7-b72b-d7960720c3de] app/controllers/staging/staged_requests_controller.rb:37:in `destroy'
[e76c17ce-3c18-44a7-b72b-d7960720c3de] config/initializers/wrap_parameters.rb:38:in `call'

**Comment by coolo** [comment]
Ah, the xml doesn't matter - I forgot to post a body :)
