### ISSUE TITLE
Flickering requests

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7533]
```
[ 2214s]   1) Packages existing requests see a request
[ 2214s]      Failure/Error: expect(page).to have_css('table#all_requests_table tr', count: 1)
[ 2214s]        expected to find visible css "table#all_requests_table tr" 1 time, found 2 matches: "Created Source Target Requester Type Priority", "now source_project / package_764 home:package_test_user / test_package user_1047 submit moderate"
[ 2214s]      # ./spec/features/webui/packages_spec.rb:140:in `block (3 levels) in <top (required)>'
[ 2214s]

**Comment by eduardoj** [comment]
This also appeared yesterday, in another line of the test:
```
Failure/Error: expect(page).to have_css('table#all_requests_table tr', count: 1)
  expected to find visible css "table#all_requests_table tr" 1 time, found 2 matches: "Created Source Target Requester Type Priority", "now source_project / package_206 home:package_test_user / test_package user_918 submit moderate"
./spec/features/webui/packages_spec.rb:94:in `block (3 levels) in <top (required)>'
```
