### ISSUE TITLE
Blinking minitest test_submit_requests_from_remote

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7670]
Looks like the code is buggy - but only sometimes :)

```
[3f5f4733-ba12-41cd-8d97-d27b308045a5] [backend_sync] [230:81.52] Saved Package LocalProject/pack2.linked
[3f5f4733-ba12-41cd-8d97-d27b308045a5] [230:81.52]    (0.2ms)  RELEASE SAVEPOINT active_record_1
[3f5f4733-ba12-41cd-8d97-d27b308045a5] [230:81.52]   BackendPackage Destroy (0.2ms)  DELETE FROM `backend_packages` WHERE `backend_packages`.`package_id` = 1044768003
[3f5f4733-ba12-41cd-8d97-d27b308045a5] [230:81.52] [backend] GET: /source/LocalProject/pack2.linked
[3f5f4733-ba12-41cd-8d97-d27b308045a5] [230:81.52] Completed 500 Internal Server Error in 168ms (Views: 0.5ms | ActiveRecord: 11.2ms | Backend: 45.5ms)
[3f5f4733-ba12-41cd-8d97-d27b308045a5] [230:81.53]   
[3f5f4733-ba12-41cd-8d97-d27b308045a5] [230:81.53] AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".):
[3f5f4733-ba12-41cd-8d97-d27b308045a5] [230:81.53]   
[3f5f4733-ba12-41cd-8d97-d27b308045a5] [230:81.53] app/controllers/application_controller.rb:329:in `block (2 levels) in render_error'
[3f5f4733-ba12-41cd-8d97-d27b308045a5] app/controllers/application_controller.rb:328:in `render_error'
[3f5f4733-ba12-41cd-8d97-d27b308045a5] app/controllers/application_controller.rb:212:in `block in <class:ApplicationController>'
[3f5f4733-ba12-41cd-8d97-d27b308045a5] config/initializers/wrap_parameters.rb:38:in `call'
[3f5f4733-ba12-41cd-8d97-d27b308045a5] test/test_helper.rb:172:in `process'
[3f5f4733-ba12-41cd-8d97-d27b308045a5] test/functional/interconnect_test.rb:416:in `test_submit_requests_from_remote'

**Comment by hennevogel** [comment]
You find flickering specs on circle now.

https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests?branch=master&reporting-window=last-30-days
