### ISSUE TITLE
2.5.4: Removing repositories causes exception: no such method

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#790]
On obs-server 2.5.4/openSUSE 13.1 x86_64, changing the prjmeta from

```
<project name="DEB">
  <title/>
  <description/>
  <person userid="jengelh" role="bugowner"/>
  <person userid="jengelh" role="maintainer"/>
  <build>
    <enable/>
    <disable arch="x86_64"/>
  </build>
  <publish>
    <disable/>
  </publish>
  <debuginfo>
    <enable/>
  </debuginfo>
  <repository name="openSUSE_13.1">
    <path project="openSUSE.org:windows:mingw:win32" repository="openSUSE_13.1"/>
    <path project="openSUSE.org:windows:mingw:win64" repository="openSUSE_13.1"/>
    <path project="openSUSE.org:openSUSE:13.1" repository="standard"/>
    <arch>x86_64</arch>
    <arch>i586</arch>
  </repository>
  <repository name="Windows_x86"/>
  <repository name="Windows_x64"/>
</project>
```

to

```
<project name="DEB">
  <title/>
  <description/>
  <person userid="jengelh" role="bugowner"/>
  <person userid="jengelh" role="maintainer"/>
  <build>
    <enable/>
    <disable arch="x86_64"/>
  </build>
  <publish>
    <disable/>
  </publish>
  <debuginfo>
    <enable/>
  </debuginfo>
  <repository name="openSUSE_13.1">
    <path project="openSUSE.org:windows:mingw:win32" repository="openSUSE_13.1"/>
    <path project="openSUSE.org:windows:mingw:win64" repository="openSUSE_13.1"/>
    <path project="openSUSE.org:openSUSE:13.1" repository="standard"/>
    <arch>x86_64</arch>
    <arch>i586</arch>
  </repository>
</project>
```

that is, removing the Windows repos, causes error 500 being reported via osc:

```
Sending meta data...
BuildService API error: 500
Try again? ([y/N]): 
```

Bad point 1: it just says 500 without an explanation.
/srv/obs/www/api/log/production.log:

```
[402decdb-06b0-4983-97ce-7e00c4dbbe48] [5371:8430.87] Started GET "/monitor/events?range=24&arch=x86_64" for 10.5.5.218 at 2014-09-22 15:33:10 +0200
[402decdb-06b0-4983-97ce-7e00c4dbbe48] [5371:8430.87] Processing by Webui::MonitorController#events as JSON
[402decdb-06b0-4983-97ce-7e00c4dbbe48] [5371:8430.87]   Parameters: {"range"=>"24", "arch"=>"x86_64"}
[402decdb-06b0-4983-97ce-7e00c4dbbe48] [5371:8430.87] Authenticated request to "/monitor/events?range=24&arch=x86_64" from Admin
[402decdb-06b0-4983-97ce-7e00c4dbbe48] [5371:8430.89] Completed 200 OK in 20ms (Views: 7.6ms | ActiveRecord: 1.0ms | Backend: 0.0ms | XML: 0.0ms)
[57656027-d084-4744-b1ce-5857b9737d11] [5371:8431.94] Started PUT "/source/DEB/_meta" for 46.4.84.70 at 2014-09-22 15:33:11 +0200
[57656027-d084-4744-b1ce-5857b9737d11] [5371:8431.94] Processing by SourceController#update_project_meta as XML
[57656027-d084-4744-b1ce-5857b9737d11] [5371:8431.94]   Parameters: {"project"=>"DEB"}
[57656027-d084-4744-b1ce-5857b9737d11] [5371:8431.94] Can't verify CSRF token authenticity
[57656027-d084-4744-b1ce-5857b9737d11] [5371:8431.95]   Rendered status.xml.builder (0.3ms)
[57656027-d084-4744-b1ce-5857b9737d11] [5371:8431.95] Completed 401 Unauthorized in 7ms (Views: 1.0ms | ActiveRecord: 0.8ms | Backend: 0.0ms | XML: 0.0ms)
[4abdd6db-c9a6-4de1-921a-c29ce699e1e9] [5371:8432.03] Started PUT "/source/DEB/_meta" for 46.4.84.70 at 2014-09-22 15:33:11 +0200
[4abdd6db-c9a6-4de1-921a-c29ce699e1e9] [5371:8432.04] Processing by SourceController#update_project_meta as XML
[4abdd6db-c9a6-4de1-921a-c29ce699e1e9] [5371:8432.04]   Parameters: {"project"=>"DEB"}
[4abdd6db-c9a6-4de1-921a-c29ce699e1e9] [5371:8432.04] Can't verify CSRF token authenticity
[4abdd6db-c9a6-4de1-921a-c29ce699e1e9] [5371:8432.16] Completed 500 Internal Server Error in 127ms
[4abdd6db-c9a6-4de1-921a-c29ce699e1e9] [5371:8432.17] 
NoMethodError (undefined method `repositories' for nil:NilClass):
  app/controllers/source_controller.rb:972:in `private_remove_repositories'
  app/controllers/source_controller.rb:966:in `private_check_and_remove_repositories'
  app/controllers/source_controller.rb:531:in `update_project_meta'
  actionpack (4.0.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.0.3) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.0.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.0.3) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (4.0.3) lib/active_support/callbacks.rb:473:in `_run__1669586411855404430__process_action__callbacks'
  activesupport (4.0.3) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.3) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (4.0.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.0.3) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.0.3) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.3) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.0.3) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  activerecord (4.0.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.0.3) lib/abstract_controller/base.rb:136:in `process'
  actionpack (4.0.3) lib/abstract_controller/rendering.rb:44:in `process'
  actionpack (4.0.3) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.0.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.0.3) lib/action_controller/metal.rb:231:in `block in action'
  actionpack (4.0.3) lib/action_dispatch/routing/route_set.rb:80:in `call'
  actionpack (4.0.3) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  actionpack (4.0.3) lib/action_dispatch/routing/route_set.rb:48:in `call'
  actionpack (4.0.3) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.3) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.0.3) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.3) lib/action_dispatch/routing/route_set.rb:680:in `call'
  config/initializers/wrap_parameters.rb:41:in `call'
  hoptoad_notifier (2.4.11) lib/hoptoad_notifier/rack.rb:27:in `call'
  rack (1.5.2) lib/rack/deflater.rb:25:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.0.3) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.3) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  activerecord (4.0.3) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  actionpack (4.0.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.3) lib/active_support/callbacks.rb:373:in `_run__2147208160468642157__call__callbacks'
  activesupport (4.0.3) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.3) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.3) lib/active_support/tagged_logging.rb:67:in `block in tagged'
  activesupport (4.0.3) lib/active_support/tagged_logging.rb:25:in `tagged'
  activesupport (4.0.3) lib/active_support/tagged_logging.rb:67:in `tagged'
  railties (4.0.3) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.0.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.3) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  hoptoad_notifier (2.4.11) lib/hoptoad_notifier/user_informer.rb:12:in `call'
  railties (4.0.3) lib/rails/engine.rb:511:in `call'
  railties (4.0.3) lib/rails/application.rb:97:in `call'
  railties (4.0.3) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.33) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  passenger (4.0.33) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.33) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.33) lib/phusion_passenger/request_handler.rb:440:in `block (3 levels) in start_threads'
```

**Comment by bgeuken** [comment]
Can't reproduce this anymore.

=> Solved
