### ISSUE TITLE
rake task dev:development_testdata:create is broken

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#8231]
trying to run it in the development environment it is broken:

```
frontend@ec63dd772fb2:/obs/src/api> rake dev:development_testdata:create
Dropped database 'api_development'
Dropped database 'api_test'
Created database 'api_development'
Created database 'api_test'
Seeding architectures table...
Seeding roles table...
Seeding users table...
Seeding roles_users table...
Seeding static_permissions table...
Seeding static permissions for admin role in roles_static_permissions table...
Seeding static permissions for maintainer role in roles_static_permissions table...
Seeding static permissions for reader role in roles_static_permissions table...
Seeding static permissions for downloader role in roles_static_permissions table...
Seeding attrib_namespaces table...
Seeding attrib_types table...
Seeding issue trackers ...
rake aborted!
ActionView::Template::Error: wrong number of arguments (given 0, expected 1+)
/obs/src/api/app/helpers/flag_helper.rb:166:in `block in render'
/obs/src/api/app/helpers/flag_helper.rb:164:in `each'
/obs/src/api/app/helpers/flag_helper.rb:164:in `render'
/obs/src/api/app/views/models/_project.xml.builder:23:in `block (2 levels) in _app_views_models__project_xml_builder___1205233474342540696_46973085762620'
/obs/src/api/app/views/models/_project.xml.builder:5:in `block in _app_views_models__project_xml_builder___1205233474342540696_46973085762620'
/obs/src/api/app/views/models/_project.xml.builder:1:in `new'
/obs/src/api/app/views/models/_project.xml.builder:1:in `_app_views_models__project_xml_builder___1205233474342540696_46973085762620'
/obs/src/api/app/mixins/can_render_model.rb:8:in `render_xml'
/obs/src/api/app/models/project.rb:687:in `block in to_axml'
/obs/src/api/app/models/project.rb:685:in `to_axml'
/obs/src/api/app/models/project.rb:603:in `write_to_backend'
/obs/src/api/spec/factories/project.rb:37:in `block (3 levels) in <top (required)>'
/obs/src/api/lib/tasks/dev.rake:235:in `block (3 levels) in <top (required)>'

Caused by:
ArgumentError: wrong number of arguments (given 0, expected 1+)
/obs/src/api/app/helpers/flag_helper.rb:166:in `block in render'
/obs/src/api/app/helpers/flag_helper.rb:164:in `each'
/obs/src/api/app/helpers/flag_helper.rb:164:in `render'
/obs/src/api/app/views/models/_project.xml.builder:23:in `block (2 levels) in _app_views_models__project_xml_builder___1205233474342540696_46973085762620'
/obs/src/api/app/views/models/_project.xml.builder:5:in `block in _app_views_models__project_xml_builder___1205233474342540696_46973085762620'
/obs/src/api/app/views/models/_project.xml.builder:1:in `new'
/obs/src/api/app/views/models/_project.xml.builder:1:in `_app_views_models__project_xml_builder___1205233474342540696_46973085762620'
/obs/src/api/app/mixins/can_render_model.rb:8:in `render_xml'
/obs/src/api/app/models/project.rb:687:in `block in to_axml'
/obs/src/api/app/models/project.rb:685:in `to_axml'
/obs/src/api/app/models/project.rb:603:in `write_to_backend'
/obs/src/api/spec/factories/project.rb:37:in `block (3 levels) in <top (required)>'
/obs/src/api/lib/tasks/dev.rake:235:in `block (3 levels) in <top (required)>'
Tasks: TOP => dev:development_testdata:create
(See full trace by running task with --trace)
```

**Comment by vpereira** [comment]
fixed with https://github.com/openSUSE/open-build-service/pull/8250

**Comment by coolo** [comment]
suprising

**Comment by dmarcoux** [comment]
It's still broken

**Comment by eduardoj** [comment]
This issue does not happen anymore since a while ago.
