### ISSUE TITLE
Can't create projects on build-test

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8623]
I wanted to get back to test staging workflow, but I'm blocked by this issue - is there some migration missing?

```
I, [2019-10-28T10:08:05.243033 #18557]  INFO -- : [f3ab4478-f70c-4216-af3c-76882e0ec30b] [18557:99349.01] method=PUT path=/source/openSUSE:Factory:Staging:adi:217/_meta format=xml controller=SourceProjectMetaController action=update status=500 error='ThinkingSphinx::SphinxError: index 'project_core' does not support INSERT (enabled=1) - REPLACE INTO project_core (id, `name`, `title`, `description`, `sphinx_internal_id`, `sphinx_internal_class`, `sphinx_deleted`, `project_id`, `attrib_type_ids`, `issue_ids`, `linked_count`, `activity_index`, `links_to_other`, `is_devel`, `updated_at`) VALUES (1629, 'openSUSE:Factory:Staging:adi:217', '', '', 407, 'Project', 0, 407, (), (), 0, 0, 0, 0, 0)' duration=142.14 view=0.00 db=77.51 params={"project"=>"openSUSE:Factory:Staging:adi:217"} host=149.44.161.60 time=2807238.56 backend=0 user=coolo
F, [2019-10-28T10:08:05.249137 #18557] FATAL -- : [f3ab4478-f70c-4216-af3c-76882e0ec30b] [18557:99349.02]   
F, [2019-10-28T10:08:05.249213 #18557] FATAL -- : [f3ab4478-f70c-4216-af3c-76882e0ec30b] [18557:99349.02] ThinkingSphinx::SphinxError (index 'project_core' does not support INSERT (enabled=1) - REPLACE INTO project_core (id, `name`, `title`, `description`, `sphinx_internal_id`, `sphinx_internal_class`, `sphinx_deleted`, `project_id`, `attrib_type_ids`, `issue_ids`, `linked_count`, `activity_index`, `links_to_other`, `is_devel`, `updated_at`) VALUES (1629, 'openSUSE:Factory:Staging:adi:217', '', '', 407, 'Project', 0, 407, (), (), 0, 0, 0, 0, 0)):
F, [2019-10-28T10:08:05.249249 #18557] FATAL -- : [f3ab4478-f70c-4216-af3c-76882e0ec30b] [18557:99349.02]   
F, [2019-10-28T10:08:05.249289 #18557] FATAL -- : [f3ab4478-f70c-4216-af3c-76882e0ec30b] [18557:99349.02] app/mixins/populate_sphinx.rb:5:in `populate_sphinx'
[f3ab4478-f70c-4216-af3c-76882e0ec30b] app/models/project/update_from_xml_command.rb:41:in `run'
[f3ab4478-f70c-4216-af3c-76882e0ec30b] app/models/project.rb:585:in `update_from_xml!'

**Comment by krauselukas** [comment]
Hi @coolo we changed something in our Thinking Sphinx setup which requires to rebuild the indexes. Depending on the amount of packages and projects, this can take a while.

Please see https://github.com/openSUSE/open-build-service/blob/e66ae62f830eae0e1936b7e6f4b598f06c83ccd4/ReleaseNotes-2.11#L34

For now this needs to be done manually, but we will work on it.

**Comment by coolo** [comment]
Note that the instructions in the releasenotes most likely miss that this will break your deployment if done as root
