### ISSUE TITLE
Crash when deleting target project before the staging projects

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8729]
This happens in the staging plugin test suite, I don't think it's a big issue in reality. Deleting a 

```
I, [2019-11-18T10:23:46.615292 #1]  INFO -- : [6df47ca2-3327-4211-9ec4-cce9c323ae24] [1:0.31] method=DELETE path=/source/openSUSE:Factory:Staging:B format=xml controller=SourceProjectController action=delete status=500 error='NoMethodError: undefined method `name' for nil:NilClass' duration=308.95 view=0.00 db=25.00 params={"force"=>"1", "project"=>"openSUSE:Factory:Staging:B"} host=172.21.0.9 time=7683441.60 backend=0 user=Admin
F, [2019-11-18T10:23:46.618617 #1] FATAL -- : [6df47ca2-3327-4211-9ec4-cce9c323ae24] [1:0.31]   
F, [2019-11-18T10:23:46.618783 #1] FATAL -- : [6df47ca2-3327-4211-9ec4-cce9c323ae24] [1:0.31] NoMethodError (undefined method `name' for nil:NilClass):
F, [2019-11-18T10:23:46.618878 #1] FATAL -- : [6df47ca2-3327-4211-9ec4-cce9c323ae24] [1:0.31]   
F, [2019-11-18T10:23:46.618958 #1] FATAL -- : [6df47ca2-3327-4211-9ec4-cce9c323ae24] [1:0.31] app/models/staging/workflow.rb:57:in `write_to_backend'
[6df47ca2-3327-4211-9ec4-cce9c323ae24] app/models/concerns/staging_project.rb:242:in `update_staging_workflow_on_backend'
[6df47ca2-3327-4211-9ec4-cce9c323ae24] app/controllers/source_project_controller.rb:73:in `delete'
[6df47ca2-3327-4211-9ec4-cce9c323ae24] config/initializers/wrap_parameters.rb:38:in `call'
```

The API requests leading to this are (I filtered out the irrelevant ones):

```
172.21.0.9 - - [18/Nov/2019:10:23:33 UTC] "PUT /group/factory-staging HTTP/1.1" 200 53
172.21.0.9 - - [18/Nov/2019:10:23:34 UTC] "PUT /source/openSUSE:Factory/_meta HTTP/1.1" 200 53
172.21.0.9 - - [18/Nov/2019:10:23:34 UTC] "POST /staging/openSUSE:Factory/workflow HTTP/1.1" 200 53
172.21.0.9 - - [18/Nov/2019:10:23:38 UTC] "PUT /source/openSUSE:Factory:Staging:B/_meta HTTP/1.1" 200 53
172.21.0.9 - - [18/Nov/2019:10:23:39 UTC] "PUT /source/openSUSE:Factory:Staging:B/_project/_frozenlinks?meta=1 HTTP/1.1" 200 167
172.21.0.9 - - [18/Nov/2019:10:23:39 UTC] "GET /source/openSUSE:Factory:Staging:B/_meta HTTP/1.1" 200 83
172.21.0.9 - - [18/Nov/2019:10:23:41 UTC] "POST /request?cmd=create HTTP/1.1" 200 379
172.21.0.9 - - [18/Nov/2019:10:23:42 UTC] "GET /staging/openSUSE:Factory/staging_projects/openSUSE:Factory:Staging:B?requests=1&status=1 HTTP/1.1" 200 334
172.21.0.9 - - [18/Nov/2019:10:23:43 UTC] "POST /staging/openSUSE:Factory/staging_projects/openSUSE:Factory:Staging:B/staged_requests HTTP/1.1" 200 53
172.21.0.9 - - [18/Nov/2019:10:23:44 UTC] "DELETE /source/openSUSE:Factory?force=1 HTTP/1.1" 200 53
172.21.0.9 - - [18/Nov/2019:10:23:46 UTC] "DELETE /source/openSUSE:Factory:Staging:B?force=1 HTTP/1.1" 500 131
```

I assume the deletion of openSUSE:Factory should have cleared the staging workflow - but didn't.

**Comment by coolo** [comment]
Easy to replicate in production:

- created home:coolo:justforfun -
- created a staging workflow for it
- deleting home:coolo:justforfun
- delete left over home:coolo:justforfun:Staging:B:

https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5dd27674df0467000cee3cda
