### ISSUE TITLE
ThinkingSphinx::SphinxError: package_core does not support INSERT

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#8830]
Package creation fails for some nondescript reason.

```
# create new package by way of pkg -e
osc meta pkg -e home:jengelh:unspec/newpackagetest
<edit>
Sending meta data...
BuildService API error: 500
Try again? ([y/N]):
```

Result in `/srv/www/obs/api/log/production.log`:
```
I, [2019-12-03T02:32:45.249938 #610]  INFO -- : [66830b25-999c-4e89-8e6a-9ebbe654ef89] [610:47.87] method=GET path=/source/home:jengelh:unspec/newpackagetest/_meta format=xml controller=SourceProjectPackageMetaController action=show status=401 duration=5.27 view=1.01 db=0.54 params={"project"=>"home:jengelh:unspec", "package"=>"newpackagetest"} host=2a01:4f8:10b:45d8::f8 time=550361.22 backend=0 user=jengelh
I, [2019-12-03T02:32:45.342520 #610]  INFO -- : [a5a542ae-f5c0-464b-8614-a5fe3f533fbb] [610:47.97] method=GET path=/source/home:jengelh:unspec/newpackagetest/_meta format=xml controller=SourceProjectPackageMetaController action=show status=404 duration=74.95 view=0.84 db=4.50 params={"project"=>"home:jengelh:unspec", "package"=>"newpackagetest"} host=2a01:4f8:10b:45d8::f8 time=550361.24 backend=0 user=jengelh
W, [2019-12-03T02:32:48.514147 #610]  WARN -- : [d7779b9c-9d43-4dea-9596-57903b14f1b9] [610:51.14] Can't verify CSRF token authenticity.
I, [2019-12-03T02:32:48.521107 #610]  INFO -- : [d7779b9c-9d43-4dea-9596-57903b14f1b9] [610:51.14] method=PUT path=/source/home:jengelh:unspec/newpackagetest/_meta format=xml controller=SourceProjectPackageMetaController action=update status=401 duration=6.90 view=0.87 db=0.54 params={"project"=>"home:jengelh:unspec", "package"=>"newpackagetest"} host=2a01:4f8:10b:45d8::f8 time=550364.49 backend=0 user=jengelh
W, [2019-12-03T02:32:48.538175 #610]  WARN -- : [ab7d083e-af5b-49cc-bf43-4ca6527659fa] [610:51.16] Can't verify CSRF token authenticity.
I, [2019-12-03T02:32:48.695509 #610]  INFO -- : [ab7d083e-af5b-49cc-bf43-4ca6527659fa] [610:51.32] method=PUT path=/source/home:jengelh:unspec/newpackagetest/_meta format=xml controller=SourceProjectPackageMetaController action=update status=500 error='ThinkingSphinx::SphinxError: index 'package_core' does not support INSERT (enabled=1) - REPLACE INTO package_core (id, `name`, `title`, `description`, `sphinx_internal_id`, `sphinx_internal_class`, `sphinx_deleted`, `project_id`, `attrib_type_ids`, `issue_ids`, `linked_count`, `activity_index`, `links_to_other`, `is_devel`, `updated_at`) VALUES (13980, 'newpackagetest', 'xyztitle', '', 3495, 'Package', 0, 9, (), (), 0, 20.0, 0, 0, 1575336768)' duration=157.22 view=0.00 db=13.73 params={"project"=>"home:jengelh:unspec", "package"=>"newpackagetest"} host=2a01:4f8:10b:45d8::f8 time=550364.51 backend=43.63 user=jengelh
F, [2019-12-03T02:32:48.700148 #610] FATAL -- : [ab7d083e-af5b-49cc-bf43-4ca6527659fa] [610:51.32]   
F, [2019-12-03T02:32:48.700278 #610] FATAL -- : [ab7d083e-af5b-49cc-bf43-4ca6527659fa] [610:51.32] ThinkingSphinx::SphinxError (index 'package_core' does not support INSERT (enabled=1) - REPLACE INTO package_core (id, `name`, `title`, `description`, `sphinx_internal_id`, `sphinx_internal_class`, `sphinx_deleted`, `project_id`, `attrib_type_ids`, `issue_ids`, `linked_count`, `activity_index`, `links_to_other`, `is_devel`, `updated_at`) VALUES (13980, 'newpackagetest', 'xyztitle', '', 3495, 'Package', 0, 9, (), (), 0, 20.0, 0, 0, 1575336768)):
F, [2019-12-03T02:32:48.700304 #610] FATAL -- : [ab7d083e-af5b-49cc-bf43-4ca6527659fa] [610:51.32]   
F, [2019-12-03T02:32:48.700334 #610] FATAL -- : [ab7d083e-af5b-49cc-bf43-4ca6527659fa] [610:51.32] app/mixins/populate_sphinx.rb:5:in `populate_sphinx'
[ab7d083e-af5b-49cc-bf43-4ca6527659fa] app/models/package.rb:776:in `block in update_from_xml'
[ab7d083e-af5b-49cc-bf43-4ca6527659fa] app/models/package.rb:740:in `update_from_xml'
[ab7d083e-af5b-49cc-bf43-4ca6527659fa] app/controllers/source_project_package_meta_controller.rb:55:in `update'
[ab7d083e-af5b-49cc-bf43-4ca6527659fa] config/initializers/wrap_parameters.rb:38:in `call'
I, [2019-12-03T02:32:49.146537 #173]  INFO -- : [ActiveJob] [173:0.00] Enqueued CreateProjectLogEntryJob (Job ID: 88553399-1d3e-47e2-b12f-14e4c8a519d7) to DelayedJob(project_log_rotate) with arguments: {"project"=>"home:jengelh:unspec", "package"=>"newpackagetest", "sender"=>"jengelh"}, "2019-12-03 01:32:49 UTC", "Event::CreatePackage"
```

Additional info
============

Updating to the newest snapshot does not cure the problem, i.e. it occurs with installed b740a8 too.

```
zypper dup --no-r
<installs obs-server-2.11~alpha.20191202T144557.b740a8ba99-lp151.9285.2.noarch>
<follow /usr/share/doc/packages/obs-server/README.UPDATERS>
<restart machine>
```

**Comment by coolo** [comment]
https://github.com/openSUSE/open-build-service/blob/master/ReleaseNotes-2.11#L34 done?

**Comment by jengelh** [comment]
Thanks for pointing that out. I did not expect update instructions to be in two different files.

The ts:rebuild jobs starts a process `/usr/bin/searchd --pidfile --config /srv/www/obs/api/config/production.sphinx.conf`, which systemd unit would launch this on startup? (Because it does not run after boot.) The `searchd.service` would run a different command, `ExecStart={ path=/usr/bin/searchd ; argv[]=/usr/bin/searchd --nodetach --config /etc/sphinx/sphinx.conf ; ignore_errors=no ; start_time=[Tue 2019-12-03 09:19:46 CET] ; stop_time=[Tue 2019-12-03 09:19:46 CET] ; pid=822 ; code=exited ; status=1 }` and fails to run because that is a different config.

**Comment by hennevogel** [comment]
> which systemd unit would launch this on startup?

`obs-sphinx.service`
