### ISSUE TITLE
rebuildpacs: can't cope with huge buildinfo for unresolvable packages

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#8924]
installation-images-extras is a nasty piece - with a huge list of potential 'uinresolvables, nothing provides'

every now and then (since recently, so I assume somewhat also an OBS change!?!) the rebuild trigger bot fails with:

```
Traceback (most recent call last):
  File "./project-installcheck.py", line 304, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 261, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 284, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 422, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 1123, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "./project-installcheck.py", line 300, in do_check
    self.tool.check(project, opts.repo)
  File "./project-installcheck.py", line 55, in check
    self.check_pra(project, repository, arch)
  File "./project-installcheck.py", line 215, in check_pra
    subpacks, build_deps = self.check_leaf_package(project, repository, arch, package)
  File "./project-installcheck.py", line 268, in check_leaf_package
    root = ET.parse(http_GET(url)).getroot()
  File "src/lxml/etree.pyx", line 3467, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1860, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1880, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1775, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1187, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "https://api.opensuse.org/build/openSUSE:Factory/standard/x86_64/installation-images-extras/_buildinfo", line 3
lxml.etree.XMLSyntaxError: xmlSAX2Characters: huge text node, line 3, column 10003825
[script-executor] Script completed with exit code: 1.
```

Today when I checked, I got 345MiB of raw xml data from the API here, in the form of (cutting down of course, not pasting all 345MB)

```
<arch>x86_64</arch>
  <error>unresolvable: nothing provides debuginfo(build-id) = 1bcdd2e76c5b812c1a0d29559c6521ed5f26bfb4 needed by installation-images-debuginfodeps-openSUSE, (got version 7db8ee0efb3899d8ca9e6b4dcf1bd31fb6eb38cb provided by vala-panel-extras-volume-debuginfo), (got version 863408ded52ae02987afd6720900970ecd486070 provided by vala-panel-extras-battery-debuginfo), (got version 588187903930f78d98745592d92d1dc431ef7bda provided by vala-panel-plugin-sntray-debuginfo), (got version d1f8274bb2150d2bed63ee9fcc29855d5d81905b provided by vala-panel-extras-xkb-debuginfo), (got version 42e3b7fde196b8f20babc8b53272d091314f8ffa provided by vala-panel-extras-weather-debuginfo),
```

When I manually recover the i-i stack, the rebuildpacs gets back to working normally

**Comment by DimStar77** [comment]
Just to add: OBS Web UI can't cope with its produced XML either (or the browsers receiving the web page). At the time when this happens (so when i-i needs a rebuild and i-i-extras is 'unresolvable' it is literally impossible to load the project monitor (the unresolvable… text is loaded as 'tooltip' for the unresolvable)

**Comment by mlschroe** [comment]
See https://github.com/openSUSE/perl-BSSolv/commit/785c3b6c98325e159c841478907eea642b01de40
