### ISSUE TITLE
cannot execute rake migrate_options_yml

### ISSUE THREAD

**Issue by dsamx** [openSUSE/open-build-service#8982]
My obs-api package is obs-api-2.10-lp151.10.1.noarch and OBS is running well. But in the systemd output of obs-delayedjob-queue-default.service I saw the message:
```
bundle.ruby2.5[15148]: DEPRECATED: Please update your options.yml by running 'rake migrate_options_yml'
```

So I tried it but it does not work. I have no clue about what is deprecated and why rake breaks:

```
/srv/www/obs/api # rake --trace migrate_options_yml
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/file_utils.rb:10: warning: already initialized constant FileUtils::RUBY
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/file_utils.rb:10: warning: previous definition of RUBY was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/file_utils.rb:109: warning: already initialized constant FileUtils::LN_SUPPORTED
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/file_utils.rb:109: warning: previous definition of LN_SUPPORTED was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/file_utils_ext.rb:17: warning: already initialized constant Rake::FileUtilsExt::DEFAULT
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/file_utils_ext.rb:17: warning: previous definition of DEFAULT was here
WARNING: Possible conflict with Rake extension: String#ext already exists
WARNING: Possible conflict with Rake extension: String#pathmap already exists
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:44: warning: already initialized constant Rake::FileList::ARRAY_METHODS
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:44: warning: previous definition of ARRAY_METHODS was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:47: warning: already initialized constant Rake::FileList::MUST_DEFINE
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:47: warning: previous definition of MUST_DEFINE was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:51: warning: already initialized constant Rake::FileList::MUST_NOT_DEFINE
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:51: warning: previous definition of MUST_NOT_DEFINE was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:55: warning: already initialized constant Rake::FileList::SPECIAL_RETURN
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:55: warning: previous definition of SPECIAL_RETURN was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:61: warning: already initialized constant Rake::FileList::DELEGATING_METHODS
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:61: warning: previous definition of DELEGATING_METHODS was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:86: warning: already initialized constant Rake::FileList::GLOB_PATTERN
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:86: warning: previous definition of GLOB_PATTERN was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:381: warning: already initialized constant Rake::FileList::DEFAULT_IGNORE_PATTERNS
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:381: warning: previous definition of DEFAULT_IGNORE_PATTERNS was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:387: warning: already initialized constant Rake::FileList::DEFAULT_IGNORE_PROCS
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/file_list.rb:387: warning: previous definition of DEFAULT_IGNORE_PROCS was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/version.rb:3: warning: already initialized constant Rake::VERSION
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/version.rb:3: warning: previous definition of VERSION was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/version.rb:6: warning: already initialized constant Rake::Version::MAJOR
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/version.rb:6: warning: previous definition of MAJOR was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/version.rb:6: warning: already initialized constant Rake::Version::MINOR
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/version.rb:6: warning: previous definition of MINOR was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/version.rb:6: warning: already initialized constant Rake::Version::BUILD
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/version.rb:6: warning: previous definition of BUILD was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/version.rb:6: warning: already initialized constant Rake::Version::OTHER
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/version.rb:6: warning: previous definition of OTHER was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/version.rb:8: warning: already initialized constant Rake::Version::NUMBERS
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/version.rb:8: warning: previous definition of NUMBERS was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/linked_list.rb:110: warning: already initialized constant Rake::LinkedList::EMPTY
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/linked_list.rb:110: warning: previous definition of EMPTY was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/scope.rb:41: warning: already initialized constant Rake::Scope::EMPTY
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/scope.rb:41: warning: previous definition of EMPTY was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/promise.rb:12: warning: already initialized constant Rake::Promise::NOT_SET
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/promise.rb:12: warning: previous definition of NOT_SET was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:13: warning: already initialized constant Rake::CommandLineOptionError
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:13: warning: previous definition of CommandLineOptionError was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:41: warning: already initialized constant Rake::Application::DEFAULT_RAKEFILES
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:41: warning: previous definition of DEFAULT_RAKEFILES was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task_arguments.rb:108: warning: already initialized constant Rake::EMPTY_TASK_ARGS
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task_arguments.rb:108: warning: previous definition of EMPTY_TASK_ARGS was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/invocation_chain.rb:55: warning: already initialized constant Rake::InvocationChain::EMPTY
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/invocation_chain.rb:55: warning: previous definition of EMPTY was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/early_time.rb:21: warning: already initialized constant Rake::EARLY
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/early_time.rb:21: warning: previous definition of EARLY was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/late_time.rb:17: warning: already initialized constant Rake::LATE
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/late_time.rb:17: warning: previous definition of LATE was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/backtrace.rb:4: warning: already initialized constant Rake::Backtrace::SYS_KEYS
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/backtrace.rb:4: warning: previous definition of SYS_KEYS was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/backtrace.rb:5: warning: already initialized constant Rake::Backtrace::SYS_PATHS
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/backtrace.rb:5: warning: previous definition of SYS_PATHS was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/backtrace.rb:8: warning: already initialized constant Rake::Backtrace::SUPPRESSED_PATHS
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/backtrace.rb:8: warning: previous definition of SUPPRESSED_PATHS was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/backtrace.rb:12: warning: already initialized constant Rake::Backtrace::SUPPRESSED_PATHS_RE
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/backtrace.rb:12: warning: previous definition of SUPPRESSED_PATHS_RE was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake/backtrace.rb:16: warning: already initialized constant Rake::Backtrace::SUPPRESS_PATTERN
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/backtrace.rb:16: warning: previous definition of SUPPRESS_PATTERN was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake.rb:70: warning: already initialized constant FileList
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake.rb:70: warning: previous definition of FileList was here
/usr/lib64/obs-api/ruby/2.5.0/gems/rake-12.3.2/lib/rake.rb:71: warning: already initialized constant RakeFileUtils
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake.rb:71: warning: previous definition of RakeFileUtils was here
rake aborted!
LoadError: cannot load such file -- single_test/tasks
/usr/lib64/obs-api/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/usr/lib64/obs-api/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/lib64/obs-api/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/lib64/obs-api/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/srv/www/obs/api/Rakefile:12:in `<top (required)>'
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load'
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load_rakefile'
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:703:in `raw_load_rakefile'
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:104:in `block in load_rakefile'
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:103:in `load_rakefile'
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:82:in `block in run'
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/usr/lib64/ruby/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/bin/rake:23:in `load'
/usr/bin/rake:23:in `<main>'
```

**Comment by hennevogel** [comment]
Try executing it with the production environment: 

```shell
rake migrate_options_yml RAILS_ENV=production
```

**Comment by dsamx** [comment]
That helped, thank you.

A backup has been created at 'config/options.yml.bkp'.
Migrating configuration.
Done.

Restarting the service does not print the message anymore.

**Comment by hennevogel** [comment]
we should fix the error message

**Comment by doccaz** [comment]
Got this as well while migrating from 2.9.x to 2.10 on a customer. Unfortunately had to run and get things running for them, so I discarded their options.yml and made a new one from the template. Good to know, thanks.
