### ISSUE TITLE
Flickering test_copy_project_for_release_with_history

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#9138]
Just saw this on #8346 

```
MaintenanceTests
  test_OBS_BranchTarget                                           PASS (1.96s)
  test_branch_from_service_pack_WIP                               PASS (2.32s)
  test_branch_package                                             PASS (4.16s)
  test_branch_package_with_local_link                             PASS (2.53s)
  test_copy_from_origin_with_modification_has_write_permission_check PASS (0.17s)
  test_copy_project_for_release                                   PASS (5.96s)
  test_copy_project_for_release_using_makeoriginolder             PASS (2.02s)
  test_copy_project_for_release_with_history                      FAIL (1.12s)
        --- expected
        +++ actual
        @@ -1 +1 @@
        -"{\"count\"=>\"6\", \"entry\"=>[X({\"name\"=>\"Pack3\"}), X({\"name\"=>\"_product\"}), X({\"name\"=>\"_product:fixed-release\"}), X({\"name\"=>\"pack1\"}), X({\"name\"=>\"pack2\"}), X({\"name\"=>\"patchinfo\"})]}"
        +"{\"count\"=>\"4\", \"entry\"=>[X({\"name\"=>\"Pack3\"}), X({\"name\"=>\"pack1\"}), X({\"name\"=>\"pack2\"}), X({\"name\"=>\"patchinfo\"})]}"
        test/functional/maintenance_test.rb:2469:in `test_copy_project_for_release_with_history'
        test/test_helper.rb:117:in `block in __run'
        test/test_helper.rb:117:in `map'
        test/test_helper.rb:117:in `__run'
```

**Comment by hennevogel** [comment]
You find flickering specs on circle now.

https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests?branch=master&reporting-window=last-30-days
