### ISSUE TITLE
apache error.log Compiling passenger_native_support.so for the current Ruby interpreter

### ISSUE THREAD

**Issue by dasdeniz** [openSUSE/open-build-service#941]
immediately post install apache error.log has:

```
[Mon Jun 08 09:36:05.549541 2015] [mpm_prefork:notice] [pid 16018] AH00163: Apache/2.4.10 (Linux/SUSE) OpenSSL/1.0.1k-fips Phusion_Passenger/5.0.6 configured -- resuming normal operations
[Mon Jun 08 09:36:05.549606 2015] [core:notice] [pid 16018] AH00094: Command line: '/usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SSL -D SYSTEMD -D FOREGROUND'
App 16090 stdout:
App 16090 stderr:  --> Compiling passenger_native_support.so for the current Ruby interpreter...
App 16090 stderr:
App 16090 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 16090 stderr:      Warning: compilation didn't succeed. To learn why, read this file:
App 16090 stderr:      /tmp/passenger_native_support-10e328l.log
App 16090 stderr:  --> Downloading precompiled passenger_native_support.so for the current Ruby interpreter...
App 16090 stderr:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 16090 stderr:      # tar xzf rubyext-ruby-2.1.3-x86_64-linux.tar.gz
App 16090 stderr:
App 16090 stderr:      # rm -f rubyext-ruby-2.1.3-x86_64-linux.tar.gz
App 16090 stderr:      Checking whether downloaded binary is usable...
App 16090 stderr:      # /usr/bin/ruby.ruby2.1 -I. test.rb
App 16090 stderr:      /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': libruby.so.2.1: cannot open shared object file: No such file or directory - /tmp/passenger-native-support-3fgisp/passenger_native_support.so (LoadError)
App 16090 stderr:      	from /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
App 16090 stderr:      	from test.rb:2:in `<main>'
App 16090 stderr:      Binary is not usable.
App 16090 stderr:  --> Continuing without passenger_native_support.so.
```

this is "resolvable" by 

    zypper in ruby2.1-devel
    systemctl restart apache2

**Comment by cwittmer** [comment]
And why not trying to deliver a  valid 'passenger_native_support.so' with the passenger package ?
And the now wanted file to download is not available:
```
[Sun Jul 05 18:53:56 2015] [notice] Apache/2.2.12 (Linux/SUSE) mod_ssl/2.2.12 OpenSSL/0.9.8j-fips PHP/5.3.17 Phusion_Passenger/5.0.6 configured -- resuming normal operations
App 1720 stdout: 
App 1720 stderr:  --> Compiling passenger_native_support.so for the current Ruby interpreter...
App 1720 stderr: 
App 1720 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 1720 stderr: 
App 1720 stderr:      Warning: compilation didn't succeed. To learn why, read this file:
App 1720 stderr:      /tmp/passenger_native_support-1b9i0vm.log
App 1720 stderr:  --> Downloading precompiled passenger_native_support.so for the current Ruby interpreter...
App 1720 stderr:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 1720 stderr:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.0.6/rubyext-ruby-2.1.6-x86_64-linux.tar.gz: The requested URL returned error: 404
App 1720 stderr:      Trying next mirror...
App 1720 stderr:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.0.6/rubyext-ruby-2.1.6-x86_64-linux.tar.gz: The requested URL returned error: 403
App 1720 stderr:  --> Continuing without passenger_native_support.so.
App 1720 stderr: WARN: Unresolved specs during Gem::Specification.reset:
App 1720 stderr: 
App 1720 stderr:       rake (>= 0.8.1)
App 1720 stderr: 
App 1720 stderr: WARN: Clearing out unresolved specs.
App 1720 stderr: 
App 1720 stderr: Please report a bug if this causes problems.
App 1720 stderr: 
App 1720 stderr: /usr/lib64/passenger/5.0.6/bin/passenger-config:32:in `require'
App 1720 stderr: : 
App 1720 stderr: cannot load such file -- phusion_passenger
App 1720 stderr:  (
App 1720 stderr: LoadError
App 1720 stderr: )
App 1720 stderr:        from /usr/lib64/passenger/5.0.6/bin/passenger-config:32:in `<main>'
App 1753 stdout: 
App 1762 stdout:
```

**Comment by hukevinxiaochen** [comment]
Having same error logs on a per-request basis now. This is following changing my PassengerDefaultRuby to `/home/deploy/.rbenv/shims/ruby`. Is it something I need to change in the custom_require.rb, or do I need to change how passenger makes the precompiled binary available?

```
App 11979 stderr:  --> Compiling passenger_native_support.so for the current Ruby interpreter...
App 11979 stderr: 
App 11979 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 11979 stderr: 
App 11979 stderr:  --> Downloading precompiled passenger_native_support.so for the current Ruby interpreter...
App 11979 stderr: 
App 11979 stderr:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 11979 stderr: 
App 11979 stderr:      # tar xzf rubyext-ruby-1.9.3-x86_64-linux.tar.gz
App 11979 stderr:      # rm -f rubyext-ruby-1.9.3-x86_64-linux.tar.gz
App 11979 stderr:      Checking whether downloaded binary is usable...
App 11979 stderr:      # /home/deploy/.rbenv/versions/1.9.3-p392/bin/ruby -I. test.rb
App 11979 stderr:      /home/deploy/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': libruby.so.1.9: cannot open shared object file: No such file or directory - /tmp/passenger-native-support-15x8c4k/passenger_native_support.so (LoadError)
App 11979 stderr:       from /home/deploy/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
App 11979 stderr:       from test.rb:2:in `<main>'
App 11979 stderr:      Binary is not usable.
App 11979 stderr:  --> Continuing without passenger_native_support.so.
```

**Comment by darix** [comment]
if you use rbenv ... you are on your own anyway ...

**Comment by coin8086** [comment]
I'm using RVM Ruby 2.1 on Ubuntu 14.04 + Passenger 5.0.26, while I'm still suffering the similar error:

> 8551 App 9878 stderr:  [passenger_native_support.so] trying to compile for the current user (robert) and Ruby interpreter...
> 8552 App 9878 stderr:
> 8553 App 9878 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
> 8554 App 9878 stderr:
> 8555 App 9878 stderr:      Warning: compilation didn't succeed. To learn why, read this file:
> 8556 App 9878 stderr:      /tmp/passenger_native_support-3g7xic.log                                                                          
> 8557 App 9878 stderr:  [passenger_native_support.so] not downloading because passenger wasn't installed from a release package
> 8558 App 9878 stderr:  [passenger_native_support.so] will not be used (can't compile or download)
> 8559 App 9878 stderr:   --> Passenger will still operate normally.
> 8560 App 9878 stderr: fatal: Not a git repository (or any of the parent directories): .git
> 

What's wrong and what should I do please?
